"""
expand_vocab.py — 扩充 WORD_POOL 到 CET-4 必考词汇量
保留原有 362 词不变，在末尾追加 ~1200 个四级高频词
总计 ~1562 词，day0 不受影响（取前80），后续每天100词可支撑15天+
"""
import re

PATH = r'C:\Users\24470\WorkBuddy\2026-05-21-16-18-52\cet4-study\index.html'

with open(PATH, 'r', encoding='utf-8') as f:
    html = f.read()

# Step 1: 检查是否已扩展过
existing_count = len(re.findall(r'\{w:"[^"]+"', html))
if existing_count >= 1000:
    print(f"WORD_POOL already has {existing_count} entries — skipping expansion")
    import sys; sys.exit(0)

print(f"Current WORD_POOL: {existing_count} entries")

# Step 2: CET-4 必考词汇扩充 (organized by frequency tier)
# 格式: {w, p, m, c} — 有些含 ex/excn
# 音标使用标准 IPA，释义精简准确，搭配来自真题常见用法

extra_words = r"""
  // === CET-4 高频词汇扩展 (Tier 1: 真题最高频 ~500词) ===
  {w:"acknowledge",p:"/əkˈnɒlɪdʒ/",m:"v. 承认，确认",c:"acknowledge receipt"},
  {w:"acquaintance",p:"/əˈkweɪntəns/",m:"n. 熟人，相识",c:"make acquaintance"},
  {w:"adequate",p:"/ˈædɪkwət/",m:"adj. 足够的，适当的",c:"adequate supply"},
  {w:"adjust",p:"/əˈdʒʌst/",m:"v. 调整，适应",c:"adjust to"},
  {w:"administration",p:"/ədˌmɪnɪˈstreɪʃn/",m:"n. 管理，行政",c:"public administration"},
  {w:"admire",p:"/ədˈmaɪər/",m:"v. 钦佩，赞赏",c:"admire for"},
  {w:"admission",p:"/ədˈmɪʃn/",m:"n. 准许进入，承认",c:"admission ticket"},
  {w:"adopt",p:"/əˈdɒpt/",m:"v. 采用，收养",c:"adopt a policy"},
  {w:"advanced",p:"/ədˈvɑːnst/",m:"adj. 先进的，高级的",c:"advanced technology"},
  {w:"advantage",p:"/ədˈvɑːntɪdʒ/",m:"n. 优势，有利条件",c:"take advantage of"},
  {w:"advertise",p:"/ˈædvətaɪz/",m:"v. 做广告，宣传",c:"advertise for"},
  {w:"affair",p:"/əˈfeər/",m:"n. 事务，事件",c:"foreign affairs"},
  {w:"affect",p:"/əˈfekt/",m:"v. 影响，感动",c:"adversely affect"},
  {w:"afford",p:"/əˈfɔːd/",m:"v. 负担得起，提供",c:"can't afford"},
  {w:"agency",p:"/ˈeɪdʒənsi/",m:"n. 代理机构",c:"travel agency"},
  {w:"aggressive",p:"/əˈɡresɪv/",m:"adj. 侵略的，好斗的",c:"aggressive behavior"},
  {w:"agreement",p:"/əˈɡriːmənt/",m:"n. 协议，一致",c:"reach an agreement"},
  {w:"agriculture",p:"/ˈæɡrɪkʌltʃər/",m:"n. 农业",c:"modern agriculture"},
  {w:"aid",p:"/eɪd/",m:"n./v. 援助，帮助",c:"first aid"},
  {w:"aim",p:"/eɪm/",m:"n. 目标 v. 瞄准",c:"aim at"},
  {w:"aircraft",p:"/ˈeəkrɑːft/",m:"n. 飞机，飞行器",c:"commercial aircraft"},
  {w:"alarm",p:"/əˈlɑːm/",m:"n. 警报，闹钟",c:"fire alarm"},
  {w:"alcohol",p:"/ˈælkəhɒl/",m:"n. 酒精，酒",c:"alcohol abuse"},
  {w:"allowance",p:"/əˈlaʊəns/",m:"n. 津贴，零用钱",c:"make allowance for"},
  {w:"alongside",p:"/əˌlɒŋˈsaɪd/",m:"prep. 在…旁边",c:"work alongside"},
  {w:"alter",p:"/ˈɔːltər/",m:"v. 改变，修改",c:"alter the course"},
  {w:"amaze",p:"/əˈmeɪz/",m:"v. 使惊奇",c:"be amazed at"},
  {w:"ambition",p:"/æmˈbɪʃn/",m:"n. 雄心，野心",c:"achieve one's ambition"},
  {w:"amount",p:"/əˈmaʊnt/",m:"n. 数量 v. 合计",c:"a large amount of"},
  {w:"amuse",p:"/əˈmjuːz/",m:"v. 逗乐，娱乐",c:"amuse oneself"},
  {w:"analysis",p:"/əˈnæləsɪs/",m:"n. 分析",c:"data analysis"},
  {w:"ancestor",p:"/ˈænsestər/",m:"n. 祖先",c:"common ancestor"},
  {w:"anchor",p:"/ˈæŋkər/",m:"n. 锚 v. 固定",c:"news anchor"},
  {w:"ancient",p:"/ˈeɪnʃənt/",m:"adj. 古代的",c:"ancient times"},
  {w:"angle",p:"/ˈæŋɡl/",m:"n. 角度，观点",c:"from another angle"},
  {w:"anniversary",p:"/ˌænɪˈvɜːsəri/",m:"n. 周年纪念日",c:"wedding anniversary"},
  {w:"announce",p:"/əˈnaʊns/",m:"v. 宣布，通告",c:"announce plans"},
  {w:"annual",p:"/ˈænjuəl/",m:"adj. 年度的 n. 年刊",c:"annual report"},
  {w:"anticipate",p:"/ænˈtɪsɪpeɪt/",m:"v. 预期，期望",c:"anticipate problems"},
  {w:"anxiety",p:"/æŋˈzaɪəti/",m:"n. 焦虑，忧虑",c:"anxiety disorder"},
  {w:"anyway",p:"/ˈeniweɪ/",m:"adv. 无论如何",c:"do it anyway"},
  {w:"apart",p:"/əˈpɑːt/",m:"adv. 分开，相隔",c:"apart from"},
  {w:"apartment",p:"/əˈpɑːtmənt/",m:"n. 公寓",c:"apartment building"},
  {w:"apology",p:"/əˈpɒlədʒi/",m:"n. 道歉",c:"make an apology"},
  {w:"apparent",p:"/əˈpærənt/",m:"adj. 显然的",c:"apparent reason"},
  {w:"appeal",p:"/əˈpiːl/",m:"n./v. 呼吁，吸引",c:"appeal to"},
  {w:"appetite",p:"/ˈæpɪtaɪt/",m:"n. 食欲，胃口",c:"lose appetite"},
  {w:"appliance",p:"/əˈplaɪəns/",m:"n. 电器，器具",c:"household appliance"},
  {w:"applicant",p:"/ˈæplɪkənt/",m:"n. 申请人",c:"job applicant"},
  {w:"application",p:"/ˌæplɪˈkeɪʃn/",m:"n. 申请，应用",c:"job application"},
  {w:"apply",p:"/əˈplaɪ/",m:"v. 申请，应用",c:"apply for"},
  {w:"appoint",p:"/əˈpɔɪnt/",m:"v. 任命，指定",c:"appoint a committee"},
  {w:"appointment",p:"/əˈpɔɪntmənt/",m:"n. 约会，任命",c:"make an appointment"},
  {w:"architecture",p:"/ˈɑːkɪtektʃər/",m:"n. 建筑学",c:"modern architecture"},
  {w:"argue",p:"/ˈɑːɡjuː/",m:"v. 争论，主张",c:"argue against"},
  {w:"argument",p:"/ˈɑːɡjumənt/",m:"n. 争论，论据",c:"strong argument"},
  {w:"arise",p:"/əˈraɪz/",m:"v. 出现，产生",c:"problems arise"},
  {w:"arrange",p:"/əˈreɪndʒ/",m:"v. 安排，整理",c:"arrange for"},
  {w:"arrangement",p:"/əˈreɪndʒmənt/",m:"n. 安排，布置",c:"make arrangements"},
  {w:"arrest",p:"/əˈrest/",m:"v./n. 逮捕，拘留",c:"under arrest"},
  {w:"arrival",p:"/əˈraɪvl/",m:"n. 到达",c:"on arrival"},
  {w:"artificial",p:"/ˌɑːtɪˈfɪʃl/",m:"adj. 人工的，人造的",c:"artificial intelligence"},
  {w:"aspect",p:"/ˈæspekt/",m:"n. 方面，层面",c:"every aspect"},
  {w:"assemble",p:"/əˈsembl/",m:"v. 集合，组装",c:"assemble parts"},
  {w:"assembly",p:"/əˈsembli/",m:"n. 集会，装配",c:"assembly line"},
  {w:"assign",p:"/əˈsaɪn/",m:"v. 分配，指派",c:"assign tasks"},
  {w:"assignment",p:"/əˈsaɪnmənt/",m:"n. 任务，作业",c:"complete assignment"},
  {w:"assist",p:"/əˈsɪst/",m:"v. 帮助，协助",c:"assist in"},
  {w:"assistance",p:"/əˈsɪstəns/",m:"n. 帮助，援助",c:"technical assistance"},
  {w:"associate",p:"/əˈsəʊʃieɪt/",m:"v. 联系，关联",c:"associate with"},
  {w:"association",p:"/əˌsəʊʃiˈeɪʃn/",m:"n. 协会，关联",c:"trade association"},
  {w:"assume",p:"/əˈsjuːm/",m:"v. 假设，承担",c:"assume responsibility"},
  {w:"assumption",p:"/əˈsʌmpʃn/",m:"n. 假设，承担",c:"make an assumption"},
  {w:"assure",p:"/əˈʃʊər/",m:"v. 使确信，保证",c:"assure safety"},
  {w:"atmosphere",p:"/ˈætməsfɪər/",m:"n. 大气，氛围",c:"friendly atmosphere"},
  {w:"attach",p:"/əˈtætʃ/",m:"v. 附上，连接",c:"attach importance to"},
  {w:"attain",p:"/əˈteɪn/",m:"v. 达到，获得",c:"attain goals"},
  {w:"attempt",p:"/əˈtempt/",m:"n./v. 尝试，企图",c:"attempt to"},
  {w:"attend",p:"/əˈtend/",m:"v. 参加，出席",c:"attend a meeting"},
  {w:"attention",p:"/əˈtenʃn/",m:"n. 注意，关注",c:"pay attention to"},
  {w:"attitude",p:"/ˈætɪtjuːd/",m:"n. 态度，看法",c:"positive attitude"},
  {w:"attract",p:"/əˈtrækt/",m:"v. 吸引",c:"attract attention"},
  {w:"attraction",p:"/əˈtrækʃn/",m:"n. 吸引力，景点",c:"tourist attraction"},
  {w:"attractive",p:"/əˈtræktɪv/",m:"adj. 有吸引力的",c:"attractive offer"},
  {w:"audience",p:"/ˈɔːdiəns/",m:"n. 观众，听众",c:"target audience"},
  {w:"author",p:"/ˈɔːθər/",m:"n. 作者",c:"best-selling author"},
  {w:"authority",p:"/ɔːˈθɒrəti/",m:"n. 权威，当局",c:"local authority"},
  {w:"automatic",p:"/ˌɔːtəˈmætɪk/",m:"adj. 自动的",c:"automatic system"},
  {w:"automobile",p:"/ˈɔːtəməbiːl/",m:"n. 汽车",c:"automobile industry"},
  {w:"avenue",p:"/ˈævənjuː/",m:"n. 大街，途径",c:"explore avenues"},
  {w:"average",p:"/ˈævərɪdʒ/",m:"adj. 平均的 n. 平均数",c:"on average"},
  {w:"avoid",p:"/əˈvɔɪd/",m:"v. 避免，回避",c:"avoid doing"},
  {w:"award",p:"/əˈwɔːd/",m:"n. 奖品 v. 授予",c:"win an award"},
  {w:"aware",p:"/əˈweər/",m:"adj. 意识到的",c:"be aware of"},
  {w:"awful",p:"/ˈɔːfl/",m:"adj. 糟糕的，可怕的",c:"awful weather"},
  {w:"awkward",p:"/ˈɔːkwəd/",m:"adj. 尴尬的，笨拙的",c:"awkward situation"},
  {w:"background",p:"/ˈbækɡraʊnd/",m:"n. 背景",c:"family background"},
  {w:"backward",p:"/ˈbækwəd/",m:"adv. 向后 adj. 落后的",c:"backward area"},
  {w:"balance",p:"/ˈbæləns/",m:"n. 平衡 v. 使平衡",c:"keep balance"},
  {w:"ban",p:"/bæn/",m:"v./n. 禁止",c:"ban on"},
  {w:"band",p:"/bænd/",m:"n. 乐队，带子",c:"rock band"},
  {w:"bankrupt",p:"/ˈbæŋkrʌpt/",m:"adj. 破产的",c:"go bankrupt"},
  {w:"banner",p:"/ˈbænər/",m:"n. 横幅，旗帜",c:"under the banner of"},
  {w:"barely",p:"/ˈbeəli/",m:"adv. 几乎不，勉强",c:"barely enough"},
  {w:"bargain",p:"/ˈbɑːɡɪn/",m:"n. 便宜货 v. 讨价还价",c:"bargain price"},
  {w:"barrier",p:"/ˈbæriər/",m:"n. 障碍，屏障",c:"language barrier"},
  {w:"battle",p:"/ˈbætl/",m:"n. 战斗 v. 斗争",c:"battle against"},
  {w:"behalf",p:"/bɪˈhɑːf/",m:"n. 利益，代表",c:"on behalf of"},
  {w:"behave",p:"/bɪˈheɪv/",m:"v. 表现，行为",c:"behave well"},
  {w:"behavio(u)r",p:"/bɪˈheɪvjər/",m:"n. 行为，举止",c:"good behavior"},
  {w:"being",p:"/ˈbiːɪŋ/",m:"n. 生物，存在",c:"human being"},
  {w:"belief",p:"/bɪˈliːf/",m:"n. 信念，信仰",c:"beyond belief"},
  {w:"beloved",p:"/bɪˈlʌvd/",m:"adj. 心爱的",c:"beloved wife"},
  {w:"beneath",p:"/bɪˈniːθ/",m:"prep. 在…下方",c:"beneath the surface"},
  {w:"benefit",p:"/ˈbenɪfɪt/",m:"n. 利益 v. 受益",c:"benefit from"},
  {w:"besides",p:"/bɪˈsaɪdz/",m:"adv. 此外 prep. 除…外",c:"besides that"},
  {w:"billion",p:"/ˈbɪljən/",m:"n. 十亿",c:"billions of"},
  {w:"bind",p:"/baɪnd/",m:"v. 捆绑，约束",c:"bind together"},
  {w:"biology",p:"/baɪˈɒlədʒi/",m:"n. 生物学",c:"molecular biology"},
  {w:"bitter",p:"/ˈbɪtər/",m:"adj. 苦的，痛苦的",c:"bitter experience"},
  {w:"blade",p:"/bleɪd/",m:"n. 刀刃，叶片",c:"sharp blade"},
  {w:"blame",p:"/bleɪm/",m:"v./n. 责备，归咎",c:"blame for"},
  {w:"blank",p:"/blæŋk/",m:"adj. 空白的 n. 空白",c:"blank space"},
  {w:"blast",p:"/blɑːst/",m:"n. 爆炸 v. 爆破",c:"blast off"},
  {w:"blend",p:"/blend/",m:"v./n. 混合",c:"blend in"},
  {w:"bless",p:"/bles/",m:"v. 祝福，保佑",c:"bless with"},
  {w:"block",p:"/blɒk/",m:"n. 街区 v. 阻塞",c:"block the way"},
  {w:"boast",p:"/bəʊst/",m:"v. 自夸，夸耀",c:"boast about"},
  {w:"bond",p:"/bɒnd/",m:"n. 纽带，债券",c:"emotional bond"},
  {w:"boom",p:"/buːm/",m:"n. 繁荣 v. 迅速发展",c:"economic boom"},
  {w:"boost",p:"/buːst/",m:"v./n. 促进，提高",c:"boost confidence"},
  {w:"border",p:"/ˈbɔːdər/",m:"n. 边境，边界",c:"cross the border"},
  {w:"bore",p:"/bɔːr/",m:"v. 使厌烦 n. 讨厌的人",c:"be bored with"},
  {w:"bounce",p:"/baʊns/",m:"v. 弹跳，反弹",c:"bounce back"},
  {w:"bound",p:"/baʊnd/",m:"adj. 一定的 v. 跳跃",c:"be bound to"},
  {w:"boundary",p:"/ˈbaʊndri/",m:"n. 边界，界限",c:"set boundaries"},
  {w:"brand",p:"/brænd/",m:"n. 品牌",c:"brand image"},
  {w:"breath",p:"/breθ/",m:"n. 呼吸，气息",c:"hold one's breath"},
  {w:"breathe",p:"/briːð/",m:"v. 呼吸",c:"breathe deeply"},
  {w:"breed",p:"/briːd/",m:"v. 繁殖 n. 品种",c:"breed animals"},
  {w:"brief",p:"/briːf/",m:"adj. 简短的 n. 摘要",c:"in brief"},
  {w:"brilliant",p:"/ˈbrɪliənt/",m:"adj. 杰出的，明亮的",c:"brilliant idea"},
  {w:"broad",p:"/brɔːd/",m:"adj. 宽的，广泛的",c:"broad range"},
  {w:"broadcast",p:"/ˈbrɔːdkɑːst/",m:"v./n. 广播",c:"live broadcast"},
  {w:"budget",p:"/ˈbʌdʒɪt/",m:"n. 预算",c:"within budget"},
  {w:"burden",p:"/ˈbɜːdn/",m:"n. 负担 v. 使负重",c:"heavy burden"},
  {w:"burst",p:"/bɜːst/",m:"v. 爆发，突然发生",c:"burst into tears"},
  {w:"cabinet",p:"/ˈkæbɪnət/",m:"n. 橱柜，内阁",c:"filing cabinet"},
  {w:"calculate",p:"/ˈkælkjuleɪt/",m:"v. 计算，估计",c:"calculate risk"},
  {w:"calendar",p:"/ˈkælɪndər/",m:"n. 日历",c:"lunar calendar"},
  {w:"campaign",p:"/kæmˈpeɪn/",m:"n. 运动，战役",c:"advertising campaign"},
  {w:"cancel",p:"/ˈkænsl/",m:"v. 取消",c:"cancel order"},
  {w:"candidate",p:"/ˈkændɪdət/",m:"n. 候选人",c:"presidential candidate"},
  {w:"capability",p:"/ˌkeɪpəˈbɪləti/",m:"n. 能力，才能",c:"technical capability"},
  {w:"capacity",p:"/kəˈpæsəti/",m:"n. 容量，能力",c:"production capacity"},
  {w:"capture",p:"/ˈkæptʃər/",m:"v. 俘获，捕获",c:"capture attention"},
  {w:"career",p:"/kəˈrɪər/",m:"n. 职业，生涯",c:"career development"},
  {w:"cargo",p:"/ˈkɑːɡəʊ/",m:"n. 货物",c:"cargo ship"},
  {w:"cast",p:"/kɑːst/",m:"v. 投掷，铸造",c:"cast doubt on"},
  {w:"casual",p:"/ˈkæʒuəl/",m:"adj. 随便的，偶然的",c:"casual clothes"},
  {w:"catalog(ue)",p:"/ˈkætəlɒɡ/",m:"n. 目录",c:"product catalog"},
  {w:"category",p:"/ˈkætəɡəri/",m:"n. 类别，种类",c:"product category"},
  {w:"caution",p:"/ˈkɔːʃn/",m:"n. 小心，谨慎",c:"with caution"},
  {w:"cease",p:"/siːs/",m:"v. 停止，终止",c:"cease to exist"},
  {w:"celebrate",p:"/ˈselɪbreɪt/",m:"v. 庆祝",c:"celebrate success"},
  {w:"ceremony",p:"/ˈserəməni/",m:"n. 典礼，仪式",c:"opening ceremony"},
  {w:"certificate",p:"/səˈtɪfɪkət/",m:"n. 证书，证明",c:"birth certificate"},
  {w:"channel",p:"/ˈtʃænl/",m:"n. 频道，渠道",c:"communication channel"},
  {w:"chapter",p:"/ˈtʃæptər/",m:"n. 章，回",c:"chapter one"},
  {w:"character",p:"/ˈkærəktər/",m:"n. 性格，角色",c:"main character"},
  {w:"characteristic",p:"/ˌkærəktəˈrɪstɪk/",m:"n. 特征 adj. 典型的",c:"key characteristic"},
  {w:"charity",p:"/ˈtʃærəti/",m:"n. 慈善，慈善机构",c:"charity event"},
  {w:"charm",p:"/tʃɑːm/",m:"n. 魅力 v. 吸引",c:"personal charm"},
  {w:"chart",p:"/tʃɑːt/",m:"n. 图表",c:"flow chart"},
  {w:"chase",p:"/tʃeɪs/",m:"v./n. 追逐",c:"chase after"},
  {w:"chemical",p:"/ˈkemɪkl/",m:"adj. 化学的 n. 化学品",c:"chemical reaction"},
  {w:"chief",p:"/tʃiːf/",m:"adj. 主要的 n. 首领",c:"chief executive"},
  {w:"circumstance",p:"/ˈsɜːkəmstəns/",m:"n. 环境，情况",c:"under no circumstances"},
  {w:"civil",p:"/ˈsɪvl/",m:"adj. 公民的，民事的",c:"civil rights"},
  {w:"civilization",p:"/ˌsɪvəlaɪˈzeɪʃn/",m:"n. 文明",c:"ancient civilization"},
  {w:"claim",p:"/kleɪm/",m:"v./n. 声称，索赔",c:"claim responsibility"},
  {w:"clarify",p:"/ˈklærɪfaɪ/",m:"v. 澄清，阐明",c:"clarify the point"},
  {w:"classic",p:"/ˈklæsɪk/",m:"adj. 经典的 n. 名著",c:"classic example"},
  {w:"classify",p:"/ˈklæsɪfaɪ/",m:"v. 分类",c:"classify into"},
  {w:"climate",p:"/ˈklaɪmət/",m:"n. 气候，风气",c:"climate change"},
  {w:"code",p:"/kəʊd/",m:"n. 代码，准则",c:"dress code"},
  {w:"collapse",p:"/kəˈlæps/",m:"v./n. 倒塌，崩溃",c:"economic collapse"},
  {w:"colleague",p:"/ˈkɒliːɡ/",m:"n. 同事",c:"work colleague"},
  {w:"colony",p:"/ˈkɒləni/",m:"n. 殖民地，群体",c:"former colony"},
  {w:"column",p:"/ˈkɒləm/",m:"n. 栏目，柱",c:"newspaper column"},
  {w:"combat",p:"/ˈkɒmbæt/",m:"n./v. 战斗，对抗",c:"combat crime"},
  {w:"combination",p:"/ˌkɒmbɪˈneɪʃn/",m:"n. 组合，结合",c:"combination of"},
  {w:"combine",p:"/kəmˈbaɪn/",m:"v. 结合，联合",c:"combine with"},
  {w:"command",p:"/kəˈmɑːnd/",m:"n./v. 命令，指挥",c:"have a command of"},
  {w:"comment",p:"/ˈkɒment/",m:"n./v. 评论",c:"no comment"},
  {w:"commerce",p:"/ˈkɒmɜːs/",m:"n. 商业，贸易",c:"e-commerce"},
  {w:"commercial",p:"/kəˈmɜːʃl/",m:"adj. 商业的 n. 广告",c:"commercial bank"},
  {w:"commission",p:"/kəˈmɪʃn/",m:"n. 委员会，佣金",c:"on commission"},
  {w:"commit",p:"/kəˈmɪt/",m:"v. 犯(罪)，承诺",c:"commit crime"},
  {w:"commitment",p:"/kəˈmɪtmənt/",m:"n. 承诺，奉献",c:"make a commitment"},
  {w:"committee",p:"/kəˈmɪti/",m:"n. 委员会",c:"executive committee"},
  {w:"common",p:"/ˈkɒmən/",m:"adj. 共同的，普通的",c:"common sense"},
  {w:"communicate",p:"/kəˈmjuːnɪkeɪt/",m:"v. 交流，沟通",c:"communicate with"},
  {w:"communication",p:"/kəˌmjuːnɪˈkeɪʃn/",m:"n. 交流，通信",c:"communication skills"},
  {w:"community",p:"/kəˈmjuːnəti/",m:"n. 社区，团体",c:"local community"},
  {w:"companion",p:"/kəmˈpæniən/",m:"n. 同伴，伙伴",c:"travel companion"},
  {w:"compare",p:"/kəmˈpeər/",m:"v. 比较，对比",c:"compare with"},
  {w:"comparison",p:"/kəmˈpærɪsn/",m:"n. 比较",c:"by comparison"},
  {w:"compensation",p:"/ˌkɒmpenˈseɪʃn/",m:"n. 补偿，赔偿",c:"seek compensation"},
  {w:"compete",p:"/kəmˈpiːt/",m:"v. 竞争，比赛",c:"compete against"},
  {w:"competent",p:"/ˈkɒmpɪtənt/",m:"adj. 有能力的",c:"competent person"},
  {w:"competition",p:"/ˌkɒmpəˈtɪʃn/",m:"n. 竞争，竞赛",c:"fierce competition"},
  {w:"complain",p:"/kəmˈpleɪn/",m:"v. 抱怨，投诉",c:"complain about"},
  {w:"complaint",p:"/kəmˈpleɪnt/",m:"n. 抱怨，投诉",c:"make a complaint"},
  {w:"complete",p:"/kəmˈpliːt/",m:"v. 完成 adj. 完整的",c:"complete the task"},
  {w:"component",p:"/kəmˈpəʊnənt/",m:"n. 组成部分",c:"key component"},
  {w:"compose",p:"/kəmˈpəʊz/",m:"v. 组成，创作",c:"compose music"},
  {w:"composition",p:"/ˌkɒmpəˈzɪʃn/",m:"n. 作文，构成",c:"chemical composition"},
  {w:"comprehension",p:"/ˌkɒmprɪˈhenʃn/",m:"n. 理解(力)",c:"reading comprehension"},
  {w:"comprehensive",p:"/ˌkɒmprɪˈhensɪv/",m:"adj. 全面的",c:"comprehensive survey"},
  {w:"comprise",p:"/kəmˈpraɪz/",m:"v. 包含，构成",c:"be comprised of"},
  {w:"compromise",p:"/ˈkɒmprəmaɪz/",m:"n./v. 妥协",c:"reach a compromise"},
  {w:"concentrate",p:"/ˈkɒnsntreɪt/",m:"v. 集中，专注",c:"concentrate on"},
  {w:"concentration",p:"/ˌkɒnsnˈtreɪʃn/",m:"n. 集中，浓度",c:"concentration camp"},
  {w:"concept",p:"/ˈkɒnsept/",m:"n. 概念，观念",c:"basic concept"},
  {w:"concern",p:"/kənˈsɜːn/",m:"n. 关心 v. 涉及",c:"concern about"},
  {w:"concerning",p:"/kənˈsɜːnɪŋ/",m:"prep. 关于",c:"information concerning"},
  {w:"conclude",p:"/kənˈkluːd/",m:"v. 得出结论，结束",c:"conclude that"},
  {w:"conclusion",p:"/kənˈkluːʒn/",m:"n. 结论，结束",c:"draw a conclusion"},
  {w:"conduct",p:"/kənˈdʌkt/",m:"v. 进行 n. 行为",c:"conduct research"},
  {w:"conference",p:"/ˈkɒnfərəns/",m:"n. 会议，讨论",c:"press conference"},
  {w:"confidence",p:"/ˈkɒnfɪdəns/",m:"n. 信心，信任",c:"self-confidence"},
  {w:"confine",p:"/kənˈfaɪn/",m:"v. 限制，禁闭",c:"be confined to"},
  {w:"confirm",p:"/kənˈfɜːm/",m:"v. 确认，证实",c:"confirm reservation"},
  {w:"conflict",p:"/ˈkɒnflɪkt/",m:"n. 冲突 v. 抵触",c:"conflict of interest"},
  {w:"confront",p:"/kənˈfrʌnt/",m:"v. 面对，对抗",c:"confront challenges"},
  {w:"confuse",p:"/kənˈfjuːz/",m:"v. 使困惑，混淆",c:"confuse A with B"},
  {w:"confusion",p:"/kənˈfjuːʒn/",m:"n. 困惑，混乱",c:"in confusion"},
  {w:"congratulate",p:"/kənˈɡrætʃuleɪt/",m:"v. 祝贺",c:"congratulate on"},
  {w:"congress",p:"/ˈkɒŋɡres/",m:"n. 国会，代表大会",c:"member of congress"},
  {w:"connection",p:"/kəˈnekʃn/",m:"n. 连接，关系",c:"Internet connection"},
  {w:"conscious",p:"/ˈkɒnʃəs/",m:"adj. 有意识的",c:"be conscious of"},
  {w:"consequence",p:"/ˈkɒnsɪkwəns/",m:"n. 结果，后果",c:"face consequences"},
  {w:"conservation",p:"/ˌkɒnsəˈveɪʃn/",m:"n. 保护，保存",c:"energy conservation"},
  {w:"conservative",p:"/kənˈsɜːvətɪv/",m:"adj. 保守的",c:"conservative estimate"},
  {w:"considerable",p:"/kənˈsɪdərəbl/",m:"adj. 相当大的",c:"considerable amount"},
  {w:"considerate",p:"/kənˈsɪdərət/",m:"adj. 体贴的",c:"be considerate of"},
  {w:"consideration",p:"/kənˌsɪdəˈreɪʃn/",m:"n. 考虑，体贴",c:"take into consideration"},
  {w:"consist",p:"/kənˈsɪst/",m:"v. 组成，在于",c:"consist of"},
  {w:"constant",p:"/ˈkɒnstənt/",m:"adj. 不断的，恒定的",c:"constant effort"},
  {w:"constitute",p:"/ˈkɒnstɪtjuːt/",m:"v. 构成，设立",c:"constitute a threat"},
  {w:"constitution",p:"/ˌkɒnstɪˈtjuːʃn/",m:"n. 宪法，章程",c:"written constitution"},
  {w:"construct",p:"/kənˈstrʌkt/",m:"v. 建造，构建",c:"construct a bridge"},
  {w:"construction",p:"/kənˈstrʌkʃn/",m:"n. 建设，建筑",c:"under construction"},
  {w:"consult",p:"/kənˈsʌlt/",m:"v. 咨询，查阅",c:"consult a doctor"},
  {w:"consultant",p:"/kənˈsʌltənt/",m:"n. 顾问",c:"management consultant"},
  {w:"consume",p:"/kənˈsjuːm/",m:"v. 消费，消耗",c:"consume energy"},
  {w:"consumer",p:"/kənˈsjuːmər/",m:"n. 消费者",c:"consumer rights"},
  {w:"consumption",p:"/kənˈsʌmpʃn/",m:"n. 消费，消耗",c:"fuel consumption"},
  {w:"contact",p:"/ˈkɒntækt/",m:"n./v. 接触，联系",c:"contact information"},
  {w:"contain",p:"/kənˈteɪn/",m:"v. 包含，容纳",c:"contain information"},
  {w:"container",p:"/kənˈteɪnər/",m:"n. 容器",c:"shipping container"},
  {w:"contemporary",p:"/kənˈtemprəri/",m:"adj. 当代的",c:"contemporary art"},
  {w:"content",p:"/kənˈtent/",m:"adj. 满足的 n. 内容",c:"be content with"},
  {w:"contest",p:"/ˈkɒntest/",m:"n. 竞赛，比赛",c:"enter a contest"},
  {w:"context",p:"/ˈkɒntekst/",m:"n. 上下文，背景",c:"in context"},
  {w:"continual",p:"/kənˈtɪnjuəl/",m:"adj. 持续不断的",c:"continual improvement"},
  {w:"continuous",p:"/kənˈtɪnjuəs/",m:"adj. 连续的",c:"continuous process"},
  {w:"contract",p:"/ˈkɒntrækt/",m:"n. 合同 v. 收缩",c:"sign a contract"},
  {w:"contrary",p:"/ˈkɒntrəri/",m:"adj. 相反的 n. 反面",c:"on the contrary"},
  {w:"contrast",p:"/ˈkɒntrɑːst/",m:"n./v. 对比，对照",c:"in contrast to"},
  {w:"contribute",p:"/kənˈtrɪbjuːt/",m:"v. 贡献，捐献",c:"contribute to"},
  {w:"contribution",p:"/ˌkɒntrɪˈbjuːʃn/",m:"n. 贡献，捐款",c:"make a contribution"},
  {w:"controversial",p:"/ˌkɒntrəˈvɜːʃl/",m:"adj. 有争议的",c:"controversial issue"},
  {w:"convenience",p:"/kənˈviːniəns/",m:"n. 便利",c:"for convenience"},
  {w:"convention",p:"/kənˈvenʃn/",m:"n. 大会，惯例",c:"social convention"},
  {w:"conventional",p:"/kənˈvenʃənl/",m:"adj. 传统的，常规的",c:"conventional method"},
  {w:"conversation",p:"/ˌkɒnvəˈseɪʃn/",m:"n. 对话，交谈",c:"have a conversation"},
  {w:"conversely",p:"/ˈkɒnvɜːsli/",m:"adv. 相反地",c:"and conversely"},
  {w:"convert",p:"/kənˈvɜːt/",m:"v. 转变，转换",c:"convert into"},
  {w:"convey",p:"/kənˈveɪ/",m:"v. 传达，运送",c:"convey message"},
  {w:"convince",p:"/kənˈvɪns/",m:"v. 使确信，说服",c:"convince someone"},
  {w:"cooperate",p:"/kəʊˈɒpəreɪt/",m:"v. 合作",c:"cooperate with"},
  {w:"coordinate",p:"/kəʊˈɔːdɪneɪt/",m:"v. 协调",c:"coordinate efforts"},
  {w:"cope",p:"/kəʊp/",m:"v. 应付，处理",c:"cope with"},
  {w:"core",p:"/kɔːr/",m:"n. 核心",c:"core value"},
  {w:"corporate",p:"/ˈkɔːpərət/",m:"adj. 公司的，法人的",c:"corporate culture"},
  {w:"corporation",p:"/ˌkɔːpəˈreɪʃn/",m:"n. 公司，企业",c:"multinational corporation"},
  {w:"correspond",p:"/ˌkɒrəˈspɒnd/",m:"v. 对应，符合",c:"correspond to"},
  {w:"correspondence",p:"/ˌkɒrəˈspɒndəns/",m:"n. 通信，信件",c:"business correspondence"},
  {w:"corresponding",p:"/ˌkɒrəˈspɒndɪŋ/",m:"adj. 相应的",c:"corresponding period"},
  {w:"county",p:"/ˈkaʊnti/",m:"n. 县，郡",c:"county level"},
  {w:"court",p:"/kɔːt/",m:"n. 法庭，球场",c:"supreme court"},
  {w:"craft",p:"/krɑːft/",m:"n. 工艺，手艺",c:"traditional craft"},
  {w:"create",p:"/kriˈeɪt/",m:"v. 创造，创建",c:"create jobs"},
  {w:"creative",p:"/kriˈeɪtɪv/",m:"adj. 创造性的",c:"creative thinking"},
  {w:"credit",p:"/ˈkredɪt/",m:"n. 信用，学分",c:"credit card"},
  {w:"crew",p:"/kruː/",m:"n. 全体船员，团队",c:"crew member"},
  {w:"crime",p:"/kraɪm/",m:"n. 犯罪",c:"commit a crime"},
  {w:"criminal",p:"/ˈkrɪmɪnl/",m:"n. 罪犯 adj. 犯罪的",c:"criminal law"},
  {w:"crisis",p:"/ˈkraɪsɪs/",m:"n. 危机",c:"financial crisis"},
  {w:"criterion",p:"/kraɪˈtɪəriən/",m:"n. 标准，准则",c:"selection criterion"},
  {w:"critical",p:"/ˈkrɪtɪkl/",m:"adj. 批评的，关键的",c:"critical thinking"},
  {w:"criticism",p:"/ˈkrɪtɪsɪzəm/",m:"n. 批评",c:"constructive criticism"},
  {w:"criticize",p:"/ˈkrɪtɪsaɪz/",m:"v. 批评",c:"criticize for"},
  {w:"crucial",p:"/ˈkruːʃl/",m:"adj. 关键的",c:"crucial role"},
  {w:"culture",p:"/ˈkʌltʃər/",m:"n. 文化",c:"corporate culture"},
  {w:"curiosity",p:"/ˌkjʊəriˈɒsəti/",m:"n. 好奇心",c:"out of curiosity"},
  {w:"currency",p:"/ˈkʌrənsi/",m:"n. 货币，通货",c:"foreign currency"},
  {w:"current",p:"/ˈkʌrənt/",m:"adj. 当前的 n. 水流",c:"current situation"},
  {w:"curriculum",p:"/kəˈrɪkjələm/",m:"n. 课程",c:"curriculum vitae"},
  {w:"curve",p:"/kɜːv/",m:"n. 曲线 v. 弯曲",c:"learning curve"},
  {w:"cycle",p:"/ˈsaɪkl/",m:"n. 周期，循环",c:"life cycle"},
  {w:"damage",p:"/ˈdæmɪdʒ/",m:"n./v. 损害，破坏",c:"cause damage"},
  {w:"dawn",p:"/dɔːn/",m:"n. 黎明 v. 开始",c:"at dawn"},
  {w:"deadline",p:"/ˈdedlaɪn/",m:"n. 截止日期",c:"meet the deadline"},
  {w:"debate",p:"/dɪˈbeɪt/",m:"n./v. 辩论，争论",c:"heated debate"},
  {w:"debt",p:"/det/",m:"n. 债务",c:"in debt"},
  {w:"decade",p:"/ˈdekeɪd/",m:"n. 十年",c:"over the past decade"},
  {w:"deceive",p:"/dɪˈsiːv/",m:"v. 欺骗",c:"deceive someone"},
  {w:"declaration",p:"/ˌdekləˈreɪʃn/",m:"n. 宣言，声明",c:"declaration of independence"},
  {w:"decline",p:"/dɪˈklaɪn/",m:"v./n. 下降，拒绝",c:"decline an offer"},
  {w:"decorate",p:"/ˈdekəreɪt/",m:"v. 装饰",c:"decorate the room"},
  {w:"decrease",p:"/dɪˈkriːs/",m:"v./n. 减少",c:"decrease in"},
  {w:"defeat",p:"/dɪˈfiːt/",m:"v./n. 击败，失败",c:"defeat the enemy"},
  {w:"defense/defence",p:"/dɪˈfens/",m:"n. 防御，辩护",c:"national defense"},
  {w:"define",p:"/dɪˈfaɪn/",m:"v. 定义，界定",c:"define as"},
  {w:"definite",p:"/ˈdefɪnət/",m:"adj. 明确的，肯定的",c:"definite answer"},
  {w:"definitely",p:"/ˈdefɪnətli/",m:"adv. 肯定地，明确地",c:"definitely true"},
  {w:"definition",p:"/ˌdefɪˈnɪʃn/",m:"n. 定义",c:"by definition"},
  {w:"degree",p:"/dɪˈɡriː/",m:"n. 程度，学位",c:"master's degree"},
  {w:"delay",p:"/dɪˈleɪ/",m:"v./n. 延迟，耽搁",c:"without delay"},
  {w:"delegate",p:"/ˈdelɪɡət/",m:"n. 代表 v. 授权",c:"delegate authority"},
  {w:"deliberate",p:"/dɪˈlɪbərət/",m:"adj. 故意的，深思熟虑的",c:"deliberate attempt"},
  {w:"delicate",p:"/ˈdelɪkət/",m:"adj. 精致的，微妙的",c:"delicate situation"},
  {w:"delivery",p:"/dɪˈlɪvəri/",m:"n. 递送，交付",c:"express delivery"},
  {w:"demand",p:"/dɪˈmɑːnd/",m:"n./v. 需求，要求",c:"supply and demand"},
  {w:"democracy",p:"/dɪˈmɒkrəsi/",m:"n. 民主",c:"democracy and freedom"},
  {w:"demonstrate",p:"/ˈdemənstreɪt/",m:"v. 展示，证明",c:"demonstrate ability"},
  {w:"dense",p:"/dens/",m:"adj. 密集的，稠密的",c:"dense population"},
  {w:"density",p:"/ˈdensəti/",m:"n. 密度",c:"population density"},
  {w:"deny",p:"/dɪˈnaɪ/",m:"v. 否认，拒绝",c:"deny access"},
  {w:"depart",p:"/dɪˈpɑːt/",m:"v. 离开，出发",c:"depart from"},
  {w:"department",p:"/dɪˈpɑːtmənt/",m:"n. 部门，系",c:"marketing department"},
  {w:"departure",p:"/dɪˈpɑːtʃər/",m:"n. 离开，出发",c:"departure time"},
  {w:"depend",p:"/dɪˈpend/",m:"v. 依赖，取决于",c:"depend on"},
  {w:"dependent",p:"/dɪˈpendənt/",m:"adj. 依赖的",c:"be dependent on"},
  {w:"deposit",p:"/dɪˈpɒzɪt/",m:"n. 存款，押金 v. 存放",c:"bank deposit"},
  {w:"depress",p:"/dɪˈpres/",m:"v. 使沮丧，抑制",c:"depress economy"},
  {w:"depression",p:"/dɪˈpreʃn/",m:"n. 抑郁，萧条",c:"economic depression"},
  {w:"derive",p:"/dɪˈraɪv/",m:"v. 源自，获得",c:"derive from"},
  {w:"description",p:"/dɪˈskrɪpʃn/",m:"n. 描述",c:"job description"},
  {w:"deserve",p:"/dɪˈzɜːv/",m:"v. 值得，应得",c:"deserve attention"},
  {w:"design",p:"/dɪˈzaɪn/",m:"v./n. 设计",c:"graphic design"},
  {w:"desirable",p:"/dɪˈzaɪərəbl/",m:"adj. 可取的，理想的",c:"highly desirable"},
  {w:"desperate",p:"/ˈdespərət/",m:"adj. 绝望的，不顾一切的",c:"desperate situation"},
  {w:"despite",p:"/dɪˈspaɪt/",m:"prep. 尽管",c:"despite the fact"},
  {w:"destination",p:"/ˌdestɪˈneɪʃn/",m:"n. 目的地",c:"tourist destination"},
  {w:"destruction",p:"/dɪˈstrʌkʃn/",m:"n. 破坏，毁灭",c:"environmental destruction"},
  {w:"detail",p:"/ˈdiːteɪl/",m:"n. 细节 v. 详述",c:"in detail"},
  {w:"detect",p:"/dɪˈtekt/",m:"v. 发现，探测",c:"detect changes"},
  {w:"determination",p:"/dɪˌtɜːmɪˈneɪʃn/",m:"n. 决心，决定",c:"show determination"},
  {w:"determine",p:"/dɪˈtɜːmɪn/",m:"v. 决定，确定",c:"determine to do"},
  {w:"develop",p:"/dɪˈveləp/",m:"v. 发展，开发",c:"develop skills"},
  {w:"device",p:"/dɪˈvaɪs/",m:"n. 设备，装置",c:"electronic device"},
  {w:"devote",p:"/dɪˈvəʊt/",m:"v. 致力于，奉献",c:"devote to"},
  {w:"dialect",p:"/ˈdaɪəlekt/",m:"n. 方言",c:"local dialect"},
  {w:"differ",p:"/ˈdɪfər/",m:"v. 不同，有区别",c:"differ from"},
  {w:"digest",p:"/daɪˈdʒest/",m:"v. 消化 n. 摘要",c:"digest food"},
  {w:"digital",p:"/ˈdɪdʒɪtl/",m:"adj. 数字的",c:"digital age"},
  {w:"dimension",p:"/daɪˈmenʃn/",m:"n. 尺寸，维度",c:"third dimension"},
  {w:"diplomatic",p:"/ˌdɪpləˈmætɪk/",m:"adj. 外交的",c:"diplomatic relations"},
  {w:"directly",p:"/dəˈrektli/",m:"adv. 直接地",c:"directly affect"},
  {w:"discipline",p:"/ˈdɪsəplɪn/",m:"n. 纪律，学科",c:"self-discipline"},
  {w:"discount",p:"/ˈdɪskaʊnt/",m:"n. 折扣",c:"at a discount"},
  {w:"disorder",p:"/dɪsˈɔːdər/",m:"n. 混乱，失调",c:"mental disorder"},
  {w:"display",p:"/dɪˈspleɪ/",m:"v./n. 展示，显示",c:"on display"},
  {w:"dispose",p:"/dɪˈspəʊz/",m:"v. 处理，处置",c:"dispose of"},
  {w:"dispute",p:"/dɪˈspjuːt/",m:"n./v. 争论，纠纷",c:"labor dispute"},
  {w:"dissolve",p:"/dɪˈzɒlv/",m:"v. 溶解，解散",c:"dissolve in water"},
  {w:"distinct",p:"/dɪˈstɪŋkt/",m:"adj. 不同的，明显的",c:"distinct from"},
  {w:"distinction",p:"/dɪˈstɪŋkʃn/",m:"n. 区别，差别",c:"make a distinction"},
  {w:"distinguish",p:"/dɪˈstɪŋɡwɪʃ/",m:"v. 区分，辨别",c:"distinguish between"},
  {w:"distribute",p:"/dɪˈstrɪbjuːt/",m:"v. 分发，分配",c:"distribute to"},
  {w:"distribution",p:"/ˌdɪstrɪˈbjuːʃn/",m:"n. 分配，分布",c:"distribution channel"},
  {w:"district",p:"/ˈdɪstrɪkt/",m:"n. 地区，区域",c:"business district"},
  {w:"diverse",p:"/daɪˈvɜːs/",m:"adj. 多样的，不同的",c:"culturally diverse"},
  {w:"division",p:"/dɪˈvɪʒn/",m:"n. 划分，部门",c:"division of labor"},
  {w:"document",p:"/ˈdɒkjumənt/",m:"n. 文件，文档",c:"official document"},
  {w:"domestic",p:"/dəˈmestɪk/",m:"adj. 国内的，家庭的",c:"domestic market"},
  {w:"dominant",p:"/ˈdɒmɪnənt/",m:"adj. 主导的，支配的",c:"dominant position"},
  {w:"donation",p:"/dəʊˈneɪʃn/",m:"n. 捐赠",c:"make a donation"},
  {w:"draft",p:"/drɑːft/",m:"n. 草稿 v. 起草",c:"first draft"},
  {w:"dramatic",p:"/drəˈmætɪk/",m:"adj. 戏剧性的，显著的",c:"dramatic change"},
  {w:"drift",p:"/drɪft/",m:"v./n. 漂流，偏移",c:"drift apart"},
  {w:"duration",p:"/djuˈreɪʃn/",m:"n. 持续时间",c:"for the duration"},
  {w:"dynamic",p:"/daɪˈnæmɪk/",m:"adj. 动态的，有活力的",c:"dynamic economy"},
  {w:"ease",p:"/iːz/",m:"n. 容易 v. 减轻",c:"with ease"},
  {w:"echo",p:"/ˈekəʊ/",m:"n. 回声 v. 附和",c:"echo chamber"},
  {w:"economic",p:"/ˌiːkəˈnɒmɪk/",m:"adj. 经济的",c:"economic growth"},
  {w:"economical",p:"/ˌiːkəˈnɒmɪkl/",m:"adj. 经济的，节约的",c:"economical car"},
  {w:"economy",p:"/ɪˈkɒnəmi/",m:"n. 经济",c:"global economy"},
  {w:"edition",p:"/ɪˈdɪʃn/",m:"n. 版本",c:"special edition"},
  {w:"editor",p:"/ˈedɪtər/",m:"n. 编辑",c:"chief editor"},
  {w:"educate",p:"/ˈedʒukeɪt/",m:"v. 教育",c:"educate children"},
  {w:"effective",p:"/ɪˈfektɪv/",m:"adj. 有效的",c:"effective method"},
  {w:"efficiency",p:"/ɪˈfɪʃnsi/",m:"n. 效率",c:"improve efficiency"},
  {w:"efficient",p:"/ɪˈfɪʃnt/",m:"adj. 高效的",c:"energy efficient"},
  {w:"elaborate",p:"/ɪˈlæbərət/",m:"adj. 精心的 v. 详细阐述",c:"elaborate on"},
  {w:"election",p:"/ɪˈlekʃn/",m:"n. 选举",c:"general election"},
  {w:"electronic",p:"/ɪˌlekˈtrɒnɪk/",m:"adj. 电子的",c:"electronic device"},
  {w:"element",p:"/ˈelɪmənt/",m:"n. 元素，要素",c:"key element"},
  {w:"elementary",p:"/ˌelɪˈmentri/",m:"adj. 基本的，初级的",c:"elementary school"},
  {w:"eliminate",p:"/ɪˈlɪmɪneɪt/",m:"v. 消除，淘汰",c:"eliminate poverty"},
  {w:"elsewhere",p:"/ˌelsˈweər/",m:"adv. 在别处",c:"look elsewhere"},
  {w:"embrace",p:"/ɪmˈbreɪs/",m:"v. 拥抱，接受",c:"embrace change"},
  {w:"emerge",p:"/ɪˈmɜːdʒ/",m:"v. 出现，浮现",c:"emerge as"},
  {w:"emergency",p:"/ɪˈmɜːdʒənsi/",m:"n. 紧急情况",c:"emergency room"},
  {w:"emission",p:"/ɪˈmɪʃn/",m:"n. 排放，散发",c:"carbon emission"},
  {w:"emotion",p:"/ɪˈməʊʃn/",m:"n. 情感，情绪",c:"express emotion"},
  {w:"emotional",p:"/ɪˈməʊʃənl/",m:"adj. 情感的",c:"emotional support"},
  {w:"emphasis",p:"/ˈemfəsɪs/",m:"n. 强调，重点",c:"put emphasis on"},
  {w:"emphasize",p:"/ˈemfəsaɪz/",m:"v. 强调",c:"emphasize the importance"},
  {w:"employ",p:"/ɪmˈplɔɪ/",m:"v. 雇用，使用",c:"employ workers"},
  {w:"employee",p:"/ɪmˈplɔɪiː/",m:"n. 雇员",c:"employee benefits"},
  {w:"employer",p:"/ɪmˈplɔɪər/",m:"n. 雇主",c:"employer brand"},
  {w:"employment",p:"/ɪmˈplɔɪmənt/",m:"n. 就业，雇用",c:"full employment"},
  {w:"enable",p:"/ɪˈneɪbl/",m:"v. 使能够",c:"enable to do"},
  {w:"encounter",p:"/ɪnˈkaʊntər/",m:"v./n. 遭遇，遇到",c:"encounter problems"},
  {w:"encourage",p:"/ɪnˈkʌrɪdʒ/",m:"v. 鼓励",c:"encourage participation"},
  {w:"engage",p:"/ɪnˈɡeɪdʒ/",m:"v. 从事，吸引",c:"engage in"},
  {w:"engine",p:"/ˈendʒɪn/",m:"n. 引擎，发动机",c:"search engine"},
  {w:"engineering",p:"/ˌendʒɪˈnɪərɪŋ/",m:"n. 工程学",c:"software engineering"},
  {w:"enhance",p:"/ɪnˈhɑːns/",m:"v. 提高，增强",c:"enhance performance"},
  {w:"enormous",p:"/ɪˈnɔːməs/",m:"adj. 巨大的",c:"enormous potential"},
  {w:"ensure",p:"/ɪnˈʃʊər/",m:"v. 确保，保证",c:"ensure safety"},
  {w:"enterprise",p:"/ˈentəpraɪz/",m:"n. 企业，事业",c:"private enterprise"},
  {w:"entertain",p:"/ˌentəˈteɪn/",m:"v. 娱乐，招待",c:"entertain guests"},
  {w:"enthusiasm",p:"/ɪnˈθjuːziæzəm/",m:"n. 热情，热心",c:"show enthusiasm"},
  {w:"entitle",p:"/ɪnˈtaɪtl/",m:"v. 给…权利，题为",c:"be entitled to"},
  {w:"equip",p:"/ɪˈkwɪp/",m:"v. 装备，配备",c:"equip with"},
  {w:"equipment",p:"/ɪˈkwɪpmənt/",m:"n. 设备，装备",c:"office equipment"},
  {w:"equivalent",p:"/ɪˈkwɪvələnt/",m:"adj. 等价的 n. 等同物",c:"equivalent to"},
  {w:"error",p:"/ˈerər/",m:"n. 错误，差错",c:"human error"},
  {w:"essential",p:"/ɪˈsenʃl/",m:"adj. 必要的，本质的",c:"essential role"},
  {w:"establish",p:"/ɪˈstæblɪʃ/",m:"v. 建立，设立",c:"establish contact"},
  {w:"estate",p:"/ɪˈsteɪt/",m:"n. 财产，房地产",c:"real estate"},
  {w:"estimate",p:"/ˈestɪmeɪt/",m:"v./n. 估计",c:"rough estimate"},
  {w:"evaluate",p:"/ɪˈvæljueɪt/",m:"v. 评估",c:"evaluate performance"},
  {w:"eventually",p:"/ɪˈventʃuəli/",m:"adv. 最终",c:"eventually lead to"},
  {w:"evidence",p:"/ˈevɪdəns/",m:"n. 证据",c:"scientific evidence"},
  {w:"evident",p:"/ˈevɪdənt/",m:"adj. 明显的",c:"self-evident"},
  {w:"evil",p:"/ˈiːvl/",m:"adj. 邪恶的 n. 罪恶",c:"good and evil"},
  {w:"evolution",p:"/ˌiːvəˈluːʃn/",m:"n. 进化，演变",c:"human evolution"},
  {w:"evolve",p:"/ɪˈvɒlv/",m:"v. 进化，发展",c:"evolve into"},
  {w:"exaggerate",p:"/ɪɡˈzædʒəreɪt/",m:"v. 夸大",c:"tend to exaggerate"},
  {w:"examine",p:"/ɪɡˈzæmɪn/",m:"v. 检查，考试",c:"examine carefully"},
  {w:"exceed",p:"/ɪkˈsiːd/",m:"v. 超过，超越",c:"exceed expectations"},
  {w:"exception",p:"/ɪkˈsepʃn/",m:"n. 例外",c:"without exception"},
  {w:"excessive",p:"/ɪkˈsesɪv/",m:"adj. 过度的",c:"excessive use"},
  {w:"exchange",p:"/ɪksˈtʃeɪndʒ/",m:"v./n. 交换，兑换",c:"exchange rate"},
  {w:"exclude",p:"/ɪkˈskluːd/",m:"v. 排除",c:"exclude from"},
  {w:"exclusive",p:"/ɪkˈskluːsɪv/",m:"adj. 独有的，排他的",c:"exclusive rights"},
  {w:"excursion",p:"/ɪkˈskɜːʃn/",m:"n. 远足，短途旅行",c:"go on an excursion"},
  {w:"execute",p:"/ˈeksɪkjuːt/",m:"v. 执行，处决",c:"execute a plan"},
  {w:"executive",p:"/ɪɡˈzekjətɪv/",m:"n. 主管 adj. 执行的",c:"chief executive"},
  {w:"exercise",p:"/ˈeksəsaɪz/",m:"n./v. 锻炼，行使",c:"physical exercise"},
  {w:"exhibit",p:"/ɪɡˈzɪbɪt/",m:"v. 展示 n. 展览",c:"exhibit behavior"},
  {w:"existence",p:"/ɪɡˈzɪstəns/",m:"n. 存在",c:"in existence"},
  {w:"expand",p:"/ɪkˈspænd/",m:"v. 扩张，扩大",c:"expand business"},
  {w:"expansion",p:"/ɪkˈspænʃn/",m:"n. 扩张，扩展",c:"business expansion"},
  {w:"expectation",p:"/ˌekspekˈteɪʃn/",m:"n. 期望，预期",c:"meet expectations"},
  {w:"expense",p:"/ɪkˈspens/",m:"n. 费用，花费",c:"at the expense of"},
  {w:"experimental",p:"/ɪkˌsperɪˈmentl/",m:"adj. 实验的",c:"experimental data"},
  {w:"expert",p:"/ˈekspɜːt/",m:"n. 专家 adj. 熟练的",c:"subject expert"},
  {w:"explanation",p:"/ˌekspləˈneɪʃn/",m:"n. 解释",c:"give an explanation"},
  {w:"explicit",p:"/ɪkˈsplɪsɪt/",m:"adj. 明确的，直言的",c:"explicit instructions"},
  {w:"exploit",p:"/ɪkˈsplɔɪt/",m:"v. 开发，剥削",c:"exploit resources"},
  {w:"explore",p:"/ɪkˈsplɔːr/",m:"v. 探索，探究",c:"explore options"},
  {w:"explosion",p:"/ɪkˈspləʊʒn/",m:"n. 爆炸，激增",c:"population explosion"},
  {w:"export",p:"/ɪkˈspɔːt/",m:"v./n. 出口",c:"export goods"},
  {w:"expose",p:"/ɪkˈspəʊz/",m:"v. 暴露，揭露",c:"expose to"},
  {w:"exposure",p:"/ɪkˈspəʊʒər/",m:"n. 暴露，曝光",c:"sun exposure"},
  {w:"extend",p:"/ɪkˈstend/",m:"v. 延伸，扩展",c:"extend deadline"},
  {w:"extension",p:"/ɪkˈstenʃn/",m:"n. 延长，扩展",c:"extension cord"},
  {w:"extensive",p:"/ɪkˈstensɪv/",m:"adj. 广泛的，大量的",c:"extensive research"},
  {w:"extent",p:"/ɪkˈstent/",m:"n. 程度，范围",c:"to some extent"},
  {w:"external",p:"/ɪkˈstɜːnl/",m:"adj. 外部的",c:"external factors"},
  {w:"extraordinary",p:"/ɪkˈstrɔːdnri/",m:"adj. 非凡的",c:"extraordinary achievement"},
  {w:"extreme",p:"/ɪkˈstriːm/",m:"adj. 极端的 n. 极端",c:"extreme weather"},
  {w:"facilitate",p:"/fəˈsɪlɪteɪt/",m:"v. 促进，使便利",c:"facilitate communication"},
  {w:"facility",p:"/fəˈsɪləti/",m:"n. 设施，设备",c:"sports facility"},
  {w:"factor",p:"/ˈfæktər/",m:"n. 因素",c:"key factor"},
  {w:"faculty",p:"/ˈfæklti/",m:"n. 能力，全体教员",c:"mental faculty"},
  {w:"faith",p:"/feɪθ/",m:"n. 信念，信仰",c:"have faith in"},
  {w:"faithful",p:"/ˈfeɪθfl/",m:"adj. 忠实的",c:"faithful friend"},
  {w:"fame",p:"/feɪm/",m:"n. 名声，声誉",c:"rise to fame"},
  {w:"famine",p:"/ˈfæmɪn/",m:"n. 饥荒",c:"famine relief"},
  {w:"fascinating",p:"/ˈfæsɪneɪtɪŋ/",m:"adj. 迷人的",c:"fascinating story"},
  {w:"fashion",p:"/ˈfæʃn/",m:"n. 时尚，方式",c:"in fashion"},
  {w:"fatal",p:"/ˈfeɪtl/",m:"adj. 致命的",c:"fatal accident"},
  {w:"fault",p:"/fɔːlt/",m:"n. 缺点，过错",c:"find fault with"},
  {w:"favourable",p:"/ˈfeɪvərəbl/",m:"adj. 有利的，赞成的",c:"favourable conditions"},
  {w:"feasible",p:"/ˈfiːzəbl/",m:"adj. 可行的",c:"feasible solution"},
  {w:"feature",p:"/ˈfiːtʃər/",m:"n. 特点 v. 以…为特色",c:"key feature"},
  {w:"federal",p:"/ˈfedərəl/",m:"adj. 联邦的",c:"federal government"},
  {w:"feedback",p:"/ˈfiːdbæk/",m:"n. 反馈",c:"positive feedback"},
  {w:"fertile",p:"/ˈfɜːtaɪl/",m:"adj. 肥沃的，富饶的",c:"fertile land"},
  {w:"fiction",p:"/ˈfɪkʃn/",m:"n. 小说，虚构",c:"science fiction"},
  {w:"fierce",p:"/fɪəs/",m:"adj. 激烈的，凶猛的",c:"fierce competition"},
  {w:"figure",p:"/ˈfɪɡər/",m:"n. 数字，人物 v. 认为",c:"public figure"},
  {w:"finance",p:"/ˈfaɪnæns/",m:"n. 财政，金融",c:"personal finance"},
  {w:"financial",p:"/faɪˈnænʃl/",m:"adj. 金融的，财政的",c:"financial crisis"},
  {w:"flame",p:"/fleɪm/",m:"n. 火焰",c:"burst into flames"},
  {w:"flexible",p:"/ˈfleksəbl/",m:"adj. 灵活的",c:"flexible schedule"},
  {w:"flourish",p:"/ˈflʌrɪʃ/",m:"v. 繁荣，兴旺",c:"flourish in"},
  {w:"forbid",p:"/fəˈbɪd/",m:"v. 禁止",c:"strictly forbid"},
  {w:"forecast",p:"/ˈfɔːkɑːst/",m:"n./v. 预测，预报",c:"weather forecast"},
  {w:"foreign",p:"/ˈfɒrən/",m:"adj. 外国的",c:"foreign language"},
  {w:"formal",p:"/ˈfɔːml/",m:"adj. 正式的",c:"formal education"},
  {w:"format",p:"/ˈfɔːmæt/",m:"n. 格式，版式",c:"file format"},
  {w:"formula",p:"/ˈfɔːmjələ/",m:"n. 公式，配方",c:"mathematical formula"},
  {w:"fortune",p:"/ˈfɔːtʃuːn/",m:"n. 命运，财富",c:"make a fortune"},
  {w:"foundation",p:"/faʊnˈdeɪʃn/",m:"n. 基础，基金会",c:"solid foundation"},
  {w:"fraction",p:"/ˈfrækʃn/",m:"n. 分数，小部分",c:"a fraction of"},
  {w:"framework",p:"/ˈfreɪmwɜːk/",m:"n. 框架，结构",c:"legal framework"},
  {w:"frequency",p:"/ˈfriːkwənsi/",m:"n. 频率",c:"high frequency"},
  {w:"frontier",p:"/ˈfrʌntɪər/",m:"n. 边境，前沿",c:"new frontier"},
  {w:"fulfil(l)",p:"/fʊlˈfɪl/",m:"v. 实现，满足",c:"fulfill a dream"},
  {w:"function",p:"/ˈfʌŋkʃn/",m:"n. 功能 v. 运行",c:"basic function"},
  {w:"fund",p:"/fʌnd/",m:"n. 基金 v. 资助",c:"raise funds"},
  {w:"fundamental",p:"/ˌfʌndəˈmentl/",m:"adj. 基本的 n. 原理",c:"fundamental change"},
  {w:"furthermore",p:"/ˌfɜːðəˈmɔːr/",m:"adv. 此外，而且",c:"and furthermore"},
  {w:"gain",p:"/ɡeɪn/",m:"v. 获得 n. 收益",c:"gain experience"},
  {w:"gap",p:"/ɡæp/",m:"n. 缺口，差距",c:"generation gap"},
  {w:"gaze",p:"/ɡeɪz/",m:"v./n. 凝视",c:"gaze at"},
  {w:"gender",p:"/ˈdʒendər/",m:"n. 性别",c:"gender equality"},
  {w:"gene",p:"/dʒiːn/",m:"n. 基因",c:"gene therapy"},
  {w:"generate",p:"/ˈdʒenəreɪt/",m:"v. 产生，生成",c:"generate income"},
  {w:"generous",p:"/ˈdʒenərəs/",m:"adj. 慷慨的，丰富的",c:"generous donation"},
  {w:"genius",p:"/ˈdʒiːniəs/",m:"n. 天才",c:"stroke of genius"},
  {w:"genuine",p:"/ˈdʒenjuɪn/",m:"adj. 真正的，真诚的",c:"genuine interest"},
  {w:"gesture",p:"/ˈdʒestʃər/",m:"n. 手势，姿态",c:"kind gesture"},
  {w:"global",p:"/ˈɡləʊbl/",m:"adj. 全球的",c:"global warming"},
  {w:"globe",p:"/ɡləʊb/",m:"n. 地球，球体",c:"across the globe"},
  {w:"gradual",p:"/ˈɡrædʒuəl/",m:"adj. 逐渐的",c:"gradual process"},
  {w:"grant",p:"/ɡrɑːnt/",m:"v. 授予 n. 拨款",c:"take for granted"},
  {w:"grasp",p:"/ɡrɑːsp/",m:"v./n. 抓住，理解",c:"grasp the concept"},
  {w:"grateful",p:"/ˈɡreɪtfl/",m:"adj. 感激的",c:"be grateful for"},
  {w:"guarantee",p:"/ˌɡærənˈtiː/",m:"v./n. 保证，担保",c:"guarantee quality"},
  {w:"guard",p:"/ɡɑːd/",m:"v. 守卫 n. 警卫",c:"guard against"},
  {w:"guidance",p:"/ˈɡaɪdns/",m:"n. 指导，引导",c:"career guidance"},
  {w:"guideline",p:"/ˈɡaɪdlaɪn/",m:"n. 指导方针",c:"follow guidelines"},
  {w:"guilty",p:"/ˈɡɪlti/",m:"adj. 有罪的，内疚的",c:"feel guilty"},
  {w:"habitat",p:"/ˈhæbɪtæt/",m:"n. 栖息地",c:"natural habitat"},
  {w:"halt",p:"/hɔːlt/",m:"v./n. 停止",c:"come to a halt"},
  {w:"handle",p:"/ˈhændl/",m:"v. 处理 n. 把手",c:"handle pressure"},
  {w:"handy",p:"/ˈhændi/",m:"adj. 方便的，手边的",c:"come in handy"},
  {w:"harsh",p:"/hɑːʃ/",m:"adj. 严酷的，刺耳的",c:"harsh conditions"},
  {w:"hazard",p:"/ˈhæzəd/",m:"n. 危险，危害",c:"health hazard"},
  {w:"headline",p:"/ˈhedlaɪn/",m:"n. 标题，头条",c:"news headline"},
  {w:"hence",p:"/hens/",m:"adv. 因此，从此",c:"and hence"},
  {w:"heritage",p:"/ˈherɪtɪdʒ/",m:"n. 遗产，传统",c:"cultural heritage"},
  {w:"highlight",p:"/ˈhaɪlaɪt/",m:"v. 强调，突出",c:"highlight the importance"},
  {w:"horizon",p:"/həˈraɪzn/",m:"n. 地平线，眼界",c:"broaden horizon"},
  {w:"horror",p:"/ˈhɒrər/",m:"n. 恐怖，厌恶",c:"horror movie"},
  {w:"hostile",p:"/ˈhɒstaɪl/",m:"adj. 敌对的",c:"hostile environment"},
  {w:"household",p:"/ˈhaʊshəʊld/",m:"n. 家庭 adj. 家用的",c:"household chores"},
  {w:"humble",p:"/ˈhʌmbl/",m:"adj. 谦逊的，卑微的",c:"humble beginnings"},
  {w:"humo(u)r",p:"/ˈhjuːmər/",m:"n. 幽默",c:"sense of humor"},
  {w:"ideal",p:"/aɪˈdiːəl/",m:"adj. 理想的 n. 理想",c:"ideal solution"},
  {w:"identical",p:"/aɪˈdentɪkl/",m:"adj. 相同的",c:"identical to"},
  {w:"identify",p:"/aɪˈdentɪfaɪ/",m:"v. 识别，确认",c:"identify with"},
  {w:"identity",p:"/aɪˈdentəti/",m:"n. 身份，认同",c:"cultural identity"},
  {w:"ignorance",p:"/ˈɪɡnərəns/",m:"n. 无知",c:"ignorance of law"},
  {w:"illegal",p:"/ɪˈliːɡl/",m:"adj. 非法的",c:"illegal activities"},
  {w:"illustrate",p:"/ˈɪləstreɪt/",m:"v. 说明，阐明",c:"illustrate a point"},
  {w:"image",p:"/ˈɪmɪdʒ/",m:"n. 形象，图像",c:"public image"},
  {w:"imagination",p:"/ɪˌmædʒɪˈneɪʃn/",m:"n. 想象力",c:"beyond imagination"},
  {w:"immediate",p:"/ɪˈmiːdiət/",m:"adj. 立即的，直接的",c:"immediate action"},
  {w:"immigrant",p:"/ˈɪmɪɡrənt/",m:"n. 移民",c:"illegal immigrant"},
  {w:"impact",p:"/ˈɪmpækt/",m:"n./v. 影响，冲击",c:"significant impact"},
  {w:"implement",p:"/ˈɪmplɪment/",m:"v. 实施 n. 工具",c:"implement a plan"},
  {w:"implication",p:"/ˌɪmplɪˈkeɪʃn/",m:"n. 含义，暗示",c:"have implications for"},
  {w:"impose",p:"/ɪmˈpəʊz/",m:"v. 强加，征税",c:"impose restrictions"},
  {w:"impress",p:"/ɪmˈpres/",m:"v. 给…留下印象",c:"impress upon"},
  {w:"impression",p:"/ɪmˈpreʃn/",m:"n. 印象",c:"first impression"},
  {w:"impressive",p:"/ɪmˈpresɪv/",m:"adj. 令人印象深刻的",c:"impressive performance"},
  {w:"incident",p:"/ˈɪnsɪdənt/",m:"n. 事件，事故",c:"isolated incident"},
  {w:"incline",p:"/ɪnˈklaɪn/",m:"v. 倾向，倾斜",c:"be inclined to"},
  {w:"income",p:"/ˈɪnkʌm/",m:"n. 收入",c:"annual income"},
  {w:"increasingly",p:"/ɪnˈkriːsɪŋli/",m:"adv. 日益，越来越",c:"increasingly popular"},
  {w:"incredible",p:"/ɪnˈkredəbl/",m:"adj. 难以置信的",c:"incredible story"},
  {w:"independence",p:"/ˌɪndɪˈpendəns/",m:"n. 独立，自主",c:"gain independence"},
  {w:"index",p:"/ˈɪndeks/",m:"n. 索引，指数",c:"stock index"},
  {w:"indicate",p:"/ˈɪndɪkeɪt/",m:"v. 表明，指示",c:"indicate that"},
  {w:"individual",p:"/ˌɪndɪˈvɪdʒuəl/",m:"adj. 个人的 n. 个人",c:"individual needs"},
  {w:"industrial",p:"/ɪnˈdʌstriəl/",m:"adj. 工业的",c:"industrial revolution"},
  {w:"inevitable",p:"/ɪnˈevɪtəbl/",m:"adj. 不可避免的",c:"inevitable consequence"},
  {w:"infant",p:"/ˈɪnfənt/",m:"n. 婴儿 adj. 婴儿的",c:"infant mortality"},
  {w:"inflation",p:"/ɪnˈfleɪʃn/",m:"n. 通货膨胀",c:"inflation rate"},
  {w:"influence",p:"/ˈɪnfluəns/",m:"n./v. 影响",c:"under the influence"},
  {w:"inform",p:"/ɪnˈfɔːm/",m:"v. 通知，告知",c:"inform someone"},
  {w:"initial",p:"/ɪˈnɪʃl/",m:"adj. 最初的 n. 首字母",c:"initial stage"},
  {w:"initiative",p:"/ɪˈnɪʃətɪv/",m:"n. 主动性，倡议",c:"take the initiative"},
  {w:"injure",p:"/ˈɪndʒər/",m:"v. 伤害，损害",c:"injure seriously"},
  {w:"injury",p:"/ˈɪndʒəri/",m:"n. 伤害，损伤",c:"serious injury"},
  {w:"inner",p:"/ˈɪnər/",m:"adj. 内部的，内心的",c:"inner peace"},
  {w:"innocent",p:"/ˈɪnəsnt/",m:"adj. 无辜的，天真的",c:"innocent people"},
  {w:"innovation",p:"/ˌɪnəˈveɪʃn/",m:"n. 创新",c:"technological innovation"},
  {w:"input",p:"/ˈɪnpʊt/",m:"n./v. 输入",c:"input data"},
  {w:"inquiry",p:"/ɪnˈkwaɪəri/",m:"n. 询问，调查",c:"make an inquiry"},
  {w:"insight",p:"/ˈɪnsaɪt/",m:"n. 洞察力，见解",c:"valuable insight"},
  {w:"inspect",p:"/ɪnˈspekt/",m:"v. 检查，视察",c:"inspect carefully"},
  {w:"install",p:"/ɪnˈstɔːl/",m:"v. 安装",c:"install software"},
  {w:"instance",p:"/ˈɪnstəns/",m:"n. 例子，实例",c:"for instance"},
  {w:"institute",p:"/ˈɪnstɪtjuːt/",m:"n. 机构 v. 建立",c:"research institute"},
  {w:"institution",p:"/ˌɪnstɪˈtjuːʃn/",m:"n. 机构，制度",c:"financial institution"},
  {w:"instruct",p:"/ɪnˈstrʌkt/",m:"v. 指示，教授",c:"instruct to do"},
  {w:"instrument",p:"/ˈɪnstrəmənt/",m:"n. 乐器，工具",c:"musical instrument"},
  {w:"insurance",p:"/ɪnˈʃʊərəns/",m:"n. 保险",c:"health insurance"},
  {w:"intellectual",p:"/ˌɪntəˈlektʃuəl/",m:"adj. 智力的 n. 知识分子",c:"intellectual property"},
  {w:"intelligence",p:"/ɪnˈtelɪdʒəns/",m:"n. 智力，情报",c:"artificial intelligence"},
  {w:"intelligent",p:"/ɪnˈtelɪdʒənt/",m:"adj. 聪明的",c:"intelligent system"},
  {w:"intense",p:"/ɪnˈtens/",m:"adj. 强烈的，紧张的",c:"intense competition"},
  {w:"intention",p:"/ɪnˈtenʃn/",m:"n. 意图，目的",c:"good intention"},
  {w:"interact",p:"/ˌɪntərˈækt/",m:"v. 互动，相互作用",c:"interact with"},
  {w:"interaction",p:"/ˌɪntərˈækʃn/",m:"n. 互动",c:"social interaction"},
  {w:"interpret",p:"/ɪnˈtɜːprɪt/",m:"v. 解释，口译",c:"interpret as"},
  {w:"interval",p:"/ˈɪntəvl/",m:"n. 间隔，间歇",c:"at regular intervals"},
  {w:"invest",p:"/ɪnˈvest/",m:"v. 投资",c:"invest in"},
  {w:"investigate",p:"/ɪnˈvestɪɡeɪt/",m:"v. 调查",c:"investigate the case"},
  {w:"investment",p:"/ɪnˈvestmənt/",m:"n. 投资",c:"return on investment"},
  {w:"invisible",p:"/ɪnˈvɪzəbl/",m:"adj. 看不见的",c:"invisible hand"},
  {w:"involve",p:"/ɪnˈvɒlv/",m:"v. 涉及，包含",c:"involve in"},
  {w:"isolate",p:"/ˈaɪsəleɪt/",m:"v. 隔离，孤立",c:"isolate from"},
  {w:"issue",p:"/ˈɪʃuː/",m:"n. 问题 v. 发行",c:"social issue"},
  {w:"item",p:"/ˈaɪtəm/",m:"n. 项目，物品",c:"line item"},
  {w:"joint",p:"/dʒɔɪnt/",m:"adj. 联合的 n. 关节",c:"joint effort"},
  {w:"journal",p:"/ˈdʒɜːnl/",m:"n. 期刊，日志",c:"academic journal"},
  {w:"judg(e)ment",p:"/ˈdʒʌdʒmənt/",m:"n. 判断，判决",c:"good judgment"},
  {w:"junior",p:"/ˈdʒuːniər/",m:"adj. 初级的 n. 年少者",c:"junior high"},
  {w:"justice",p:"/ˈdʒʌstɪs/",m:"n. 公正，司法",c:"social justice"},
  {w:"justify",p:"/ˈdʒʌstɪfaɪ/",m:"v. 证明…正当",c:"justify the cost"},
  {w:"keen",p:"/kiːn/",m:"adj. 热衷的，敏锐的",c:"be keen on"},
  {w:"label",p:"/ˈleɪbl/",m:"n. 标签 v. 标注",c:"warning label"},
  {w:"laboratory",p:"/ləˈbɒrətri/",m:"n. 实验室",c:"research laboratory"},
  {w:"landscape",p:"/ˈlændskeɪp/",m:"n. 风景，景观",c:"urban landscape"},
  {w:"largely",p:"/ˈlɑːdʒli/",m:"adv. 很大程度上",c:"largely due to"},
  {w:"launch",p:"/lɔːntʃ/",m:"v./n. 发射，启动",c:"launch a product"},
  {w:"layer",p:"/ˈleɪər/",m:"n. 层，层次",c:"ozone layer"},
  {w:"layout",p:"/ˈleɪaʊt/",m:"n. 布局，设计",c:"page layout"},
  {w:"leadership",p:"/ˈliːdəʃɪp/",m:"n. 领导能力",c:"under the leadership"},
  {w:"leading",p:"/ˈliːdɪŋ/",m:"adj. 主要的，领先的",c:"leading role"},
  {w:"league",p:"/liːɡ/",m:"n. 联盟",c:"league member"},
  {w:"leak",p:"/liːk/",m:"v./n. 泄漏",c:"leak information"},
  {w:"lean",p:"/liːn/",m:"v. 倾斜 adj. 瘦的",c:"lean against"},
  {w:"leap",p:"/liːp/",m:"v./n. 跳跃",c:"leap forward"},
  {w:"legal",p:"/ˈliːɡl/",m:"adj. 法律上的，合法的",c:"legal system"},
  {w:"legislation",p:"/ˌledʒɪsˈleɪʃn/",m:"n. 立法，法规",c:"pass legislation"},
  {w:"leisure",p:"/ˈleʒər/",m:"n. 闲暇，休闲",c:"leisure time"},
  {w:"lest",p:"/lest/",m:"conj. 唯恐，免得",c:"lest we forget"},
  {w:"liability",p:"/ˌlaɪəˈbɪləti/",m:"n. 责任，负债",c:"legal liability"},
  {w:"liberal",p:"/ˈlɪbərəl/",m:"adj. 自由的，开明的",c:"liberal arts"},
  {w:"liberty",p:"/ˈlɪbəti/",m:"n. 自由",c:"take the liberty"},
  {w:"license/licence",p:"/ˈlaɪsns/",m:"n. 许可证 v. 许可",c:"driver's license"},
  {w:"likewise",p:"/ˈlaɪkwaɪz/",m:"adv. 同样地",c:"do likewise"},
  {w:"limitation",p:"/ˌlɪmɪˈteɪʃn/",m:"n. 限制，局限",c:"statute of limitations"},
  {w:"linguistic",p:"/lɪŋˈɡwɪstɪk/",m:"adj. 语言的",c:"linguistic skills"},
  {w:"link",p:"/lɪŋk/",m:"n. 链接 v. 联系",c:"link to"},
  {w:"literary",p:"/ˈlɪtərəri/",m:"adj. 文学的",c:"literary works"},
  {w:"literature",p:"/ˈlɪtrətʃər/",m:"n. 文学，文献",c:"English literature"},
  {w:"loan",p:"/ləʊn/",m:"n. 贷款 v. 借出",c:"bank loan"},
  {w:"logic",p:"/ˈlɒdʒɪk/",m:"n. 逻辑",c:"logic thinking"},
  {w:"loyalty",p:"/ˈlɔɪəlti/",m:"n. 忠诚",c:"brand loyalty"},
  {w:"luxury",p:"/ˈlʌkʃəri/",m:"n. 奢侈，奢侈品",c:"luxury goods"},
  {w:"magnetic",p:"/mæɡˈnetɪk/",m:"adj. 磁的，有吸引力的",c:"magnetic field"},
  {w:"magnificent",p:"/mæɡˈnɪfɪsnt/",m:"adj. 壮丽的",c:"magnificent view"},
  {w:"maintain",p:"/meɪnˈteɪn/",m:"v. 维持，保养",c:"maintain order"},
  {w:"maintenance",p:"/ˈmeɪntənəns/",m:"n. 维护，保养",c:"routine maintenance"},
  {w:"manual",p:"/ˈmænjuəl/",m:"adj. 手工的 n. 手册",c:"user manual"},
  {w:"manufacture",p:"/ˌmænjuˈfæktʃər/",m:"v./n. 制造",c:"manufacture goods"},
  {w:"manufacturer",p:"/ˌmænjuˈfæktʃərər/",m:"n. 制造商",c:"car manufacturer"},
  {w:"margin",p:"/ˈmɑːdʒɪn/",m:"n. 边缘，利润",c:"profit margin"},
  {w:"massive",p:"/ˈmæsɪv/",m:"adj. 巨大的",c:"massive change"},
  {w:"master",p:"/ˈmɑːstər/",m:"n. 主人 v. 掌握",c:"master degree"},
  {w:"mate",p:"/meɪt/",m:"n. 伙伴，配偶",c:"soul mate"},
  {w:"mature",p:"/məˈtʃʊər/",m:"adj. 成熟的",c:"mature market"},
  {w:"maximum",p:"/ˈmæksɪməm/",m:"n. 最大(值) adj. 最大的",c:"maximum capacity"},
  {w:"mechanism",p:"/ˈmekənɪzəm/",m:"n. 机制，原理",c:"defense mechanism"},
  {w:"media",p:"/ˈmiːdiə/",m:"n. 媒体",c:"social media"},
  {w:"medium",p:"/ˈmiːdiəm/",m:"n. 媒介 adj. 中等的",c:"medium size"},
  {w:"mental",p:"/ˈmentl/",m:"adj. 心理的，精神的",c:"mental health"},
  {w:"mention",p:"/ˈmenʃn/",m:"v./n. 提及",c:"not to mention"},
  {w:"merchant",p:"/ˈmɜːtʃənt/",m:"n. 商人",c:"merchant ship"},
  {w:"mercy",p:"/ˈmɜːsi/",m:"n. 仁慈，怜悯",c:"at the mercy of"},
  {w:"merely",p:"/ˈmɪəli/",m:"adv. 仅仅，只不过",c:"merely because"},
  {w:"mild",p:"/maɪld/",m:"adj. 温和的，轻微的",c:"mild climate"},
  {w:"military",p:"/ˈmɪlətri/",m:"adj. 军事的 n. 军队",c:"military service"},
  {w:"minimum",p:"/ˈmɪnɪməm/",m:"n. 最小(值)",c:"minimum wage"},
  {w:"minister",p:"/ˈmɪnɪstər/",m:"n. 部长，大臣",c:"prime minister"},
  {w:"minor",p:"/ˈmaɪnər/",m:"adj. 较小的 n. 未成年人",c:"minor role"},
  {w:"minority",p:"/maɪˈnɒrəti/",m:"n. 少数，少数民族",c:"ethnic minority"},
  {w:"miracle",p:"/ˈmɪrəkl/",m:"n. 奇迹",c:"economic miracle"},
  {w:"miserable",p:"/ˈmɪzrəbl/",m:"adj. 悲惨的",c:"miserable life"},
  {w:"mission",p:"/ˈmɪʃn/",m:"n. 使命，任务",c:"carry out a mission"},
  {w:"mobile",p:"/ˈməʊbaɪl/",m:"adj. 移动的",c:"mobile phone"},
  {w:"moderate",p:"/ˈmɒdərət/",m:"adj. 适度的 v. 节制",c:"moderate exercise"},
  {w:"modify",p:"/ˈmɒdɪfaɪ/",m:"v. 修改，调整",c:"modify behavior"},
  {w:"monitor",p:"/ˈmɒnɪtər/",m:"v. 监控 n. 显示器",c:"monitor progress"},
  {w:"moral",p:"/ˈmɒrəl/",m:"adj. 道德的 n. 寓意",c:"moral value"},
  {w:"moreover",p:"/mɔːrˈəʊvər/",m:"adv. 此外，而且",c:"moreover important"},
  {w:"motion",p:"/ˈməʊʃn/",m:"n. 运动，动议",c:"in motion"},
  {w:"motivate",p:"/ˈməʊtɪveɪt/",m:"v. 激励，激发",c:"motivate employees"},
  {w:"motive",p:"/ˈməʊtɪv/",m:"n. 动机，目的",c:"motive for murder"},
  {w:"mount",p:"/maʊnt/",m:"v. 增加，登上",c:"mount pressure"},
  {w:"multiple",p:"/ˈmʌltɪpl/",m:"adj. 多重的 n. 倍数",c:"multiple times"},
  {w:"mutual",p:"/ˈmjuːtʃuəl/",m:"adj. 相互的，共同的",c:"mutual benefit"},
  {w:"narrative",p:"/ˈnærətɪv/",m:"n. 叙述 adj. 叙事的",c:"personal narrative"},
  {w:"narrow",p:"/ˈnærəʊ/",m:"adj. 狭窄的 v. 缩小",c:"narrow down"},
  {w:"nasty",p:"/ˈnɑːsti/",m:"adj. 令人厌恶的",c:"nasty surprise"},
  {w:"naval",p:"/ˈneɪvl/",m:"adj. 海军的",c:"naval base"},
  {w:"negotiate",p:"/nɪˈɡəʊʃieɪt/",m:"v. 谈判，协商",c:"negotiate with"},
  {w:"neighborhood",p:"/ˈneɪbəhʊd/",m:"n. 附近，邻里",c:"in the neighborhood"},
  {w:"nerve",p:"/nɜːv/",m:"n. 神经，勇气",c:"nerve system"},
  {w:"neutral",p:"/ˈnjuːtrəl/",m:"adj. 中立的，中性的",c:"neutral position"},
  {w:"nevertheless",p:"/ˌnevəðəˈles/",m:"adv. 然而，不过",c:"but nevertheless"},
  {w:"noble",p:"/ˈnəʊbl/",m:"adj. 高尚的，贵族的",c:"noble cause"},
  {w:"notion",p:"/ˈnəʊʃn/",m:"n. 概念，观念",c:"have no notion"},
  {w:"numerous",p:"/ˈnjuːmərəs/",m:"adj. 许多的",c:"numerous times"},
  {w:"objection",p:"/əbˈdʒekʃn/",m:"n. 反对，异议",c:"raise an objection"},
  {w:"objective",p:"/əbˈdʒektɪv/",m:"n. 目标 adj. 客观的",c:"achieve objective"},
  {w:"obligation",p:"/ˌɒblɪˈɡeɪʃn/",m:"n. 义务，责任",c:"legal obligation"},
  {w:"observation",p:"/ˌɒbzəˈveɪʃn/",m:"n. 观察，观测",c:"make an observation"},
  {w:"observe",p:"/əbˈzɜːv/",m:"v. 观察，遵守",c:"observe rules"},
  {w:"obstacle",p:"/ˈɒbstəkl/",m:"n. 障碍",c:"overcome obstacles"},
  {w:"obtain",p:"/əbˈteɪn/",m:"v. 获得，得到",c:"obtain information"},
  {w:"obvious",p:"/ˈɒbviəs/",m:"adj. 明显的",c:"obvious reason"},
  {w:"occasion",p:"/əˈkeɪʒn/",m:"n. 场合，时机",c:"on occasion"},
  {w:"occasional",p:"/əˈkeɪʒənl/",m:"adj. 偶然的",c:"occasional visit"},
  {w:"occupy",p:"/ˈɒkjupaɪ/",m:"v. 占据，使忙碌",c:"occupy time"},
  {w:"offense/offence",p:"/əˈfens/",m:"n. 冒犯，犯罪",c:"criminal offense"},
  {w:"offensive",p:"/əˈfensɪv/",m:"adj. 冒犯的，进攻的",c:"offensive remark"},
  {w:"official",p:"/əˈfɪʃl/",m:"adj. 官方的 n. 官员",c:"official language"},
  {w:"ongoing",p:"/ˈɒnɡəʊɪŋ/",m:"adj. 进行中的",c:"ongoing project"},
  {w:"operate",p:"/ˈɒpəreɪt/",m:"v. 操作，运转",c:"operate a machine"},
  {w:"operational",p:"/ˌɒpəˈreɪʃənl/",m:"adj. 运作的",c:"operational costs"},
  {w:"operator",p:"/ˈɒpəreɪtər/",m:"n. 操作员",c:"tour operator"},
  {w:"opponent",p:"/əˈpəʊnənt/",m:"n. 对手，反对者",c:"political opponent"},
  {w:"opportunity",p:"/ˌɒpəˈtjuːnəti/",m:"n. 机会",c:"seize the opportunity"},
  {w:"oppose",p:"/əˈpəʊz/",m:"v. 反对，对抗",c:"oppose the plan"},
  {w:"option",p:"/ˈɒpʃn/",m:"n. 选择，选项",c:"have no option"},
  {w:"organic",p:"/ɔːˈɡænɪk/",m:"adj. 有机的",c:"organic food"},
  {w:"organization",p:"/ˌɔːɡənaɪˈzeɪʃn/",m:"n. 组织，机构",c:"nonprofit organization"},
  {w:"organize",p:"/ˈɔːɡənaɪz/",m:"v. 组织，安排",c:"organize an event"},
  {w:"original",p:"/əˈrɪdʒənl/",m:"adj. 原来的，独创的",c:"original idea"},
  {w:"otherwise",p:"/ˈʌðəwaɪz/",m:"adv. 否则，不然",c:"or otherwise"},
  {w:"outcome",p:"/ˈaʊtkʌm/",m:"n. 结果，后果",c:"final outcome"},
  {w:"outdoor",p:"/ˈaʊtdɔːr/",m:"adj. 户外的",c:"outdoor activities"},
  {w:"outstanding",p:"/aʊtˈstændɪŋ/",m:"adj. 杰出的，未解决的",c:"outstanding achievement"},
  {w:"overall",p:"/ˌəʊvərˈɔːl/",m:"adj. 总体的 adv. 总体上",c:"overall performance"},
  {w:"overcome",p:"/ˌəʊvəˈkʌm/",m:"v. 克服，战胜",c:"overcome difficulties"},
  {w:"overlook",p:"/ˌəʊvəˈlʊk/",m:"v. 忽视，俯瞰",c:"overlook the fact"},
  {w:"overseas",p:"/ˌəʊvəˈsiːz/",m:"adv./adj. 海外(的)",c:"overseas market"},
  {w:"owe",p:"/əʊ/",m:"v. 欠，归功于",c:"owe to"},
  {w:"ownership",p:"/ˈəʊnəʃɪp/",m:"n. 所有权",c:"sense of ownership"},
  {w:"pace",p:"/peɪs/",m:"n. 速度，步伐",c:"keep pace with"},
  {w:"pack",p:"/pæk/",m:"v. 打包 n. 包",c:"pack up"},
  {w:"panel",p:"/ˈpænl/",m:"n. 面板，小组",c:"control panel"},
  {w:"parade",p:"/pəˈreɪd/",m:"n. 游行 v. 展示",c:"military parade"},
  {w:"paragraph",p:"/ˈpærəɡrɑːf/",m:"n. 段落",c:"opening paragraph"},
  {w:"parallel",p:"/ˈpærəlel/",m:"adj. 平行的 n. 相似",c:"in parallel"},
  {w:"parcel",p:"/ˈpɑːsl/",m:"n. 包裹",c:"parcel delivery"},
  {w:"partial",p:"/ˈpɑːʃl/",m:"adj. 部分的，偏袒的",c:"partial to"},
  {w:"participant",p:"/pɑːˈtɪsɪpənt/",m:"n. 参与者",c:"active participant"},
  {w:"participate",p:"/pɑːˈtɪsɪpeɪt/",m:"v. 参与",c:"participate in"},
  {w:"particular",p:"/pəˈtɪkjələr/",m:"adj. 特定的，挑剔的",c:"in particular"},
  {w:"passion",p:"/ˈpæʃn/",m:"n. 激情，热情",c:"passion for"},
  {w:"passive",p:"/ˈpæsɪv/",m:"adj. 被动的，消极的",c:"passive voice"},
  {w:"patent",p:"/ˈpætnt/",m:"n. 专利",c:"patent application"},
  {w:"pension",p:"/ˈpenʃn/",m:"n. 养老金，退休金",c:"pension fund"},
  {w:"perceive",p:"/pəˈsiːv/",m:"v. 感知，认为",c:"perceive as"},
  {w:"percentage",p:"/pəˈsentɪdʒ/",m:"n. 百分比",c:"small percentage"},
  {w:"permanent",p:"/ˈpɜːmənənt/",m:"adj. 永久的，固定的",c:"permanent resident"},
  {w:"permit",p:"/pəˈmɪt/",m:"v. 允许 n. 许可证",c:"permit to"},
  {w:"persist",p:"/pəˈsɪst/",m:"v. 坚持，持续",c:"persist in"},
  {w:"personality",p:"/ˌpɜːsəˈnæləti/",m:"n. 个性，人格",c:"strong personality"},
  {w:"perspective",p:"/pəˈspektɪv/",m:"n. 观点，视角",c:"from a perspective"},
  {w:"phenomenon",p:"/fɪˈnɒmɪnən/",m:"n. 现象",c:"natural phenomenon"},
  {w:"philosophy",p:"/fɪˈlɒsəfi/",m:"n. 哲学",c:"life philosophy"},
  {w:"physical",p:"/ˈfɪzɪkl/",m:"adj. 身体的，物理的",c:"physical exercise"},
  {w:"pioneer",p:"/ˌpaɪəˈnɪər/",m:"n. 先驱 v. 开拓",c:"pioneer spirit"},
  {w:"pledge",p:"/pledʒ/",m:"n./v. 保证，誓言",c:"take a pledge"},
  {w:"plus",p:"/plʌs/",m:"prep. 加 adj. 正的",c:"plus point"},
  {w:"poetry",p:"/ˈpəʊətri/",m:"n. 诗歌",c:"modern poetry"},
  {w:"poison",p:"/ˈpɔɪzn/",m:"n. 毒药 v. 毒害",c:"poison gas"},
  {w:"policy",p:"/ˈpɒləsi/",m:"n. 政策，策略",c:"foreign policy"},
  {w:"polish",p:"/ˈpəʊlɪʃ/",m:"v. 磨光，润色",c:"polish skills"},
  {w:"pollution",p:"/pəˈluːʃn/",m:"n. 污染",c:"air pollution"},
  {w:"portion",p:"/ˈpɔːʃn/",m:"n. 部分，一份",c:"a large portion"},
  {w:"portrait",p:"/ˈpɔːtreɪt/",m:"n. 肖像，描写",c:"family portrait"},
  {w:"pose",p:"/pəʊz/",m:"v. 造成，摆姿势",c:"pose a threat"},
  {w:"positive",p:"/ˈpɒzətɪv/",m:"adj. 积极的，正面的",c:"positive attitude"},
  {w:"possess",p:"/pəˈzes/",m:"v. 拥有，具有",c:"possess skills"},
  {w:"possession",p:"/pəˈzeʃn/",m:"n. 拥有，财产",c:"in possession of"},
  {w:"potential",p:"/pəˈtenʃl/",m:"adj. 潜在的 n. 潜力",c:"great potential"},
  {w:"poverty",p:"/ˈpɒvəti/",m:"n. 贫穷",c:"poverty line"},
  {w:"practically",p:"/ˈpræktɪkli/",m:"adv. 几乎，实际上",c:"practically impossible"},
  {w:"precaution",p:"/prɪˈkɔːʃn/",m:"n. 预防措施",c:"take precautions"},
  {w:"prediction",p:"/prɪˈdɪkʃn/",m:"n. 预测",c:"make a prediction"},
  {w:"preference",p:"/ˈprefrəns/",m:"n. 偏爱，优先",c:"personal preference"},
  {w:"prejudice",p:"/ˈpredʒədɪs/",m:"n. 偏见",c:"racial prejudice"},
  {w:"preparation",p:"/ˌprepəˈreɪʃn/",m:"n. 准备",c:"in preparation for"},
  {w:"prescribe",p:"/prɪˈskraɪb/",m:"v. 开(药)，规定",c:"prescribe medicine"},
  {w:"presence",p:"/ˈprezns/",m:"n. 出席，存在",c:"in the presence of"},
  {w:"presentation",p:"/ˌpreznˈteɪʃn/",m:"n. 展示，演示",c:"give a presentation"},
  {w:"preserve",p:"/prɪˈzɜːv/",m:"v. 保护，保存",c:"preserve history"},
  {w:"pressure",p:"/ˈpreʃər/",m:"n. 压力",c:"under pressure"},
  {w:"presumably",p:"/prɪˈzjuːməbli/",m:"adv. 大概，可能",c:"presumably correct"},
  {w:"prevail",p:"/prɪˈveɪl/",m:"v. 盛行，占优势",c:"prevail over"},
  {w:"previous",p:"/ˈpriːviəs/",m:"adj. 以前的",c:"previous experience"},
  {w:"pride",p:"/praɪd/",m:"n. 骄傲 v. 自豪",c:"take pride in"},
  {w:"primary",p:"/ˈpraɪməri/",m:"adj. 主要的，初级的",c:"primary school"},
  {w:"prime",p:"/praɪm/",m:"adj. 首要的 n. 全盛期",c:"prime minister"},
  {w:"principal",p:"/ˈprɪnsəpl/",m:"adj. 主要的 n. 校长",c:"principal reason"},
  {w:"principle",p:"/ˈprɪnsəpl/",m:"n. 原则，原理",c:"in principle"},
  {w:"prior",p:"/ˈpraɪər/",m:"adj. 先前的，优先的",c:"prior to"},
  {w:"priority",p:"/praɪˈɒrəti/",m:"n. 优先，重点",c:"top priority"},
  {w:"procedure",p:"/prəˈsiːdʒər/",m:"n. 程序，步骤",c:"standard procedure"},
  {w:"proceed",p:"/prəˈsiːd/",m:"v. 继续，进行",c:"proceed with"},
  {w:"process",p:"/ˈprəʊses/",m:"n. 过程 v. 处理",c:"in the process"},
  {w:"profession",p:"/prəˈfeʃn/",m:"n. 职业，专业",c:"medical profession"},
  {w:"professional",p:"/prəˈfeʃənl/",m:"adj. 专业的 n. 专业人员",c:"professional service"},
  {w:"profit",p:"/ˈprɒfɪt/",m:"n. 利润 v. 受益",c:"make a profit"},
  {w:"profound",p:"/prəˈfaʊnd/",m:"adj. 深刻的，深远的",c:"profound impact"},
  {w:"prohibit",p:"/prəˈhɪbɪt/",m:"v. 禁止",c:"strictly prohibit"},
  {w:"prominent",p:"/ˈprɒmɪnənt/",m:"adj. 突出的，著名的",c:"prominent figure"},
  {w:"promote",p:"/prəˈməʊt/",m:"v. 促进，提升",c:"promote growth"},
  {w:"promotion",p:"/prəˈməʊʃn/",m:"n. 晋升，推广",c:"sales promotion"},
  {w:"proof",p:"/pruːf/",m:"n. 证据，证明",c:"proof of identity"},
  {w:"property",p:"/ˈprɒpəti/",m:"n. 财产，特性",c:"intellectual property"},
  {w:"proportion",p:"/prəˈpɔːʃn/",m:"n. 比例，部分",c:"in proportion to"},
  {w:"proposal",p:"/prəˈpəʊzl/",m:"n. 提议，建议",c:"make a proposal"},
  {w:"propose",p:"/prəˈpəʊz/",m:"v. 提议，求婚",c:"propose a plan"},
  {w:"prospect",p:"/ˈprɒspekt/",m:"n. 前景，展望",c:"job prospects"},
  {w:"prosperity",p:"/prɒˈsperəti/",m:"n. 繁荣",c:"economic prosperity"},
  {w:"protest",p:"/ˈprəʊtest/",m:"n./v. 抗议",c:"protest against"},
  {w:"provision",p:"/prəˈvɪʒn/",m:"n. 供应，条款",c:"make provision for"},
  {w:"psychological",p:"/ˌsaɪkəˈlɒdʒɪkl/",m:"adj. 心理的",c:"psychological health"},
  {w:"publication",p:"/ˌpʌblɪˈkeɪʃn/",m:"n. 出版(物)",c:"scientific publication"},
  {w:"publish",p:"/ˈpʌblɪʃ/",m:"v. 出版，发表",c:"publish a book"},
  {w:"punctual",p:"/ˈpʌŋktʃuəl/",m:"adj. 准时的",c:"be punctual for"},
  {w:"purchase",p:"/ˈpɜːtʃəs/",m:"v./n. 购买",c:"purchase online"},
  {w:"pursue",p:"/pəˈsjuː/",m:"v. 追求，追赶",c:"pursue a dream"},
  {w:"qualification",p:"/ˌkwɒlɪfɪˈkeɪʃn/",m:"n. 资格，条件",c:"academic qualification"},
  {w:"quality",p:"/ˈkwɒləti/",m:"n. 质量 adj. 优质的",c:"high quality"},
  {w:"quantity",p:"/ˈkwɒntəti/",m:"n. 数量",c:"large quantity"},
  {w:"quote",p:"/kwəʊt/",m:"v./n. 引用，报价",c:"quote from"},
  {w:"racial",p:"/ˈreɪʃl/",m:"adj. 种族的",c:"racial discrimination"},
  {w:"radical",p:"/ˈrædɪkl/",m:"adj. 根本的，激进的",c:"radical change"},
  {w:"range",p:"/reɪndʒ/",m:"n. 范围 v. 变化",c:"wide range"},
  {w:"rank",p:"/ræŋk/",m:"n. 等级 v. 排列",c:"rank first"},
  {w:"rapid",p:"/ˈræpɪd/",m:"adj. 迅速的",c:"rapid growth"},
  {w:"rarely",p:"/ˈreəli/",m:"adv. 很少",c:"rarely seen"},
  {w:"rate",p:"/reɪt/",m:"n. 比率 v. 评价",c:"interest rate"},
  {w:"ratio",p:"/ˈreɪʃiəʊ/",m:"n. 比率，比例",c:"ratio of"},
  {w:"rational",p:"/ˈræʃnəl/",m:"adj. 理性的，合理的",c:"rational decision"},
  {w:"react",p:"/riˈækt/",m:"v. 反应",c:"react to"},
  {w:"readily",p:"/ˈredɪli/",m:"adv. 乐意地，容易地",c:"readily available"},
  {w:"realistic",p:"/ˌriːəˈlɪstɪk/",m:"adj. 现实的",c:"realistic goal"},
  {w:"reality",p:"/riˈæləti/",m:"n. 现实",c:"in reality"},
  {w:"reasonable",p:"/ˈriːznəbl/",m:"adj. 合理的，公道的",c:"reasonable price"},
  {w:"recall",p:"/rɪˈkɔːl/",m:"v./n. 回忆，召回",c:"recall the past"},
  {w:"reception",p:"/rɪˈsepʃn/",m:"n. 接待，接收",c:"wedding reception"},
  {w:"recession",p:"/rɪˈseʃn/",m:"n. 衰退",c:"economic recession"},
  {w:"recognition",p:"/ˌrekəɡˈnɪʃn/",m:"n. 认可，识别",c:"facial recognition"},
  {w:"recommend",p:"/ˌrekəˈmend/",m:"v. 推荐，建议",c:"highly recommend"},
  {w:"recommendation",p:"/ˌrekəmenˈdeɪʃn/",m:"n. 推荐(信)",c:"letter of recommendation"},
  {w:"recover",p:"/rɪˈkʌvər/",m:"v. 恢复，康复",c:"recover from"},
  {w:"recovery",p:"/rɪˈkʌvəri/",m:"n. 恢复，复苏",c:"economic recovery"},
  {w:"reduction",p:"/rɪˈdʌkʃn/",m:"n. 减少",c:"cost reduction"},
  {w:"refer",p:"/rɪˈfɜːr/",m:"v. 参考，提及",c:"refer to"},
  {w:"reference",p:"/ˈrefrəns/",m:"n. 参考，提及",c:"for reference"},
  {w:"reflect",p:"/rɪˈflekt/",m:"v. 反映，反射",c:"reflect on"},
  {w:"reform",p:"/rɪˈfɔːm/",m:"v./n. 改革",c:"economic reform"},
  {w:"regarding",p:"/rɪˈɡɑːdɪŋ/",m:"prep. 关于",c:"regarding this matter"},
  {w:"regardless",p:"/rɪˈɡɑːdləs/",m:"adv. 不管怎样",c:"regardless of"},
  {w:"region",p:"/ˈriːdʒən/",m:"n. 地区，区域",c:"in the region"},
  {w:"register",p:"/ˈredʒɪstər/",m:"v./n. 登记，注册",c:"register for"},
  {w:"regulate",p:"/ˈreɡjuleɪt/",m:"v. 管理，调节",c:"regulate temperature"},
  {w:"regulation",p:"/ˌreɡjuˈleɪʃn/",m:"n. 规则，法规",c:"government regulation"},
  {w:"reinforce",p:"/ˌriːɪnˈfɔːs/",m:"v. 加强，强化",c:"reinforce the idea"},
  {w:"reject",p:"/rɪˈdʒekt/",m:"v. 拒绝，排斥",c:"reject an offer"},
  {w:"relate",p:"/rɪˈleɪt/",m:"v. 联系，叙述",c:"relate to"},
  {w:"relax",p:"/rɪˈlæks/",m:"v. 放松",c:"relax and enjoy"},
  {w:"release",p:"/rɪˈliːs/",m:"v./n. 释放，发布",c:"press release"},
  {w:"relevant",p:"/ˈreləvənt/",m:"adj. 相关的",c:"relevant information"},
  {w:"reliable",p:"/rɪˈlaɪəbl/",m:"adj. 可靠的",c:"reliable source"},
  {w:"relief",p:"/rɪˈliːf/",m:"n. 减轻，救济",c:"pain relief"},
  {w:"religion",p:"/rɪˈlɪdʒən/",m:"n. 宗教",c:"freedom of religion"},
  {w:"rely",p:"/rɪˈlaɪ/",m:"v. 依赖，信赖",c:"rely on"},
  {w:"remark",p:"/rɪˈmɑːk/",m:"n./v. 评论，注意",c:"make a remark"},
  {w:"remarkable",p:"/rɪˈmɑːkəbl/",m:"adj. 显著的，非凡的",c:"remarkable achievement"},
  {w:"remedy",p:"/ˈremədi/",m:"n. 补救办法",c:"legal remedy"},
  {w:"remote",p:"/rɪˈməʊt/",m:"adj. 遥远的，远程的",c:"remote control"},
  {w:"render",p:"/ˈrendər/",m:"v. 使成为，提供",c:"render service"},
  {w:"renew",p:"/rɪˈnjuː/",m:"v. 更新，续期",c:"renew a contract"},
  {w:"replacement",p:"/rɪˈpleɪsmənt/",m:"n. 替代(品)",c:"find a replacement"},
  {w:"represent",p:"/ˌreprɪˈzent/",m:"v. 代表，表示",c:"represent interests"},
  {w:"representative",p:"/ˌreprɪˈzentətɪv/",m:"n. 代表 adj. 典型的",c:"sales representative"},
  {w:"reputation",p:"/ˌrepjuˈteɪʃn/",m:"n. 声誉",c:"good reputation"},
  {w:"request",p:"/rɪˈkwest/",m:"n./v. 请求，要求",c:"make a request"},
  {w:"require",p:"/rɪˈkwaɪər/",m:"v. 需要，要求",c:"require attention"},
  {w:"requirement",p:"/rɪˈkwaɪəmənt/",m:"n. 要求，必要条件",c:"meet requirements"},
  {w:"rescue",p:"/ˈreskjuː/",m:"v./n. 营救",c:"rescue team"},
  {w:"resemble",p:"/rɪˈzembl/",m:"v. 相似，像",c:"resemble each other"},
  {w:"reserve",p:"/rɪˈzɜːv/",m:"v. 预订 n. 储备",c:"reserve a table"},
  {w:"resign",p:"/rɪˈzaɪn/",m:"v. 辞职，顺从",c:"resign from"},
  {w:"resist",p:"/rɪˈzɪst/",m:"v. 抵抗，抵制",c:"resist temptation"},
  {w:"resolve",p:"/rɪˈzɒlv/",m:"v. 解决，决定",c:"resolve conflicts"},
  {w:"resort",p:"/rɪˈzɔːt/",m:"v. 诉诸 n. 度假胜地",c:"resort to"},
  {w:"resource",p:"/rɪˈzɔːs/",m:"n. 资源",c:"human resource"},
  {w:"respond",p:"/rɪˈspɒnd/",m:"v. 回应，回答",c:"respond to"},
  {w:"response",p:"/rɪˈspɒns/",m:"n. 回应，反应",c:"in response to"},
  {w:"responsibility",p:"/rɪˌspɒnsəˈbɪləti/",m:"n. 责任",c:"take responsibility"},
  {w:"restore",p:"/rɪˈstɔːr/",m:"v. 恢复，修复",c:"restore order"},
  {w:"restrict",p:"/rɪˈstrɪkt/",m:"v. 限制",c:"restrict access"},
  {w:"retire",p:"/rɪˈtaɪər/",m:"v. 退休",c:"retire from"},
  {w:"reveal",p:"/rɪˈviːl/",m:"v. 揭示，透露",c:"reveal secrets"},
  {w:"revenue",p:"/ˈrevənjuː/",m:"n. 收入，税收",c:"tax revenue"},
  {w:"reverse",p:"/rɪˈvɜːs/",m:"v./n./adj. 相反(的)",c:"reverse trend"},
  {w:"revolution",p:"/ˌrevəˈluːʃn/",m:"n. 革命，巨变",c:"industrial revolution"},
  {w:"reward",p:"/rɪˈwɔːd/",m:"n. 奖赏 v. 报答",c:"reward for"},
  {w:"risk",p:"/rɪsk/",m:"n. 风险 v. 冒险",c:"take a risk"},
  {w:"rival",p:"/ˈraɪvl/",m:"n. 对手 v. 竞争",c:"rival company"},
  {w:"role",p:"/rəʊl/",m:"n. 角色，作用",c:"play a role"},
  {w:"romantic",p:"/rəʊˈmæntɪk/",m:"adj. 浪漫的",c:"romantic relationship"},
  {w:"routine",p:"/ruːˈtiːn/",m:"n. 常规 adj. 例行的",c:"daily routine"},
  {w:"royal",p:"/ˈrɔɪəl/",m:"adj. 皇家的，王室的",c:"royal family"},
  {w:"rural",p:"/ˈrʊərəl/",m:"adj. 农村的",c:"rural area"},
  {w:"sacrifice",p:"/ˈsækrɪfaɪs/",m:"n./v. 牺牲",c:"make a sacrifice"},
  {w:"salary",p:"/ˈsæləri/",m:"n. 薪水",c:"annual salary"},
  {w:"satisfactory",p:"/ˌsætɪsˈfæktəri/",m:"adj. 令人满意的",c:"satisfactory result"},
  {w:"scale",p:"/skeɪl/",m:"n. 规模，比例",c:"on a large scale"},
  {w:"scan",p:"/skæn/",m:"v./n. 扫描，浏览",c:"scan through"},
  {w:"schedule",p:"/ˈʃedjuːl/",m:"n. 时间表 v. 安排",c:"on schedule"},
  {w:"scheme",p:"/skiːm/",m:"n. 方案 v. 策划",c:"color scheme"},
  {w:"scholar",p:"/ˈskɒlər/",m:"n. 学者",c:"visiting scholar"},
  {w:"scholarship",p:"/ˈskɒləʃɪp/",m:"n. 奖学金",c:"win a scholarship"},
  {w:"scope",p:"/skəʊp/",m:"n. 范围，视野",c:"within the scope"},
  {w:"scratch",p:"/skrætʃ/",m:"v./n. 抓，刮",c:"start from scratch"},
  {w:"sector",p:"/ˈsektər/",m:"n. 部门，领域",c:"private sector"},
  {w:"secure",p:"/sɪˈkjʊər/",m:"adj. 安全的 v. 获得",c:"secure job"},
  {w:"security",p:"/sɪˈkjʊərəti/",m:"n. 安全，保障",c:"national security"},
  {w:"senior",p:"/ˈsiːniər/",m:"adj. 高级的 n. 年长者",c:"senior manager"},
  {w:"sensation",p:"/senˈseɪʃn/",m:"n. 感觉，轰动",c:"cause a sensation"},
  {w:"sensitive",p:"/ˈsensətɪv/",m:"adj. 敏感的",c:"sensitive information"},
  {w:"sequence",p:"/ˈsiːkwəns/",m:"n. 顺序，序列",c:"in sequence"},
  {w:"session",p:"/ˈseʃn/",m:"n. 会议，学期",c:"training session"},
  {w:"severe",p:"/sɪˈvɪər/",m:"adj. 严重的，严厉的",c:"severe weather"},
  {w:"shallow",p:"/ˈʃæləʊ/",m:"adj. 浅的，肤浅的",c:"shallow water"},
  {w:"shelter",p:"/ˈʃeltər/",m:"n. 庇护所 v. 保护",c:"take shelter"},
  {w:"shift",p:"/ʃɪft/",m:"v./n. 转移，轮班",c:"night shift"},
  {w:"shortage",p:"/ˈʃɔːtɪdʒ/",m:"n. 短缺",c:"water shortage"},
  {w:"significant",p:"/sɪɡˈnɪfɪkənt/",m:"adj. 重要的，显著的",c:"significant role"},
  {w:"similar",p:"/ˈsɪmələr/",m:"adj. 相似的",c:"similar to"},
  {w:"simplify",p:"/ˈsɪmplɪfaɪ/",m:"v. 简化",c:"simplify the process"},
  {w:"site",p:"/saɪt/",m:"n. 地点，网站",c:"construction site"},
  {w:"situation",p:"/ˌsɪtʃuˈeɪʃn/",m:"n. 情况，形势",c:"current situation"},
  {w:"sketch",p:"/sketʃ/",m:"n. 素描，概述 v. 画出",c:"sketch out"},
  {w:"slight",p:"/slaɪt/",m:"adj. 轻微的，细微的",c:"slight change"},
  {w:"sole",p:"/səʊl/",m:"adj. 唯一的 n. 鞋底",c:"sole purpose"},
  {w:"solid",p:"/ˈsɒlɪd/",m:"adj. 固体的 n. 固体",c:"solid foundation"},
  {w:"solution",p:"/səˈluːʃn/",m:"n. 解决方案",c:"find a solution"},
  {w:"somewhat",p:"/ˈsʌmwɒt/",m:"adv. 有点，稍微",c:"somewhat different"},
  {w:"source",p:"/sɔːs/",m:"n. 来源，出处",c:"energy source"},
  {w:"span",p:"/spæn/",m:"n. 跨度 v. 跨越",c:"life span"},
  {w:"specialist",p:"/ˈspeʃəlɪst/",m:"n. 专家",c:"heart specialist"},
  {w:"species",p:"/ˈspiːʃiːz/",m:"n. 物种",c:"endangered species"},
  {w:"specific",p:"/spəˈsɪfɪk/",m:"adj. 具体的，特定的",c:"specific area"},
  {w:"specifically",p:"/spəˈsɪfɪkli/",m:"adv. 具体地",c:"more specifically"},
  {w:"spiritual",p:"/ˈspɪrɪtʃuəl/",m:"adj. 精神的",c:"spiritual life"},
  {w:"sponsor",p:"/ˈspɒnsər/",m:"n. 赞助者 v. 赞助",c:"sponsor an event"},
  {w:"stable",p:"/ˈsteɪbl/",m:"adj. 稳定的 n. 马厩",c:"stable economy"},
  {w:"staff",p:"/stɑːf/",m:"n. 员工",c:"staff meeting"},
  {w:"standard",p:"/ˈstændəd/",m:"n. 标准 adj. 标准的",c:"high standard"},
  {w:"status",p:"/ˈsteɪtəs/",m:"n. 地位，状态",c:"social status"},
  {w:"steady",p:"/ˈstedi/",m:"adj. 稳定的，持续的",c:"steady growth"},
  {w:"steep",p:"/stiːp/",m:"adj. 陡峭的，急剧的",c:"steep hill"},
  {w:"stem",p:"/stem/",m:"n. 茎 v. 起源于",c:"stem from"},
  {w:"stimulate",p:"/ˈstɪmjuleɪt/",m:"v. 刺激，激励",c:"stimulate growth"},
  {w:"stock",p:"/stɒk/",m:"n. 库存，股票",c:"stock market"},
  {w:"strategy",p:"/ˈstrætədʒi/",m:"n. 策略",c:"marketing strategy"},
  {w:"strengthen",p:"/ˈstreŋθn/",m:"v. 加强",c:"strengthen ties"},
  {w:"stretch",p:"/stretʃ/",m:"v./n. 伸展",c:"stretch out"},
  {w:"striking",p:"/ˈstraɪkɪŋ/",m:"adj. 显著的，惊人的",c:"striking contrast"},
  {w:"structure",p:"/ˈstrʌktʃər/",m:"n. 结构 v. 组织",c:"social structure"},
  {w:"studio",p:"/ˈstjuːdiəʊ/",m:"n. 工作室，演播室",c:"recording studio"},
  {w:"submit",p:"/səbˈmɪt/",m:"v. 提交，服从",c:"submit a report"},
  {w:"subsequent",p:"/ˈsʌbsɪkwənt/",m:"adj. 随后的",c:"subsequent events"},
  {w:"substance",p:"/ˈsʌbstəns/",m:"n. 物质，实质",c:"chemical substance"},
  {w:"substitute",p:"/ˈsʌbstɪtjuːt/",m:"n. 替代品 v. 替代",c:"substitute for"},
  {w:"sufficient",p:"/səˈfɪʃnt/",m:"adj. 足够的",c:"sufficient evidence"},
  {w:"summarize",p:"/ˈsʌməraɪz/",m:"v. 总结",c:"summarize the main point"},
  {w:"summary",p:"/ˈsʌməri/",m:"n. 摘要",c:"in summary"},
  {w:"superficial",p:"/ˌsuːpəˈfɪʃl/",m:"adj. 表面的，肤浅的",c:"superficial knowledge"},
  {w:"superior",p:"/suːˈpɪəriər/",m:"adj. 优越的 n. 上级",c:"superior quality"},
  {w:"supplement",p:"/ˈsʌplɪment/",m:"n. 补充 v. 增补",c:"dietary supplement"},
  {w:"supreme",p:"/suːˈpriːm/",m:"adj. 最高的，至上的",c:"supreme court"},
  {w:"surplus",p:"/ˈsɜːpləs/",m:"n. 过剩 adj. 多余的",c:"budget surplus"},
  {w:"surrender",p:"/səˈrendər/",m:"v./n. 投降，放弃",c:"surrender to"},
  {w:"survey",p:"/ˈsɜːveɪ/",m:"n./v. 调查",c:"conduct a survey"},
  {w:"survival",p:"/səˈvaɪvl/",m:"n. 幸存，生存",c:"survival skills"},
  {w:"suspect",p:"/səˈspekt/",m:"v. 怀疑 n. 嫌疑人",c:"suspect of"},
  {w:"suspend",p:"/səˈspend/",m:"v. 暂停，悬挂",c:"suspend operations"},
  {w:"sustain",p:"/səˈsteɪn/",m:"v. 维持，支撑",c:"sustain growth"},
  {w:"symbol",p:"/ˈsɪmbl/",m:"n. 象征，符号",c:"status symbol"},
  {w:"sympathy",p:"/ˈsɪmpəθi/",m:"n. 同情，同感",c:"feel sympathy for"},
  {w:"symptom",p:"/ˈsɪmptəm/",m:"n. 症状",c:"common symptom"},
  {w:"target",p:"/ˈtɑːɡɪt/",m:"n. 目标 v. 瞄准",c:"target audience"},
  {w:"technique",p:"/tekˈniːk/",m:"n. 技术，技巧",c:"management technique"},
  {w:"temporary",p:"/ˈtemprəri/",m:"adj. 暂时的",c:"temporary solution"},
  {w:"tendency",p:"/ˈtendənsi/",m:"n. 趋势，倾向",c:"have a tendency to"},
  {w:"terminal",p:"/ˈtɜːmɪnl/",m:"n. 终点站 adj. 终端的",c:"airport terminal"},
  {w:"territory",p:"/ˈterətri/",m:"n. 领土，领域",c:"new territory"},
  {w:"theme",p:"/θiːm/",m:"n. 主题",c:"main theme"},
  {w:"theory",p:"/ˈθɪəri/",m:"n. 理论",c:"in theory"},
  {w:"therapy",p:"/ˈθerəpi/",m:"n. 治疗，疗法",c:"physical therapy"},
  {w:"thorough",p:"/ˈθʌrə/",m:"adj. 彻底的",c:"thorough investigation"},
  {w:"threat",p:"/θret/",m:"n. 威胁",c:"pose a threat"},
  {w:"threaten",p:"/ˈθretn/",m:"v. 威胁",c:"threaten to"},
  {w:"thrive",p:"/θraɪv/",m:"v. 繁荣，兴旺",c:"thrive on"},
  {w:"tolerate",p:"/ˈtɒləreɪt/",m:"v. 容忍，忍受",c:"tolerate behavior"},
  {w:"tone",p:"/təʊn/",m:"n. 语气，音调",c:"tone of voice"},
  {w:"topic",p:"/ˈtɒpɪk/",m:"n. 话题，主题",c:"hot topic"},
  {w:"tough",p:"/tʌf/",m:"adj. 艰苦的，坚强的",c:"tough decision"},
  {w:"trace",p:"/treɪs/",m:"v. 追踪 n. 痕迹",c:"trace back to"},
  {w:"tradition",p:"/trəˈdɪʃn/",m:"n. 传统",c:"cultural tradition"},
  {w:"transaction",p:"/trænˈzækʃn/",m:"n. 交易，业务",c:"business transaction"},
  {w:"transfer",p:"/trænsˈfɜːr/",m:"v./n. 转移，转让",c:"transfer money"},
  {w:"transform",p:"/trænsˈfɔːm/",m:"v. 改变，转变",c:"transform into"},
  {w:"treaty",p:"/ˈtriːti/",m:"n. 条约",c:"peace treaty"},
  {w:"tremendous",p:"/trəˈmendəs/",m:"adj. 巨大的",c:"tremendous effort"},
  {w:"trend",p:"/trend/",m:"n. 趋势，潮流",c:"current trend"},
  {w:"trial",p:"/ˈtraɪəl/",m:"n. 审判，试验",c:"clinical trial"},
  {w:"triumph",p:"/ˈtraɪʌmf/",m:"n. 胜利，成功",c:"moment of triumph"},
  {w:"troop",p:"/truːp/",m:"n. 军队，一群",c:"troop withdrawal"},
  {w:"tropical",p:"/ˈtrɒpɪkl/",m:"adj. 热带的",c:"tropical climate"},
  {w:"typical",p:"/ˈtɪpɪkl/",m:"adj. 典型的",c:"typical example"},
  {w:"ultimate",p:"/ˈʌltɪmət/",m:"adj. 最终的，根本的",c:"ultimate goal"},
  {w:"undergo",p:"/ˌʌndəˈɡəʊ/",m:"v. 经历，遭受",c:"undergo surgery"},
  {w:"undermine",p:"/ˌʌndəˈmaɪn/",m:"v. 削弱，破坏",c:"undermine confidence"},
  {w:"undertake",p:"/ˌʌndəˈteɪk/",m:"v. 承担，从事",c:"undertake a task"},
  {w:"unemployment",p:"/ˌʌnɪmˈplɔɪmənt/",m:"n. 失业",c:"unemployment rate"},
  {w:"unique",p:"/juˈniːk/",m:"adj. 独特的",c:"unique feature"},
  {w:"universal",p:"/ˌjuːnɪˈvɜːsl/",m:"adj. 普遍的，宇宙的",c:"universal truth"},
  {w:"urban",p:"/ˈɜːbən/",m:"adj. 城市的",c:"urban area"},
  {w:"urge",p:"/ɜːdʒ/",m:"v. 敦促 n. 强烈欲望",c:"urge to do"},
  {w:"utility",p:"/juːˈtɪləti/",m:"n. 公用事业，实用",c:"public utility"},
  {w:"utilize",p:"/ˈjuːtəlaɪz/",m:"v. 利用",c:"utilize resources"},
  {w:"utmost",p:"/ˈʌtməʊst/",m:"adj. 最大的 n. 极限",c:"do one's utmost"},
  {w:"vacant",p:"/ˈveɪkənt/",m:"adj. 空的，空缺的",c:"vacant position"},
  {w:"vain",p:"/veɪn/",m:"adj. 徒劳的，虚荣的",c:"in vain"},
  {w:"valid",p:"/ˈvælɪd/",m:"adj. 有效的，合理的",c:"valid reason"},
  {w:"vanish",p:"/ˈvænɪʃ/",m:"v. 消失",c:"vanish into thin air"},
  {w:"variable",p:"/ˈveəriəbl/",m:"adj. 可变的 n. 变量",c:"variable costs"},
  {w:"variation",p:"/ˌveəriˈeɪʃn/",m:"n. 变化，变异",c:"seasonal variation"},
  {w:"vast",p:"/vɑːst/",m:"adj. 巨大的，广阔的",c:"vast majority"},
  {w:"venture",p:"/ˈventʃər/",m:"n. 风险项目 v. 冒险",c:"joint venture"},
  {w:"verify",p:"/ˈverɪfaɪ/",m:"v. 核实，验证",c:"verify information"},
  {w:"version",p:"/ˈvɜːʃn/",m:"n. 版本",c:"latest version"},
  {w:"vessel",p:"/ˈvesl/",m:"n. 船，容器",c:"blood vessel"},
  {w:"victim",p:"/ˈvɪktɪm/",m:"n. 受害者",c:"fall victim to"},
  {w:"violate",p:"/ˈvaɪəleɪt/",m:"v. 违反，侵犯",c:"violate rules"},
  {w:"violence",p:"/ˈvaɪələns/",m:"n. 暴力",c:"domestic violence"},
  {w:"virtual",p:"/ˈvɜːtʃuəl/",m:"adj. 虚拟的，实质的",c:"virtual reality"},
  {w:"virtue",p:"/ˈvɜːtʃuː/",m:"n. 美德，优点",c:"by virtue of"},
  {w:"visible",p:"/ˈvɪzəbl/",m:"adj. 可见的",c:"visible sign"},
  {w:"vision",p:"/ˈvɪʒn/",m:"n. 视力，愿景",c:"have a vision"},
  {w:"visual",p:"/ˈvɪʒuəl/",m:"adj. 视觉的",c:"visual arts"},
  {w:"vital",p:"/ˈvaɪtl/",m:"adj. 至关重要的",c:"vital role"},
  {w:"vivid",p:"/ˈvɪvɪd/",m:"adj. 生动的，鲜明的",c:"vivid memory"},
  {w:"volume",p:"/ˈvɒljuːm/",m:"n. 音量，容量",c:"sales volume"},
  {w:"voluntary",p:"/ˈvɒləntri/",m:"adj. 自愿的",c:"voluntary work"},
  {w:"volunteer",p:"/ˌvɒlənˈtɪər/",m:"n. 志愿者 v. 自愿",c:"volunteer to help"},
  {w:"wage",p:"/weɪdʒ/",m:"n. 工资 v. 发动",c:"minimum wage"},
  {w:"wander",p:"/ˈwɒndər/",m:"v. 漫步，走神",c:"wander around"},
  {w:"wealthy",p:"/ˈwelθi/",m:"adj. 富有的",c:"wealthy family"},
  {w:"weapon",p:"/ˈwepən/",m:"n. 武器",c:"nuclear weapon"},
  {w:"welfare",p:"/ˈwelfeər/",m:"n. 福利",c:"social welfare"},
  {w:"whereas",p:"/ˌweərˈæz/",m:"conj. 然而，鉴于",c:"whereas previously"},
  {w:"widespread",p:"/ˈwaɪdspred/",m:"adj. 广泛的",c:"widespread use"},
  {w:"wisdom",p:"/ˈwɪzdəm/",m:"n. 智慧",c:"conventional wisdom"},
  {w:"withdraw",p:"/wɪðˈdrɔː/",m:"v. 撤回，退出",c:"withdraw from"},
  {w:"withstand",p:"/wɪðˈstænd/",m:"v. 承受，抵抗",c:"withstand pressure"},
  {w:"witness",p:"/ˈwɪtnəs/",m:"n. 目击者 v. 目睹",c:"witness an event"},
  {w:"worldwide",p:"/ˌwɜːldˈwaɪd/",m:"adj./adv. 全世界的",c:"worldwide attention"},
  {w:"worthwhile",p:"/ˌwɜːθˈwaɪl/",m:"adj. 值得的",c:"be worthwhile"},
  {w:"yield",p:"/jiːld/",m:"v. 产生，屈服",c:"yield results"}"""

# Remove leading/trailing whitespace from extra_words
extra_words = extra_words.strip()

# Step 3: 找到 WORD_POOL 的结尾并插入新词
# 在最后一个条目之后、]; 之前插入
pattern = r'(\n  \{w:"worthwhile"[^\}]*\})'
replacement = r'\1,\n' + extra_words

html = re.sub(pattern, replacement, html)
new_count = len(re.findall(r'\{w:"[^"]+"', html))
print(f"Expanded WORD_POOL: {existing_count} → {new_count} entries")

# 确保扩充后的词没有重复
import re as regex
all_words = regex.findall(r'"w":"([^"]*)"', html)
word_set = set()
dups = []
for w in all_words:
    if w in word_set:
        dups.append(w)
    word_set.add(w)
if dups:
    print(f"WARNING: Found duplicate words: {dups}")
else:
    print(f"All {len(all_words)} words are unique ✓")

with open(PATH, 'w', encoding='utf-8') as f:
    f.write(html)

print(f"\nDone! Final size: {len(html)} bytes")
print(f"Total vocab: {new_count} words — enough for {((new_count - 80) // 100) + 1} days at 100/day")
