"""
fix_vocab_v3.py — 全新词汇系统
1. 计算每天词汇（day0-2 旧逻辑保持，day3+ 补词+洗牌）
2. 全部存入 DAILY_WORDS 静态数组
3. getDailyVocab 直接取 DAILY_WORDS[idx]
4. WORD_POOL 仅保留未学词（供后续天使用）
"""
import re, datetime

PATH = r'C:\Users\24470\WorkBuddy\2026-05-21-16-18-52\cet4-study\index.html'
with open(PATH, 'r', encoding='utf-8') as f:
    html = f.read()

START_DATE = datetime.date(2026, 5, 21)
now = datetime.datetime.now()
effective = (now - datetime.timedelta(days=1)).date() if now.hour < 9 else now.date()
todayIndex = (effective - START_DATE).days
print(f"Today: {effective} (dayIndex={todayIndex})")

# ===== 1. 提取原始 WORD_POOL (362 词) =====
m = re.search(r'const WORD_POOL\s*=\s*\[(.*?)\];', html, re.DOTALL)
entry_pat = re.compile(r'(\{[^}]+\})', re.DOTALL)
all_entries = entry_pat.findall(m.group(1))
def wname(e):
    mm = re.search(r'w:"([^"]+)"', e)
    return mm.group(1) if mm else ''
print(f"Original pool: {len(all_entries)} words")

# ===== 2. seededRandom =====
def seededRandom(seed):
    h = 0
    for c in seed: h = ((h << 5) - h) + ord(c); h |= 0
    state = [h]
    def rng():
        state[0] = (state[0] * 1103515245 + 12345) & 0x7fffffff
        return state[0] / 0x7fffffff
    return rng

# ===== 3. CET-4 Bank =====
CET4_BANK = [
    ("abnormal","/æbˈnɔːml/","adj. 反常的","abnormal behavior"),
    ("aboard","/əˈbɔːd/","adv./prep. 在船上","go aboard"),
    ("abolish","/əˈbɒlɪʃ/","v. 废除","abolish slavery"),
    ("abortion","/əˈbɔːʃn/","n. 流产","illegal abortion"),
    ("abroad","/əˈbrɔːd/","adv. 到国外","study abroad"),
    ("absence","/ˈæbsəns/","n. 缺席","in the absence of"),
    ("absolute","/ˈæbsəluːt/","adj. 绝对的","absolute power"),
    ("absurd","/əbˈsɜːd/","adj. 荒谬的","absurd idea"),
    ("accommodate","/əˈkɒmədeɪt/","v. 容纳","accommodate needs"),
    ("accompany","/əˈkʌmpəni/","v. 陪伴","accompany by"),
    ("accomplish","/əˈkɒmplɪʃ/","v. 完成","accomplish goals"),
    ("account","/əˈkaʊnt/","n. 账户","take into account"),
    ("accurate","/ˈækjərət/","adj. 精确的","accurate data"),
    ("accuse","/əˈkjuːz/","v. 指控","accuse of"),
    ("achievement","/əˈtʃiːvmənt/","n. 成就","academic achievement"),
    ("acknowledge","/əkˈnɒlɪdʒ/","v. 承认","acknowledge receipt"),
    ("acquaintance","/əˈkweɪntəns/","n. 熟人","make acquaintance"),
    ("adequate","/ˈædɪkwət/","adj. 足够的","adequate supply"),
    ("admire","/ədˈmaɪər/","v. 钦佩","admire for"),
    ("admission","/ədˈmɪʃn/","n. 准许进入","admission ticket"),
    ("adopt","/əˈdɒpt/","v. 采用","adopt a policy"),
    ("advanced","/ədˈvɑːnst/","adj. 先进的","advanced technology"),
    ("advantage","/ədˈvɑːntɪdʒ/","n. 优势","take advantage of"),
    ("advertise","/ˈædvətaɪz/","v. 做广告","advertise for"),
    ("advocate","/ˈædvəkeɪt/","v. 倡导","advocate for"),
    ("affair","/əˈfeər/","n. 事务","foreign affairs"),
    ("affect","/əˈfekt/","v. 影响","adversely affect"),
    ("afford","/əˈfɔːd/","v. 负担得起","can't afford"),
    ("agency","/ˈeɪdʒənsi/","n. 代理机构","travel agency"),
    ("aggressive","/əˈɡresɪv/","adj. 好斗的","aggressive behavior"),
    ("aid","/eɪd/","n./v. 帮助","first aid"),
    ("aim","/eɪm/","n. 目标 v. 瞄准","aim at"),
    ("alarm","/əˈlɑːm/","n. 警报","fire alarm"),
    ("alert","/əˈlɜːt/","adj. 警觉的","stay alert"),
    ("alcohol","/ˈælkəhɒl/","n. 酒精","alcohol abuse"),
    ("allowance","/əˈlaʊəns/","n. 津贴","make allowance for"),
    ("alongside","/əˌlɒŋˈsaɪd/","prep. 在…旁边","work alongside"),
    ("alter","/ˈɔːltər/","v. 改变","alter the course"),
    ("amaze","/əˈmeɪz/","v. 使惊奇","be amazed at"),
    ("ambition","/æmˈbɪʃn/","n. 雄心","achieve ambition"),
    ("amount","/əˈmaʊnt/","n. 数量","a large amount of"),
    ("amuse","/əˈmjuːz/","v. 逗乐","amuse oneself"),
    ("ancestor","/ˈænsestər/","n. 祖先","common ancestor"),
    ("anchor","/ˈæŋkər/","n. 锚 v. 固定","news anchor"),
    ("ancient","/ˈeɪnʃənt/","adj. 古代的","ancient times"),
    ("angle","/ˈæŋɡl/","n. 角度","from another angle"),
    ("anniversary","/ˌænɪˈvɜːsəri/","n. 周年纪念日","wedding anniversary"),
    ("announce","/əˈnaʊns/","v. 宣布","announce plans"),
    ("annual","/ˈænjuəl/","adj. 年度的","annual report"),
    ("anticipate","/ænˈtɪsɪpeɪt/","v. 预期","anticipate problems"),
    ("anxiety","/æŋˈzaɪəti/","n. 焦虑","anxiety disorder"),
    ("apart","/əˈpɑːt/","adv. 分开","apart from"),
    ("apology","/əˈpɒlədʒi/","n. 道歉","make an apology"),
    ("apparent","/əˈpærənt/","adj. 显然的","apparent reason"),
    ("appeal","/əˈpiːl/","v./n. 呼吁","appeal to"),
    ("appetite","/ˈæpɪtaɪt/","n. 胃口","lose appetite"),
    ("appliance","/əˈplaɪəns/","n. 电器","household appliance"),
    ("applicant","/ˈæplɪkənt/","n. 申请人","job applicant"),
    ("apply","/əˈplaɪ/","v. 申请","apply for"),
    ("appoint","/əˈpɔɪnt/","v. 任命","appoint a leader"),
    ("appointment","/əˈpɔɪntmənt/","n. 约会","make an appointment"),
    ("architecture","/ˈɑːkɪtektʃər/","n. 建筑学","modern architecture"),
    ("argue","/ˈɑːɡjuː/","v. 争论","argue against"),
    ("argument","/ˈɑːɡjumənt/","n. 争论","strong argument"),
    ("arise","/əˈraɪz/","v. 出现","problems arise"),
    ("arrange","/əˈreɪndʒ/","v. 安排","arrange for"),
    ("arrest","/əˈrest/","v./n. 逮捕","under arrest"),
    ("artificial","/ˌɑːtɪˈfɪʃl/","adj. 人工的","artificial intelligence"),
    ("aspect","/ˈæspekt/","n. 方面","every aspect"),
    ("assemble","/əˈsembl/","v. 集合，组装","assemble parts"),
    ("assert","/əˈsɜːt/","v. 断言","assert authority"),
    ("assess","/əˈses/","v. 评估","assess the situation"),
    ("asset","/ˈæset/","n. 资产","valuable asset"),
    ("assign","/əˈsaɪn/","v. 分配","assign tasks"),
    ("assist","/əˈsɪst/","v. 帮助","assist in"),
    ("associate","/əˈsəʊʃieɪt/","v. 联系","associate with"),
    ("assume","/əˈsjuːm/","v. 假设","assume responsibility"),
    ("assumption","/əˈsʌmpʃn/","n. 假设","make an assumption"),
    ("assure","/əˈʃʊər/","v. 使确信","assure safety"),
    ("atmosphere","/ˈætməsfɪər/","n. 氛围","friendly atmosphere"),
    ("attach","/əˈtætʃ/","v. 附上","attach importance to"),
    ("attain","/əˈteɪn/","v. 达到","attain goals"),
    ("attempt","/əˈtempt/","v./n. 尝试","attempt to"),
    ("attend","/əˈtend/","v. 参加","attend a meeting"),
    ("attention","/əˈtenʃn/","n. 注意","pay attention to"),
    ("attitude","/ˈætɪtjuːd/","n. 态度","positive attitude"),
    ("attract","/əˈtrækt/","v. 吸引","attract attention"),
    ("attractive","/əˈtræktɪv/","adj. 有吸引力的","attractive offer"),
    ("attribute","/əˈtrɪbjuːt/","v. 归因于 n. 属性","attribute to"),
    ("audience","/ˈɔːdiəns/","n. 观众","target audience"),
    ("authority","/ɔːˈθɒrəti/","n. 权威","local authority"),
    ("automatic","/ˌɔːtəˈmætɪk/","adj. 自动的","automatic system"),
    ("avenue","/ˈævənjuː/","n. 大街，途径","explore avenues"),
    ("average","/ˈævərɪdʒ/","adj. 平均的","on average"),
    ("avoid","/əˈvɔɪd/","v. 避免","avoid doing"),
    ("award","/əˈwɔːd/","n. 奖品 v. 授予","win an award"),
    ("aware","/əˈweər/","adj. 意识到的","be aware of"),
    ("awful","/ˈɔːfl/","adj. 糟糕的","awful weather"),
    ("awkward","/ˈɔːkwəd/","adj. 尴尬的","awkward situation"),
    ("backup","/ˈbækʌp/","n. 备份 v. 支持","data backup"),
    ("backward","/ˈbækwəd/","adj. 落后的","backward area"),
    ("balance","/ˈbæləns/","n. 平衡 v. 平衡","keep balance"),
    ("ban","/bæn/","v./n. 禁止","ban on"),
    ("bankrupt","/ˈbæŋkrʌpt/","adj. 破产的","go bankrupt"),
    ("barely","/ˈbeəli/","adv. 几乎不","barely enough"),
    ("bargain","/ˈbɑːɡɪn/","n. 便宜货 v. 讨价还价","bargain price"),
    ("barrier","/ˈbæriər/","n. 障碍","language barrier"),
    ("battle","/ˈbætl/","n./v. 战斗","battle against"),
    ("behalf","/bɪˈhɑːf/","n. 利益，代表","on behalf of"),
    ("behave","/bɪˈheɪv/","v. 表现","behave well"),
    ("being","/ˈbiːɪŋ/","n. 生物，存在","human being"),
    ("belief","/bɪˈliːf/","n. 信念","beyond belief"),
    ("beloved","/bɪˈlʌvd/","adj. 心爱的","beloved wife"),
    ("beneath","/bɪˈniːθ/","prep. 在…下方","beneath the surface"),
    ("benefit","/ˈbenɪfɪt/","n. 利益 v. 受益","benefit from"),
    ("betray","/bɪˈtreɪ/","v. 背叛","betray trust"),
    ("billion","/ˈbɪljən/","n. 十亿","billions of"),
    ("bind","/baɪnd/","v. 捆绑","bind together"),
    ("biology","/baɪˈɒlədʒi/","n. 生物学","molecular biology"),
    ("bitter","/ˈbɪtər/","adj. 苦的","bitter experience"),
    ("blade","/bleɪd/","n. 刀刃","sharp blade"),
    ("blame","/bleɪm/","v./n. 责备","blame for"),
    ("blank","/blæŋk/","adj. 空白的","blank space"),
    ("blast","/blɑːst/","n. 爆炸 v. 爆破","blast off"),
    ("blend","/blend/","v./n. 混合","blend in"),
    ("bless","/bles/","v. 祝福","bless with"),
    ("bond","/bɒnd/","n. 纽带，债券","emotional bond"),
    ("boom","/buːm/","n. 繁荣 v. 兴旺","economic boom"),
    ("boost","/buːst/","v./n. 促进","boost confidence"),
    ("border","/ˈbɔːdər/","n. 边境","cross the border"),
    ("bounce","/baʊns/","v. 弹跳","bounce back"),
    ("bound","/baʊnd/","adj. 一定的","be bound to"),
    ("boundary","/ˈbaʊndri/","n. 边界","set boundaries"),
    ("brand","/brænd/","n. 品牌","brand image"),
    ("breed","/briːd/","v. 繁殖 n. 品种","breed animals"),
    ("brilliant","/ˈbrɪliənt/","adj. 杰出的","brilliant idea"),
    ("broad","/brɔːd/","adj. 宽的，广泛的","broad range"),
    ("broadcast","/ˈbrɔːdkɑːst/","v./n. 广播","live broadcast"),
    ("budget","/ˈbʌdʒɪt/","n. 预算","within budget"),
    ("burden","/ˈbɜːdn/","n. 负担","heavy burden"),
    ("burst","/bɜːst/","v. 爆发","burst into tears"),
    ("cabinet","/ˈkæbɪnət/","n. 橱柜，内阁","filing cabinet"),
    ("calculate","/ˈkælkjuleɪt/","v. 计算","calculate risk"),
    ("calendar","/ˈkælɪndər/","n. 日历","lunar calendar"),
    ("campaign","/kæmˈpeɪn/","n. 运动，战役","advertising campaign"),
    ("cancel","/ˈkænsl/","v. 取消","cancel order"),
    ("candidate","/ˈkændɪdət/","n. 候选人","presidential candidate"),
    ("capacity","/kəˈpæsəti/","n. 容量，能力","production capacity"),
    ("capture","/ˈkæptʃər/","v. 俘获","capture attention"),
    ("career","/kəˈrɪər/","n. 职业","career development"),
    ("cargo","/ˈkɑːɡəʊ/","n. 货物","cargo ship"),
    ("cast","/kɑːst/","v. 投掷","cast doubt on"),
    ("casual","/ˈkæʒuəl/","adj. 随便的","casual clothes"),
    ("catalog","/ˈkætəlɒɡ/","n. 目录","product catalog"),
    ("category","/ˈkætəɡəri/","n. 类别","product category"),
    ("caution","/ˈkɔːʃn/","n. 小心","with caution"),
    ("cease","/siːs/","v. 停止","cease to exist"),
    ("celebrate","/ˈselɪbreɪt/","v. 庆祝","celebrate success"),
    ("ceremony","/ˈserəməni/","n. 典礼","opening ceremony"),
    ("certificate","/səˈtɪfɪkət/","n. 证书","birth certificate"),
    ("channel","/ˈtʃænl/","n. 频道，渠道","communication channel"),
    ("character","/ˈkærəktər/","n. 性格，角色","main character"),
    ("characteristic","/ˌkærəktəˈrɪstɪk/","n. 特征","key characteristic"),
    ("charity","/ˈtʃærəti/","n. 慈善","charity event"),
    ("chart","/tʃɑːt/","n. 图表","flow chart"),
    ("chemical","/ˈkemɪkl/","adj. 化学的","chemical reaction"),
    ("chief","/tʃiːf/","adj. 主要的 n. 首领","chief executive"),
    ("circumstance","/ˈsɜːkəmstəns/","n. 环境","under no circumstances"),
    ("civil","/ˈsɪvl/","adj. 公民的","civil rights"),
    ("civilization","/ˌsɪvəlaɪˈzeɪʃn/","n. 文明","ancient civilization"),
    ("claim","/kleɪm/","v./n. 声称","claim responsibility"),
    ("clarify","/ˈklærɪfaɪ/","v. 澄清","clarify the point"),
    ("classic","/ˈklæsɪk/","adj. 经典的","classic example"),
    ("classify","/ˈklæsɪfaɪ/","v. 分类","classify into"),
    ("climate","/ˈklaɪmət/","n. 气候","climate change"),
    ("code","/kəʊd/","n. 代码，准则","dress code"),
    ("collapse","/kəˈlæps/","v./n. 倒塌","economic collapse"),
    ("colleague","/ˈkɒliːɡ/","n. 同事","work colleague"),
    ("column","/ˈkɒləm/","n. 栏目，柱","newspaper column"),
    ("combat","/ˈkɒmbæt/","v./n. 战斗","combat crime"),
    ("combine","/kəmˈbaɪn/","v. 结合","combine with"),
    ("command","/kəˈmɑːnd/","v./n. 命令，掌握","have a command of"),
    ("comment","/ˈkɒment/","n./v. 评论","no comment"),
    ("commerce","/ˈkɒmɜːs/","n. 商业","e-commerce"),
    ("commercial","/kəˈmɜːʃl/","adj. 商业的 n. 广告","commercial bank"),
    ("commission","/kəˈmɪʃn/","n. 委员会，佣金","on commission"),
    ("commit","/kəˈmɪt/","v. 犯(罪)，承诺","commit crime"),
    ("commitment","/kəˈmɪtmənt/","n. 承诺","make a commitment"),
    ("committee","/kəˈmɪti/","n. 委员会","executive committee"),
    ("communicate","/kəˈmjuːnɪkeɪt/","v. 交流","communicate with"),
    ("community","/kəˈmjuːnəti/","n. 社区","local community"),
    ("companion","/kəmˈpæniən/","n. 同伴","travel companion"),
    ("compare","/kəmˈpeər/","v. 比较","compare with"),
    ("compensation","/ˌkɒmpenˈseɪʃn/","n. 补偿","seek compensation"),
    ("compete","/kəmˈpiːt/","v. 竞争","compete against"),
    ("complain","/kəmˈpleɪn/","v. 抱怨","complain about"),
    ("complaint","/kəmˈpleɪnt/","n. 投诉","make a complaint"),
    ("component","/kəmˈpəʊnənt/","n. 组成部分","key component"),
    ("compose","/kəmˈpəʊz/","v. 组成，创作","compose music"),
    ("comprehensive","/ˌkɒmprɪˈhensɪv/","adj. 全面的","comprehensive survey"),
    ("comprise","/kəmˈpraɪz/","v. 包含","be comprised of"),
    ("compromise","/ˈkɒmprəmaɪz/","n./v. 妥协","reach a compromise"),
    ("concept","/ˈkɒnsept/","n. 概念","basic concept"),
    ("concern","/kənˈsɜːn/","n. 关心 v. 涉及","concern about"),
    ("conclude","/kənˈkluːd/","v. 得出结论","conclude that"),
    ("conduct","/kənˈdʌkt/","v. 进行 n. 行为","conduct research"),
    ("conference","/ˈkɒnfərəns/","n. 会议","press conference"),
    ("confidence","/ˈkɒnfɪdəns/","n. 信心","self-confidence"),
    ("confirm","/kənˈfɜːm/","v. 确认","confirm reservation"),
    ("conflict","/ˈkɒnflɪkt/","n. 冲突","conflict of interest"),
    ("confront","/kənˈfrʌnt/","v. 面对","confront challenges"),
    ("confuse","/kənˈfjuːz/","v. 使困惑","confuse A with B"),
    ("congratulate","/kənˈɡrætʃuleɪt/","v. 祝贺","congratulate on"),
    ("connection","/kəˈnekʃn/","n. 连接","Internet connection"),
    ("conscious","/ˈkɒnʃəs/","adj. 有意识的","be conscious of"),
    ("consequence","/ˈkɒnsɪkwəns/","n. 结果","face consequences"),
    ("conservation","/ˌkɒnsəˈveɪʃn/","n. 保护","energy conservation"),
    ("considerable","/kənˈsɪdərəbl/","adj. 相当大的","considerable amount"),
    ("consist","/kənˈsɪst/","v. 组成","consist of"),
    ("constant","/ˈkɒnstənt/","adj. 不断的","constant effort"),
    ("constitute","/ˈkɒnstɪtjuːt/","v. 构成","constitute a threat"),
    ("construct","/kənˈstrʌkt/","v. 建造","construct a bridge"),
    ("consult","/kənˈsʌlt/","v. 咨询","consult a doctor"),
    ("consume","/kənˈsjuːm/","v. 消费","consume energy"),
    ("consumer","/kənˈsjuːmər/","n. 消费者","consumer rights"),
    ("contact","/ˈkɒntækt/","n./v. 联系","contact information"),
    ("contain","/kənˈteɪn/","v. 包含","contain information"),
    ("contemporary","/kənˈtemprəri/","adj. 当代的","contemporary art"),
    ("content","/ˈkɒntent/","n. 内容 adj. 满足的","be content with"),
    ("contest","/ˈkɒntest/","n. 竞赛","enter a contest"),
    ("context","/ˈkɒntekst/","n. 上下文","in context"),
    ("continuous","/kənˈtɪnjuəs/","adj. 连续的","continuous process"),
    ("contract","/ˈkɒntrækt/","n. 合同 v. 收缩","sign a contract"),
    ("contrary","/ˈkɒntrəri/","adj. 相反的","on the contrary"),
    ("contrast","/ˈkɒntrɑːst/","n./v. 对比","in contrast to"),
    ("contribute","/kənˈtrɪbjuːt/","v. 贡献","contribute to"),
    ("controversial","/ˌkɒntrəˈvɜːʃl/","adj. 有争议的","controversial issue"),
    ("convenience","/kənˈviːniəns/","n. 便利","for convenience"),
    ("conventional","/kənˈvenʃənl/","adj. 传统的","conventional method"),
    ("convert","/kənˈvɜːt/","v. 转变","convert into"),
    ("convey","/kənˈveɪ/","v. 传达","convey message"),
    ("convince","/kənˈvɪns/","v. 说服","convince someone"),
    ("cooperate","/kəʊˈɒpəreɪt/","v. 合作","cooperate with"),
    ("coordinate","/kəʊˈɔːdɪneɪt/","v. 协调","coordinate efforts"),
    ("cope","/kəʊp/","v. 应付","cope with"),
    ("core","/kɔːr/","n. 核心","core value"),
    ("corporate","/ˈkɔːpərət/","adj. 公司的","corporate culture"),
    ("corporation","/ˌkɔːpəˈreɪʃn/","n. 公司","multinational corporation"),
    ("correspond","/ˌkɒrəˈspɒnd/","v. 对应","correspond to"),
    ("county","/ˈkaʊnti/","n. 县","county level"),
    ("court","/kɔːt/","n. 法庭","supreme court"),
    ("crash","/kræʃ/","v./n. 碰撞","car crash"),
    ("creative","/kriˈeɪtɪv/","adj. 创造性的","creative thinking"),
    ("credit","/ˈkredɪt/","n. 信用，学分","credit card"),
    ("crime","/kraɪm/","n. 犯罪","commit a crime"),
    ("criminal","/ˈkrɪmɪnl/","adj. 犯罪的 n. 罪犯","criminal law"),
    ("crisis","/ˈkraɪsɪs/","n. 危机","financial crisis"),
    ("criterion","/kraɪˈtɪəriən/","n. 标准","selection criterion"),
    ("critical","/ˈkrɪtɪkl/","adj. 批评的，关键的","critical thinking"),
    ("criticism","/ˈkrɪtɪsɪzəm/","n. 批评","constructive criticism"),
    ("cultivate","/ˈkʌltɪveɪt/","v. 培养","cultivate habits"),
    ("culture","/ˈkʌltʃər/","n. 文化","corporate culture"),
    ("curiosity","/ˌkjʊəriˈɒsəti/","n. 好奇心","out of curiosity"),
    ("currency","/ˈkʌrənsi/","n. 货币","foreign currency"),
    ("current","/ˈkʌrənt/","adj. 当前的","current situation"),
    ("curriculum","/kəˈrɪkjələm/","n. 课程","curriculum vitae"),
    ("damage","/ˈdæmɪdʒ/","n./v. 损害","cause damage"),
    ("deadline","/ˈdedlaɪn/","n. 截止日期","meet the deadline"),
    ("debate","/dɪˈbeɪt/","n./v. 辩论","heated debate"),
    ("debt","/det/","n. 债务","in debt"),
    ("decade","/ˈdekeɪd/","n. 十年","over the past decade"),
    ("deceive","/dɪˈsiːv/","v. 欺骗","deceive someone"),
    ("decline","/dɪˈklaɪn/","v./n. 下降，拒绝","decline an offer"),
    ("decorate","/ˈdekəreɪt/","v. 装饰","decorate the room"),
    ("defeat","/dɪˈfiːt/","v./n. 击败","defeat the enemy"),
    ("defend","/dɪˈfend/","v. 防御，辩护","defend against"),
    ("define","/dɪˈfaɪn/","v. 定义","define as"),
    ("definite","/ˈdefɪnət/","adj. 明确的","definite answer"),
    ("definitely","/ˈdefɪnətli/","adv. 肯定地","definitely true"),
    ("delay","/dɪˈleɪ/","v./n. 延迟","without delay"),
    ("delegate","/ˈdelɪɡət/","n. 代表 v. 授权","delegate authority"),
    ("deliberate","/dɪˈlɪbərət/","adj. 故意的","deliberate attempt"),
    ("delicate","/ˈdelɪkət/","adj. 精致的","delicate situation"),
    ("deliver","/dɪˈlɪvər/","v. 递送，发表","deliver a speech"),
    ("demand","/dɪˈmɑːnd/","v./n. 需求","supply and demand"),
    ("democracy","/dɪˈmɒkrəsi/","n. 民主","democracy and freedom"),
    ("demonstrate","/ˈdemənstreɪt/","v. 展示","demonstrate ability"),
    ("dense","/dens/","adj. 密集的","dense population"),
    ("deny","/dɪˈnaɪ/","v. 否认","deny access"),
    ("depart","/dɪˈpɑːt/","v. 离开","depart from"),
    ("department","/dɪˈpɑːtmənt/","n. 部门","marketing department"),
    ("departure","/dɪˈpɑːtʃər/","n. 离开","departure time"),
    ("depend","/dɪˈpend/","v. 依赖","depend on"),
    ("deposit","/dɪˈpɒzɪt/","n. 存款 v. 存放","bank deposit"),
    ("depress","/dɪˈpres/","v. 使沮丧","depress economy"),
    ("depression","/dɪˈpreʃn/","n. 抑郁，萧条","economic depression"),
    ("derive","/dɪˈraɪv/","v. 源自","derive from"),
    ("deserve","/dɪˈzɜːv/","v. 值得","deserve attention"),
    ("desire","/dɪˈzaɪər/","n./v. 渴望","strong desire"),
    ("desperate","/ˈdespərət/","adj. 绝望的","desperate situation"),
    ("despite","/dɪˈspaɪt/","prep. 尽管","despite the fact"),
    ("destination","/ˌdestɪˈneɪʃn/","n. 目的地","tourist destination"),
    ("destroy","/dɪˈstrɔɪ/","v. 破坏","destroy evidence"),
    ("detail","/ˈdiːteɪl/","n. 细节 v. 详述","in detail"),
    ("detect","/dɪˈtekt/","v. 发现","detect changes"),
    ("determination","/dɪˌtɜːmɪˈneɪʃn/","n. 决心","show determination"),
    ("determine","/dɪˈtɜːmɪn/","v. 决定","determine to do"),
    ("device","/dɪˈvaɪs/","n. 设备","electronic device"),
    ("devote","/dɪˈvəʊt/","v. 致力于","devote to"),
    ("differ","/ˈdɪfər/","v. 不同","differ from"),
    ("digital","/ˈdɪdʒɪtl/","adj. 数字的","digital age"),
    ("dignity","/ˈdɪɡnəti/","n. 尊严","human dignity"),
    ("dimension","/daɪˈmenʃn/","n. 尺寸，维度","third dimension"),
    ("discipline","/ˈdɪsəplɪn/","n. 纪律","self-discipline"),
    ("discount","/ˈdɪskaʊnt/","n. 折扣","at a discount"),
    ("display","/dɪˈspleɪ/","v./n. 展示","on display"),
    ("dispose","/dɪˈspəʊz/","v. 处理","dispose of"),
    ("dispute","/dɪˈspjuːt/","n./v. 争论","labor dispute"),
    ("dissolve","/dɪˈzɒlv/","v. 溶解","dissolve in water"),
    ("distinct","/dɪˈstɪŋkt/","adj. 不同的","distinct from"),
    ("distinguish","/dɪˈstɪŋɡwɪʃ/","v. 区分","distinguish between"),
    ("distribute","/dɪˈstrɪbjuːt/","v. 分发","distribute to"),
    ("diverse","/daɪˈvɜːs/","adj. 多样的","culturally diverse"),
    ("division","/dɪˈvɪʒn/","n. 划分","division of labor"),
    ("document","/ˈdɒkjumənt/","n. 文件","official document"),
    ("domestic","/dəˈmestɪk/","adj. 国内的","domestic market"),
    ("dominant","/ˈdɒmɪnənt/","adj. 主导的","dominant position"),
    ("dominate","/ˈdɒmɪneɪt/","v. 主导","dominate the market"),
    ("donation","/dəʊˈneɪʃn/","n. 捐赠","make a donation"),
    ("draft","/drɑːft/","n. 草稿 v. 起草","first draft"),
    ("dramatic","/drəˈmætɪk/","adj. 戏剧性的","dramatic change"),
    ("drift","/drɪft/","v./n. 漂流","drift apart"),
    ("dynamic","/daɪˈnæmɪk/","adj. 动态的","dynamic economy"),
    ("ease","/iːz/","n. 容易 v. 减轻","with ease"),
    ("economic","/ˌiːkəˈnɒmɪk/","adj. 经济的","economic growth"),
    ("economical","/ˌiːkəˈnɒmɪkl/","adj. 节约的","economical car"),
    ("economy","/ɪˈkɒnəmi/","n. 经济","global economy"),
    ("edition","/ɪˈdɪʃn/","n. 版本","special edition"),
    ("editor","/ˈedɪtər/","n. 编辑","chief editor"),
    ("educate","/ˈedʒukeɪt/","v. 教育","educate children"),
    ("effective","/ɪˈfektɪv/","adj. 有效的","effective method"),
    ("efficiency","/ɪˈfɪʃnsi/","n. 效率","improve efficiency"),
    ("efficient","/ɪˈfɪʃnt/","adj. 高效的","energy efficient"),
    ("elaborate","/ɪˈlæbərət/","adj. 精心的","elaborate on"),
    ("election","/ɪˈlekʃn/","n. 选举","general election"),
    ("electronic","/ɪˌlekˈtrɒnɪk/","adj. 电子的","electronic device"),
    ("element","/ˈelɪmənt/","n. 元素","key element"),
    ("eliminate","/ɪˈlɪmɪneɪt/","v. 消除","eliminate poverty"),
    ("embrace","/ɪmˈbreɪs/","v. 拥抱，接受","embrace change"),
    ("emerge","/ɪˈmɜːdʒ/","v. 出现","emerge as"),
    ("emergency","/ɪˈmɜːdʒənsi/","n. 紧急情况","emergency room"),
    ("emission","/ɪˈmɪʃn/","n. 排放","carbon emission"),
    ("emotion","/ɪˈməʊʃn/","n. 情感","express emotion"),
    ("emphasis","/ˈemfəsɪs/","n. 强调","put emphasis on"),
    ("emphasize","/ˈemfəsaɪz/","v. 强调","emphasize the importance"),
    ("employ","/ɪmˈplɔɪ/","v. 雇用","employ workers"),
    ("employee","/ɪmˈplɔɪiː/","n. 雇员","employee benefits"),
    ("employer","/ɪmˈplɔɪər/","n. 雇主","employer brand"),
    ("enable","/ɪˈneɪbl/","v. 使能够","enable to do"),
    ("encounter","/ɪnˈkaʊntər/","v./n. 遭遇","encounter problems"),
    ("engage","/ɪnˈɡeɪdʒ/","v. 从事，吸引","engage in"),
    ("enhance","/ɪnˈhɑːns/","v. 提高","enhance performance"),
    ("enormous","/ɪˈnɔːməs/","adj. 巨大的","enormous potential"),
    ("ensure","/ɪnˈʃʊər/","v. 确保","ensure safety"),
    ("enterprise","/ˈentəpraɪz/","n. 企业","private enterprise"),
    ("entertain","/ˌentəˈteɪn/","v. 娱乐","entertain guests"),
    ("enthusiasm","/ɪnˈθjuːziæzəm/","n. 热情","show enthusiasm"),
    ("entitle","/ɪnˈtaɪtl/","v. 给…权利","be entitled to"),
    ("equip","/ɪˈkwɪp/","v. 装备","equip with"),
    ("equivalent","/ɪˈkwɪvələnt/","adj. 等价的","equivalent to"),
    ("error","/ˈerər/","n. 错误","human error"),
    ("essential","/ɪˈsenʃl/","adj. 必要的","essential role"),
    ("establish","/ɪˈstæblɪʃ/","v. 建立","establish contact"),
    ("estate","/ɪˈsteɪt/","n. 房地产","real estate"),
    ("estimate","/ˈestɪmeɪt/","v./n. 估计","rough estimate"),
    ("evaluate","/ɪˈvæljueɪt/","v. 评估","evaluate performance"),
    ("evidence","/ˈevɪdəns/","n. 证据","scientific evidence"),
    ("evident","/ˈevɪdənt/","adj. 明显的","self-evident"),
    ("evolution","/ˌiːvəˈluːʃn/","n. 进化","human evolution"),
    ("evolve","/ɪˈvɒlv/","v. 进化","evolve into"),
    ("exaggerate","/ɪɡˈzædʒəreɪt/","v. 夸大","tend to exaggerate"),
    ("examine","/ɪɡˈzæmɪn/","v. 检查","examine carefully"),
    ("exceed","/ɪkˈsiːd/","v. 超过","exceed expectations"),
    ("exception","/ɪkˈsepʃn/","n. 例外","without exception"),
    ("excessive","/ɪkˈsesɪv/","adj. 过度的","excessive use"),
    ("exchange","/ɪksˈtʃeɪndʒ/","v./n. 交换","exchange rate"),
    ("exclude","/ɪkˈskluːd/","v. 排除","exclude from"),
    ("execute","/ˈeksɪkjuːt/","v. 执行","execute a plan"),
    ("executive","/ɪɡˈzekjətɪv/","adj. 执行的 n. 主管","chief executive"),
    ("exhibit","/ɪɡˈzɪbɪt/","v. 展示","exhibit behavior"),
    ("expand","/ɪkˈspænd/","v. 扩张","expand business"),
    ("expense","/ɪkˈspens/","n. 费用","at the expense of"),
    ("expert","/ˈekspɜːt/","n. 专家","subject expert"),
    ("exploit","/ɪkˈsplɔɪt/","v. 开发，剥削","exploit resources"),
    ("explore","/ɪkˈsplɔːr/","v. 探索","explore options"),
    ("export","/ɪkˈspɔːt/","v./n. 出口","export goods"),
    ("expose","/ɪkˈspəʊz/","v. 暴露","expose to"),
    ("extend","/ɪkˈstend/","v. 延伸","extend deadline"),
    ("extensive","/ɪkˈstensɪv/","adj. 广泛的","extensive research"),
    ("extent","/ɪkˈstent/","n. 程度","to some extent"),
    ("external","/ɪkˈstɜːnl/","adj. 外部的","external factors"),
    ("extraordinary","/ɪkˈstrɔːdnri/","adj. 非凡的","extraordinary achievement"),
    ("extreme","/ɪkˈstriːm/","adj. 极端的","extreme weather"),
    # === Tier 2: 四级中高频 ===
    ("facilitate","/fəˈsɪlɪteɪt/","v. 促进","facilitate communication"),
    ("facility","/fəˈsɪləti/","n. 设施","sports facility"),
    ("factor","/ˈfæktər/","n. 因素","key factor"),
    ("faith","/feɪθ/","n. 信念","have faith in"),
    ("fame","/feɪm/","n. 名声","rise to fame"),
    ("famine","/ˈfæmɪn/","n. 饥荒","famine relief"),
    ("fascinate","/ˈfæsɪneɪt/","v. 使着迷","be fascinated by"),
    ("fashion","/ˈfæʃn/","n. 时尚","in fashion"),
    ("fatal","/ˈfeɪtl/","adj. 致命的","fatal accident"),
    ("fault","/fɔːlt/","n. 缺点","find fault with"),
    ("feasible","/ˈfiːzəbl/","adj. 可行的","feasible solution"),
    ("feature","/ˈfiːtʃər/","n. 特点","key feature"),
    ("feedback","/ˈfiːdbæk/","n. 反馈","positive feedback"),
    ("fertile","/ˈfɜːtaɪl/","adj. 肥沃的","fertile land"),
    ("fiction","/ˈfɪkʃn/","n. 小说","science fiction"),
    ("fierce","/fɪəs/","adj. 激烈的","fierce competition"),
    ("finance","/ˈfaɪnæns/","n. 金融","personal finance"),
    ("flourish","/ˈflʌrɪʃ/","v. 繁荣","flourish in"),
    ("forecast","/ˈfɔːkɑːst/","n./v. 预测","weather forecast"),
    ("format","/ˈfɔːmæt/","n. 格式","file format"),
    ("formula","/ˈfɔːmjələ/","n. 公式","mathematical formula"),
    ("fortune","/ˈfɔːtʃuːn/","n. 命运，财富","make a fortune"),
    ("foundation","/faʊnˈdeɪʃn/","n. 基础","solid foundation"),
    ("fraction","/ˈfrækʃn/","n. 分数，小部分","a fraction of"),
    ("framework","/ˈfreɪmwɜːk/","n. 框架","legal framework"),
    ("frontier","/ˈfrʌntɪər/","n. 边境，前沿","new frontier"),
    ("fulfill","/fʊlˈfɪl/","v. 实现","fulfill a dream"),
    ("fundamental","/ˌfʌndəˈmentl/","adj. 基本的","fundamental change"),
    ("gain","/ɡeɪn/","v. 获得 n. 收益","gain experience"),
    ("gap","/ɡæp/","n. 缺口，差距","generation gap"),
    ("gender","/ˈdʒendər/","n. 性别","gender equality"),
    ("generate","/ˈdʒenəreɪt/","v. 产生","generate income"),
    ("generous","/ˈdʒenərəs/","adj. 慷慨的","generous donation"),
    ("genuine","/ˈdʒenjuɪn/","adj. 真正的","genuine interest"),
    ("gesture","/ˈdʒestʃər/","n. 手势","kind gesture"),
    ("global","/ˈɡləʊbl/","adj. 全球的","global warming"),
    ("globe","/ɡləʊb/","n. 地球","across the globe"),
    ("grant","/ɡrɑːnt/","v. 授予 n. 拨款","take for granted"),
    ("grasp","/ɡrɑːsp/","v./n. 抓住，理解","grasp the concept"),
    ("grateful","/ˈɡreɪtfl/","adj. 感激的","be grateful for"),
    ("guarantee","/ˌɡærənˈtiː/","v./n. 保证","guarantee quality"),
    ("guidance","/ˈɡaɪdns/","n. 指导","career guidance"),
    ("guideline","/ˈɡaɪdlaɪn/","n. 指导方针","follow guidelines"),
    ("guilty","/ˈɡɪlti/","adj. 有罪的","feel guilty"),
    ("halt","/hɔːlt/","v./n. 停止","come to a halt"),
    ("handle","/ˈhændl/","v. 处理 n. 把手","handle pressure"),
    ("harsh","/hɑːʃ/","adj. 严酷的","harsh conditions"),
    ("hazard","/ˈhæzəd/","n. 危险","health hazard"),
    ("hence","/hens/","adv. 因此","and hence"),
    ("heritage","/ˈherɪtɪdʒ/","n. 遗产","cultural heritage"),
    ("highlight","/ˈhaɪlaɪt/","v. 强调","highlight the importance"),
    ("horizon","/həˈraɪzn/","n. 地平线","broaden horizon"),
    ("hostile","/ˈhɒstaɪl/","adj. 敌对的","hostile environment"),
    ("household","/ˈhaʊshəʊld/","n. 家庭","household chores"),
    ("humble","/ˈhʌmbl/","adj. 谦逊的","humble beginnings"),
    ("ideal","/aɪˈdiːəl/","adj. 理想的","ideal solution"),
    ("identical","/aɪˈdentɪkl/","adj. 相同的","identical to"),
    ("identify","/aɪˈdentɪfaɪ/","v. 识别","identify with"),
    ("identity","/aɪˈdentəti/","n. 身份","cultural identity"),
    ("ignorance","/ˈɪɡnərəns/","n. 无知","ignorance of law"),
    ("illegal","/ɪˈliːɡl/","adj. 非法的","illegal activities"),
    ("illustrate","/ˈɪləstreɪt/","v. 说明","illustrate a point"),
    ("image","/ˈɪmɪdʒ/","n. 形象","public image"),
    ("imagination","/ɪˌmædʒɪˈneɪʃn/","n. 想象力","beyond imagination"),
    ("immediate","/ɪˈmiːdiət/","adj. 立即的","immediate action"),
    ("immigrant","/ˈɪmɪɡrənt/","n. 移民","illegal immigrant"),
    ("impact","/ˈɪmpækt/","n./v. 影响","significant impact"),
    ("implement","/ˈɪmplɪment/","v. 实施","implement a plan"),
    ("impose","/ɪmˈpəʊz/","v. 强加","impose restrictions"),
    ("impress","/ɪmˈpres/","v. 给…印象","impress upon"),
    ("incident","/ˈɪnsɪdənt/","n. 事件","isolated incident"),
    ("incline","/ɪnˈklaɪn/","v. 倾向","be inclined to"),
    ("income","/ˈɪnkʌm/","n. 收入","annual income"),
    ("increasingly","/ɪnˈkriːsɪŋli/","adv. 日益","increasingly popular"),
    ("independence","/ˌɪndɪˈpendəns/","n. 独立","gain independence"),
    ("indicate","/ˈɪndɪkeɪt/","v. 表明","indicate that"),
    ("individual","/ˌɪndɪˈvɪdʒuəl/","adj. 个人的","individual needs"),
    ("industrial","/ɪnˈdʌstriəl/","adj. 工业的","industrial revolution"),
    ("inevitable","/ɪnˈevɪtəbl/","adj. 不可避免的","inevitable consequence"),
    ("infant","/ˈɪnfənt/","n. 婴儿","infant mortality"),
    ("inflation","/ɪnˈfleɪʃn/","n. 通货膨胀","inflation rate"),
    ("inform","/ɪnˈfɔːm/","v. 通知","inform someone"),
    ("initial","/ɪˈnɪʃl/","adj. 最初的","initial stage"),
    ("initiative","/ɪˈnɪʃətɪv/","n. 主动性","take the initiative"),
    ("injure","/ˈɪndʒər/","v. 伤害","injure seriously"),
    ("innocent","/ˈɪnəsnt/","adj. 无辜的","innocent people"),
    ("innovation","/ˌɪnəˈveɪʃn/","n. 创新","technological innovation"),
    ("input","/ˈɪnpʊt/","n./v. 输入","input data"),
    ("insight","/ˈɪnsaɪt/","n. 洞察力","valuable insight"),
    ("inspect","/ɪnˈspekt/","v. 检查","inspect carefully"),
    ("inspire","/ɪnˈspaɪər/","v. 激励","inspire others"),
    ("install","/ɪnˈstɔːl/","v. 安装","install software"),
    ("instance","/ˈɪnstəns/","n. 例子","for instance"),
    ("institute","/ˈɪnstɪtjuːt/","n. 机构","research institute"),
    ("institution","/ˌɪnstɪˈtjuːʃn/","n. 机构","financial institution"),
    ("instrument","/ˈɪnstrəmənt/","n. 乐器","musical instrument"),
    ("insurance","/ɪnˈʃʊərəns/","n. 保险","health insurance"),
    ("intellectual","/ˌɪntəˈlektʃuəl/","adj. 智力的","intellectual property"),
    ("intelligence","/ɪnˈtelɪdʒəns/","n. 智力，情报","artificial intelligence"),
    ("intense","/ɪnˈtens/","adj. 强烈的","intense competition"),
    ("intention","/ɪnˈtenʃn/","n. 意图","good intention"),
    ("interact","/ˌɪntərˈækt/","v. 互动","interact with"),
    ("interpret","/ɪnˈtɜːprɪt/","v. 解释，口译","interpret as"),
    ("interval","/ˈɪntəvl/","n. 间隔","at regular intervals"),
    ("invest","/ɪnˈvest/","v. 投资","invest in"),
    ("investigate","/ɪnˈvestɪɡeɪt/","v. 调查","investigate the case"),
    ("investment","/ɪnˈvestmənt/","n. 投资","return on investment"),
    ("involve","/ɪnˈvɒlv/","v. 涉及","involve in"),
    ("isolate","/ˈaɪsəleɪt/","v. 隔离","isolate from"),
    ("issue","/ˈɪʃuː/","n. 问题 v. 发行","social issue"),
    ("joint","/dʒɔɪnt/","adj. 联合的 n. 关节","joint effort"),
    ("journal","/ˈdʒ�ːnl/","n. 期刊","academic journal"),
    ("judgment","/ˈdʒʌdʒmənt/","n. 判断","good judgment"),
    ("justice","/ˈdʒʌstɪs/","n. 公正","social justice"),
    ("justify","/ˈdʒʌstɪfaɪ/","v. 证明…正当","justify the cost"),
    ("keen","/kiːn/","adj. 热衷的","be keen on"),
    ("label","/ˈleɪbl/","n. 标签 v. 标注","warning label"),
    ("landscape","/ˈlændskeɪp/","n. 风景","urban landscape"),
    ("largely","/ˈlɑːdʒli/","adv. 很大程度上","largely due to"),
    ("launch","/lɔːntʃ/","v./n. 发射，启动","launch a product"),
    ("layer","/ˈleɪər/","n. 层","ozone layer"),
    ("layout","/ˈleɪaʊt/","n. 布局","page layout"),
    ("leadership","/ˈliːdəʃɪp/","n. 领导能力","under the leadership"),
    ("leak","/liːk/","v./n. 泄漏","leak information"),
    ("legal","/ˈliːɡl/","adj. 合法的","legal system"),
    ("legislation","/ˌledʒɪsˈleɪʃn/","n. 立法","pass legislation"),
    ("leisure","/ˈleʒər/","n. 闲暇","leisure time"),
    ("lest","/lest/","conj. 唯恐","lest we forget"),
    ("liability","/ˌlaɪəˈbɪləti/","n. 责任","legal liability"),
    ("liberal","/ˈlɪbərəl/","adj. 自由的","liberal arts"),
    ("liberty","/ˈlɪbəti/","n. 自由","take the liberty"),
    ("license","/ˈlaɪsns/","n. 许可证 v. 许可","driver's license"),
    ("limitation","/ˌlɪmɪˈteɪʃn/","n. 限制","statute of limitations"),
    ("link","/lɪŋk/","n. 链接 v. 联系","link to"),
    ("literature","/ˈlɪtrətʃər/","n. 文学","English literature"),
    ("loan","/ləʊn/","n. 贷款 v. 借出","bank loan"),
    ("logic","/ˈlɒdʒɪk/","n. 逻辑","logic thinking"),
    ("luxury","/ˈlʌkʃəri/","n. 奢侈","luxury goods"),
    ("maintain","/meɪnˈteɪn/","v. 维持","maintain order"),
    ("manual","/ˈmænjuəl/","adj. 手工的 n. 手册","user manual"),
    ("manufacture","/ˌmænjuˈfæktʃər/","v./n. 制造","manufacture goods"),
    ("massive","/ˈmæsɪv/","adj. 巨大的","massive change"),
    ("mature","/məˈtʃʊər/","adj. 成熟的","mature market"),
    ("maximum","/ˈmæksɪməm/","n. 最大(值)","maximum capacity"),
    ("mechanism","/ˈmekənɪzəm/","n. 机制","defense mechanism"),
    ("media","/ˈmiːdiə/","n. 媒体","social media"),
    ("medium","/ˈmiːdiəm/","n. 媒介 adj. 中等的","medium size"),
    ("mental","/ˈmentl/","adj. 心理的","mental health"),
    ("mention","/ˈmenʃn/","v./n. 提及","not to mention"),
    ("mercy","/ˈmɜːsi/","n. 仁慈","at the mercy of"),
    ("mild","/maɪld/","adj. 温和的","mild climate"),
    ("military","/ˈmɪlətri/","adj. 军事的","military service"),
    ("minimum","/ˈmɪnɪməm/","n. 最小(值)","minimum wage"),
    ("minor","/ˈmaɪnər/","adj. 较小的","minor role"),
    ("minority","/maɪˈnɒrəti/","n. 少数","ethnic minority"),
    ("miracle","/ˈmɪrəkl/","n. 奇迹","economic miracle"),
    ("mission","/ˈmɪʃn/","n. 使命","carry out a mission"),
    ("mobile","/ˈməʊbaɪl/","adj. 移动的","mobile phone"),
    ("moderate","/ˈmɒdərət/","adj. 适度的","moderate exercise"),
    ("modify","/ˈmɒdɪfaɪ/","v. 修改","modify behavior"),
    ("monitor","/ˈmɒnɪtər/","v. 监控 n. 显示器","monitor progress"),
    ("moral","/ˈmɒrəl/","adj. 道德的 n. 寓意","moral value"),
    ("moreover","/mɔːrˈəʊvər/","adv. 此外","moreover important"),
    ("motion","/ˈməʊʃn/","n. 运动","in motion"),
    ("motivate","/ˈməʊtɪveɪt/","v. 激励","motivate employees"),
    ("multiple","/ˈmʌltɪpl/","adj. 多重的","multiple times"),
    ("mutual","/ˈmjuːtʃuəl/","adj. 相互的","mutual benefit"),
    ("narrative","/ˈnærətɪv/","n. 叙述","personal narrative"),
    ("narrow","/ˈnærəʊ/","adj. 狭窄的","narrow down"),
    ("negotiate","/nɪˈɡəʊʃieɪt/","v. 谈判","negotiate with"),
    ("neutral","/ˈnjuːtrəl/","adj. 中立的","neutral position"),
    ("nevertheless","/ˌnevəðəˈles/","adv. 然而","but nevertheless"),
    ("notion","/ˈnəʊʃn/","n. 概念","have no notion"),
    ("numerous","/ˈnjuːmərəs/","adj. 许多的","numerous times"),
    ("objection","/əbˈdʒekʃn/","n. 反对","raise an objection"),
    ("objective","/əbˈdʒektɪv/","n. 目标 adj. 客观的","achieve objective"),
    ("obligation","/ˌɒblɪˈɡeɪʃn/","n. 义务","legal obligation"),
    ("observe","/əbˈzɜːv/","v. 观察，遵守","observe rules"),
    ("obstacle","/ˈɒbstəkl/","n. 障碍","overcome obstacles"),
    ("obtain","/əbˈteɪn/","v. 获得","obtain information"),
    ("obvious","/ˈɒbviəs/","adj. 明显的","obvious reason"),
    ("occasion","/əˈkeɪʒn/","n. 场合","on occasion"),
    ("occupy","/ˈɒkjupaɪ/","v. 占据","occupy time"),
    ("ongoing","/ˈɒnɡəʊɪŋ/","adj. 进行中的","ongoing project"),
    ("operate","/ˈɒpəreɪt/","v. 操作","operate a machine"),
    ("opponent","/əˈpəʊnənt/","n. 对手","political opponent"),
    ("opportunity","/ˌɒpəˈtjuːnəti/","n. 机会","seize the opportunity"),
    ("oppose","/əˈpəʊz/","v. 反对","oppose the plan"),
    ("option","/ˈɒpʃn/","n. 选择","have no option"),
    ("organic","/ɔːˈɡænɪk/","adj. 有机的","organic food"),
    ("original","/əˈrɪdʒənl/","adj. 原来的，独创的","original idea"),
    ("otherwise","/ˈʌðəwaɪz/","adv. 否则","or otherwise"),
    ("outcome","/ˈaʊtkʌm/","n. 结果","final outcome"),
    ("outstanding","/aʊtˈstændɪŋ/","adj. 杰出的","outstanding achievement"),
    ("overall","/ˌəʊvərˈɔːl/","adj. 总体的","overall performance"),
    ("overcome","/ˌəʊvəˈkʌm/","v. 克服","overcome difficulties"),
    ("overlook","/ˌəʊvəˈlʊk/","v. 忽视","overlook the fact"),
    ("overseas","/ˌəʊvəˈsiːz/","adv./adj. 海外(的)","overseas market"),
    ("owe","/əʊ/","v. 欠，归功于","owe to"),
    ("ownership","/ˈəʊnəʃɪp/","n. 所有权","sense of ownership"),
    ("pace","/peɪs/","n. 速度","keep pace with"),
    ("panel","/ˈpænl/","n. 面板，小组","control panel"),
    ("parallel","/ˈpærəlel/","adj. 平行的","in parallel"),
    ("participate","/pɑːˈtɪsɪpeɪt/","v. 参与","participate in"),
    ("particular","/pəˈtɪkjələr/","adj. 特定的","in particular"),
    ("passion","/ˈpæʃn/","n. 激情","passion for"),
    ("passive","/ˈpæsɪv/","adj. 被动的","passive voice"),
    ("patent","/ˈpætnt/","n. 专利","patent application"),
    ("pension","/ˈpenʃn/","n. 养老金","pension fund"),
    ("perceive","/pəˈsiːv/","v. 感知","perceive as"),
    ("percentage","/pəˈsentɪdʒ/","n. 百分比","small percentage"),
    ("permanent","/ˈpɜːmənənt/","adj. 永久的","permanent resident"),
    ("permit","/pəˈmɪt/","v. 允许 n. 许可证","permit to"),
    ("persist","/pəˈsɪst/","v. 坚持","persist in"),
    ("personality","/ˌpɜːsəˈnæləti/","n. 个性","strong personality"),
    ("perspective","/pəˈspektɪv/","n. 观点","from a perspective"),
    ("phenomenon","/fɪˈnɒmɪnən/","n. 现象","natural phenomenon"),
    ("philosophy","/fɪˈlɒsəfi/","n. 哲学","life philosophy"),
    ("physical","/ˈfɪzɪkl/","adj. 身体的，物理的","physical exercise"),
    ("pioneer","/ˌpaɪəˈnɪər/","n. 先驱 v. 开拓","pioneer spirit"),
    ("pledge","/pledʒ/","n./v. 保证","take a pledge"),
    ("policy","/ˈpɒləsi/","n. 政策","foreign policy"),
    ("pollution","/pəˈluːʃn/","n. 污染","air pollution"),
    ("portion","/ˈpɔːʃn/","n. 部分","a large portion"),
    ("pose","/pəʊz/","v. 造成，摆姿势","pose a threat"),
    ("positive","/ˈpɒzətɪv/","adj. 积极的","positive attitude"),
    ("possess","/pəˈzes/","v. 拥有","possess skills"),
    ("potential","/pəˈtenʃl/","adj. 潜在的 n. 潜力","great potential"),
    ("poverty","/ˈpɒvəti/","n. 贫穷","poverty line"),
    ("precaution","/prɪˈkɔːʃn/","n. 预防措施","take precautions"),
    ("preference","/ˈprefrəns/","n. 偏爱","personal preference"),
    ("prejudice","/ˈpredʒədɪs/","n. 偏见","racial prejudice"),
    ("presence","/ˈprezns/","n. 出席，存在","in the presence of"),
    ("preserve","/prɪˈzɜːv/","v. 保护","preserve history"),
    ("pressure","/ˈpreʃər/","n. 压力","under pressure"),
    ("presumably","/prɪˈzjuːməbli/","adv. 大概","presumably correct"),
    ("prevail","/prɪˈveɪl/","v. 盛行","prevail over"),
    ("previous","/ˈpriːviəs/","adj. 以前的","previous experience"),
    ("pride","/praɪd/","n. 骄傲 v. 自豪","take pride in"),
    ("primary","/ˈpraɪməri/","adj. 主要的，初级的","primary school"),
    ("prime","/praɪm/","adj. 首要的","prime minister"),
    ("principle","/ˈprɪnsəpl/","n. 原则","in principle"),
    ("prior","/ˈpraɪər/","adj. 先前的","prior to"),
    ("priority","/praɪˈɒrəti/","n. 优先","top priority"),
    ("procedure","/prəˈsiːdʒər/","n. 程序","standard procedure"),
    ("proceed","/prəˈsiːd/","v. 继续","proceed with"),
    ("process","/ˈprəʊses/","n. 过程 v. 处理","in the process"),
    ("profession","/prəˈfeʃn/","n. 职业","medical profession"),
    ("professional","/prəˈfeʃənl/","adj. 专业的","professional service"),
    ("profit","/ˈprɒfɪt/","n. 利润 v. 受益","make a profit"),
    ("profound","/prəˈfaʊnd/","adj. 深刻的","profound impact"),
    ("prohibit","/prəˈhɪbɪt/","v. 禁止","strictly prohibit"),
    ("prominent","/ˈprɒmɪnənt/","adj. 突出的","prominent figure"),
    ("promote","/prəˈməʊt/","v. 促进，提升","promote growth"),
    ("promotion","/prəˈməʊʃn/","n. 晋升","sales promotion"),
    ("proof","/pruːf/","n. 证据","proof of identity"),
    ("property","/ˈprɒpəti/","n. 财产","intellectual property"),
    ("proportion","/prəˈpɔːʃn/","n. 比例","in proportion to"),
    ("proposal","/prəˈpəʊzl/","n. 提议","make a proposal"),
    ("propose","/prəˈpəʊz/","v. 提议","propose a plan"),
    ("prospect","/ˈprɒspekt/","n. 前景","job prospects"),
    ("prosperity","/prɒˈsperəti/","n. 繁荣","economic prosperity"),
    ("protest","/ˈprəʊtest/","n./v. 抗议","protest against"),
    ("provision","/prəˈvɪʒn/","n. 供应，条款","make provision for"),
    ("publication","/ˌpʌblɪˈkeɪʃn/","n. 出版(物)","scientific publication"),
    ("publish","/ˈpʌblɪʃ/","v. 出版","publish a book"),
    ("purchase","/ˈpɜːtʃəs/","v./n. 购买","purchase online"),
    ("pursue","/pəˈsjuː/","v. 追求","pursue a dream"),
    ("qualification","/ˌkwɒlɪfɪˈkeɪʃn/","n. 资格","academic qualification"),
    ("quality","/ˈkwɒləti/","n. 质量","high quality"),
    ("quantity","/ˈkwɒntəti/","n. 数量","large quantity"),
    ("racial","/ˈreɪʃl/","adj. 种族的","racial discrimination"),
    ("radical","/ˈrædɪkl/","adj. 根本的，激进的","radical change"),
    ("range","/reɪndʒ/","n. 范围 v. 变化","wide range"),
    ("rank","/ræŋk/","n. 等级 v. 排列","rank first"),
    ("rapid","/ˈræpɪd/","adj. 迅速的","rapid growth"),
    ("rarely","/ˈreəli/","adv. 很少","rarely seen"),
    ("rate","/reɪt/","n. 比率 v. 评价","interest rate"),
    ("rational","/ˈræʃnəl/","adj. 理性的","rational decision"),
    ("react","/riˈækt/","v. 反应","react to"),
    ("realistic","/ˌriːəˈlɪstɪk/","adj. 现实的","realistic goal"),
    ("reality","/riˈæləti/","n. 现实","in reality"),
    ("reasonable","/ˈriːznəbl/","adj. 合理的","reasonable price"),
    ("recall","/rɪˈkɔːl/","v./n. 回忆","recall the past"),
    ("recession","/rɪˈseʃn/","n. 衰退","economic recession"),
    ("recognition","/ˌrekəɡˈnɪʃn/","n. 认可","facial recognition"),
    ("recommend","/ˌrekəˈmend/","v. 推荐","highly recommend"),
    ("recover","/rɪˈkʌvər/","v. 恢复","recover from"),
    ("reduction","/rɪˈdʌkʃn/","n. 减少","cost reduction"),
    ("refer","/rɪˈfɜːr/","v. 参考","refer to"),
    ("reference","/ˈrefrəns/","n. 参考","for reference"),
    ("reflect","/rɪˈflekt/","v. 反映","reflect on"),
    ("reform","/rɪˈfɔːm/","v./n. 改革","economic reform"),
    ("regarding","/rɪˈɡɑːdɪŋ/","prep. 关于","regarding this matter"),
    ("regardless","/rɪˈɡɑːdləs/","adv. 不管怎样","regardless of"),
    ("region","/ˈriːdʒən/","n. 地区","in the region"),
    ("register","/ˈredʒɪstər/","v./n. 登记","register for"),
    ("regulate","/ˈreɡjuleɪt/","v. 管理","regulate temperature"),
    ("regulation","/ˌreɡjuˈleɪʃn/","n. 法规","government regulation"),
    ("reinforce","/ˌriːɪnˈfɔːs/","v. 加强","reinforce the idea"),
    ("reject","/rɪˈdʒekt/","v. 拒绝","reject an offer"),
    ("relate","/rɪˈleɪt/","v. 联系","relate to"),
    ("release","/rɪˈliːs/","v./n. 释放，发布","press release"),
    ("relevant","/ˈreləvənt/","adj. 相关的","relevant information"),
    ("reliable","/rɪˈlaɪəbl/","adj. 可靠的","reliable source"),
    ("relief","/rɪˈliːf/","n. 减轻","pain relief"),
    ("rely","/rɪˈlaɪ/","v. 依赖","rely on"),
    ("remark","/rɪˈmɑːk/","n./v. 评论","make a remark"),
    ("remarkable","/rɪˈmɑːkəbl/","adj. 非凡的","remarkable achievement"),
    ("remedy","/ˈremədi/","n. 补救办法","legal remedy"),
    ("remote","/rɪˈməʊt/","adj. 遥远的","remote control"),
    ("render","/ˈrendər/","v. 使成为","render service"),
    ("represent","/ˌreprɪˈzent/","v. 代表","represent interests"),
    ("reputation","/ˌrepjuˈteɪʃn/","n. 声誉","good reputation"),
    ("request","/rɪˈkwest/","n./v. 请求","make a request"),
    ("require","/rɪˈkwaɪər/","v. 需要","require attention"),
    ("requirement","/rɪˈkwaɪəmənt/","n. 要求","meet requirements"),
    ("rescue","/ˈreskjuː/","v./n. 营救","rescue team"),
    ("resemble","/rɪˈzembl/","v. 相似","resemble each other"),
    ("reserve","/rɪˈzɜːv/","v. 预订 n. 储备","reserve a table"),
    ("resist","/rɪˈzɪst/","v. 抵抗","resist temptation"),
    ("resolve","/rɪˈzɒlv/","v. 解决","resolve conflicts"),
    ("resort","/rɪˈzɔːt/","v. 诉诸 n. 度假胜地","resort to"),
    ("resource","/rɪˈzɔːs/","n. 资源","human resource"),
    ("respond","/rɪˈspɒnd/","v. 回应","respond to"),
    ("response","/rɪˈspɒns/","n. 回应","in response to"),
    ("responsibility","/rɪˌspɒnsəˈbɪləti/","n. 责任","take responsibility"),
    ("restore","/rɪˈstɔːr/","v. 恢复","restore order"),
    ("restrict","/rɪˈstrɪkt/","v. 限制","restrict access"),
    ("reveal","/rɪˈviːl/","v. 揭示","reveal secrets"),
    ("revenue","/ˈrevənjuː/","n. 收入","tax revenue"),
    ("revolution","/ˌrevəˈluːʃn/","n. 革命","industrial revolution"),
    ("reward","/rɪˈwɔːd/","n. 奖赏 v. 报答","reward for"),
    ("risk","/rɪsk/","n. 风险 v. 冒险","take a risk"),
    ("rival","/ˈraɪvl/","n. 对手 v. 竞争","rival company"),
    ("role","/rəʊl/","n. 角色","play a role"),
    ("routine","/ruːˈtiːn/","n. 常规","daily routine"),
    ("rural","/ˈrʊərəl/","adj. 农村的","rural area"),
    ("sacrifice","/ˈsækrɪfaɪs/","n./v. 牺牲","make a sacrifice"),
    ("salary","/ˈsæləri/","n. 薪水","annual salary"),
    ("satisfaction","/ˌsætɪsˈfækʃn/","n. 满意","customer satisfaction"),
    ("scale","/skeɪl/","n. 规模","on a large scale"),
    ("scan","/skæn/","v./n. 扫描","scan through"),
    ("schedule","/ˈʃedjuːl/","n. 时间表 v. 安排","on schedule"),
    ("scheme","/skiːm/","n. 方案","color scheme"),
    ("scholar","/ˈskɒlər/","n. 学者","visiting scholar"),
    ("scholarship","/ˈskɒləʃɪp/","n. 奖学金","win a scholarship"),
    ("scope","/skəʊp/","n. 范围","within the scope"),
    ("sector","/ˈsektər/","n. 部门","private sector"),
    ("secure","/sɪˈkjʊər/","adj. 安全的 v. 获得","secure job"),
    ("security","/sɪˈkjʊərəti/","n. 安全","national security"),
    ("senior","/ˈsiːniər/","adj. 高级的 n. 年长者","senior manager"),
    ("sensitive","/ˈsensətɪv/","adj. 敏感的","sensitive information"),
    ("sequence","/ˈsiːkwəns/","n. 顺序","in sequence"),
    ("session","/ˈseʃn/","n. 会议","training session"),
    ("severe","/sɪˈvɪər/","adj. 严重的","severe weather"),
    ("shelter","/ˈʃeltər/","n. 庇护所","take shelter"),
    ("shift","/ʃɪft/","v./n. 转移，轮班","night shift"),
    ("shortage","/ˈʃɔːtɪdʒ/","n. 短缺","water shortage"),
    ("significant","/sɪɡˈnɪfɪkənt/","adj. 重要的","significant role"),
    ("similar","/ˈsɪmələr/","adj. 相似的","similar to"),
    ("simplify","/ˈsɪmplɪfaɪ/","v. 简化","simplify the process"),
    ("site","/saɪt/","n. 地点","construction site"),
    ("sole","/səʊl/","adj. 唯一的","sole purpose"),
    ("solid","/ˈsɒlɪd/","adj. 固体的 n. 固体","solid foundation"),
    ("solution","/səˈluːʃn/","n. 解决方案","find a solution"),
    ("source","/sɔːs/","n. 来源","energy source"),
    ("span","/spæn/","n. 跨度 v. 跨越","life span"),
    ("specialist","/ˈspeʃəlɪst/","n. 专家","heart specialist"),
    ("species","/ˈspiːʃiːz/","n. 物种","endangered species"),
    ("specific","/spəˈsɪfɪk/","adj. 具体的","specific area"),
    ("spiritual","/ˈspɪrɪtʃuəl/","adj. 精神的","spiritual life"),
    ("sponsor","/ˈspɒnsər/","v./n. 赞助","sponsor an event"),
    ("stable","/ˈsteɪbl/","adj. 稳定的","stable economy"),
    ("staff","/stɑːf/","n. 员工","staff meeting"),
    ("standard","/ˈstændəd/","n. 标准 adj. 标准的","high standard"),
    ("status","/ˈsteɪtəs/","n. 地位，状态","social status"),
    ("steady","/ˈstedi/","adj. 稳定的","steady growth"),
    ("stem","/stem/","n. 茎 v. 起源于","stem from"),
    ("stimulate","/ˈstɪmjuleɪt/","v. 刺激","stimulate growth"),
    ("stock","/stɒk/","n. 库存，股票","stock market"),
    ("strategy","/ˈstrætədʒi/","n. 策略","marketing strategy"),
    ("strengthen","/ˈstreŋθn/","v. 加强","strengthen ties"),
    ("structure","/ˈstrʌktʃər/","n. 结构","social structure"),
    ("submit","/səbˈmɪt/","v. 提交","submit a report"),
    ("substance","/ˈsʌbstəns/","n. 物质","chemical substance"),
    ("substitute","/ˈsʌbstɪtjuːt/","n. 替代品 v. 替代","substitute for"),
    ("sufficient","/səˈfɪʃnt/","adj. 足够的","sufficient evidence"),
    ("summary","/ˈsʌməri/","n. 摘要","in summary"),
    ("superior","/suːˈpɪəriər/","adj. 优越的","superior quality"),
    ("supplement","/ˈsʌplɪment/","n. 补充 v. 增补","dietary supplement"),
    ("supreme","/suːˈpriːm/","adj. 最高的","supreme court"),
    ("surplus","/ˈsɜːpləs/","n. 过剩 adj. 多余的","budget surplus"),
    ("survey","/ˈsɜːveɪ/","n./v. 调查","conduct a survey"),
    ("survival","/səˈvaɪvl/","n. 幸存","survival skills"),
    ("suspect","/səˈspekt/","v. 怀疑 n. 嫌疑人","suspect of"),
    ("suspend","/səˈspend/","v. 暂停","suspend operations"),
    ("sustain","/səˈsteɪn/","v. 维持","sustain growth"),
    ("symbol","/ˈsɪmbl/","n. 象征","status symbol"),
    ("symptom","/ˈsɪmptəm/","n. 症状","common symptom"),
    ("target","/ˈtɑːɡɪt/","n. 目标 v. 瞄准","target audience"),
    ("technique","/tekˈniːk/","n. 技术","management technique"),
    ("temporary","/ˈtemprəri/","adj. 暂时的","temporary solution"),
    ("tendency","/ˈtendənsi/","n. 趋势","have a tendency to"),
    ("terminal","/ˈtɜːmɪnl/","n. 终点站 adj. 终端的","airport terminal"),
    ("territory","/ˈterətri/","n. 领土","new territory"),
    ("theme","/θiːm/","n. 主题","main theme"),
    ("theory","/ˈθɪəri/","n. 理论","in theory"),
    ("therapy","/ˈθerəpi/","n. 治疗","physical therapy"),
    ("thorough","/ˈθʌrə/","adj. 彻底的","thorough investigation"),
    ("threat","/θret/","n. 威胁","pose a threat"),
    ("thrive","/θraɪv/","v. 繁荣","thrive on"),
    ("tolerate","/ˈtɒləreɪt/","v. 容忍","tolerate behavior"),
    ("tone","/təʊn/","n. 语气","tone of voice"),
    ("topic","/ˈtɒpɪk/","n. 话题","hot topic"),
    ("tough","/tʌf/","adj. 艰苦的","tough decision"),
    ("trace","/treɪs/","v. 追踪 n. 痕迹","trace back to"),
    ("tradition","/trəˈdɪʃn/","n. 传统","cultural tradition"),
    ("transaction","/trænˈzækʃn/","n. 交易","business transaction"),
    ("transfer","/trænsˈfɜːr/","v./n. 转移","transfer money"),
    ("transform","/trænsˈfɔːm/","v. 改变","transform into"),
    ("tremendous","/trəˈmendəs/","adj. 巨大的","tremendous effort"),
    ("trend","/trend/","n. 趋势","current trend"),
    ("trial","/ˈtraɪəl/","n. 审判，试验","clinical trial"),
    ("triumph","/ˈtraɪʌmf/","n. 胜利","moment of triumph"),
    ("typical","/ˈtɪpɪkl/","adj. 典型的","typical example"),
    ("ultimate","/ˈʌltɪmət/","adj. 最终的","ultimate goal"),
    ("undergo","/ˌʌndəˈɡəʊ/","v. 经历","undergo surgery"),
    ("undermine","/ˌʌndəˈmaɪn/","v. 削弱","undermine confidence"),
    ("undertake","/ˌʌndəˈteɪk/","v. 承担","undertake a task"),
    ("unemployment","/ˌʌnɪmˈplɔɪmənt/","n. 失业","unemployment rate"),
    ("unique","/juˈniːk/","adj. 独特的","unique feature"),
    ("urban","/ˈɜːbən/","adj. 城市的","urban area"),
    ("urge","/ɜːdʒ/","v. 敦促 n. 强烈欲望","urge to do"),
    ("utility","/juːˈtɪləti/","n. 公用事业","public utility"),
    ("utilize","/ˈjuːtəlaɪz/","v. 利用","utilize resources"),
    ("vacant","/ˈveɪkənt/","adj. 空的，空缺的","vacant position"),
    ("vain","/veɪn/","adj. 徒劳的","in vain"),
    ("valid","/ˈvælɪd/","adj. 有效的","valid reason"),
    ("vanish","/ˈvænɪʃ/","v. 消失","vanish into thin air"),
    ("variable","/ˈveəriəbl/","adj. 可变的 n. 变量","variable costs"),
    ("vast","/vɑːst/","adj. 巨大的","vast majority"),
    ("venture","/ˈventʃər/","n. 风险项目 v. 冒险","joint venture"),
    ("verify","/ˈverɪfaɪ/","v. 核实","verify information"),
    ("version","/ˈvɜːʃn/","n. 版本","latest version"),
    ("vessel","/ˈvesl/","n. 船，容器","blood vessel"),
    ("victim","/ˈvɪktɪm/","n. 受害者","fall victim to"),
    ("violate","/ˈvaɪəleɪt/","v. 违反","violate rules"),
    ("violence","/ˈvaɪələns/","n. 暴力","domestic violence"),
    ("virtual","/ˈvɜːtʃuəl/","adj. 虚拟的","virtual reality"),
    ("virtue","/ˈvɜːtʃuː/","n. 美德","by virtue of"),
    ("visible","/ˈvɪzəbl/","adj. 可见的","visible sign"),
    ("vision","/ˈvɪʒn/","n. 视力，愿景","have a vision"),
    ("visual","/ˈvɪʒuəl/","adj. 视觉的","visual arts"),
    ("vital","/ˈvaɪtl/","adj. 至关重要的","vital role"),
    ("vivid","/ˈvɪvɪd/","adj. 生动的","vivid memory"),
    ("volume","/ˈvɒljuːm/","n. 音量，容量","sales volume"),
    ("voluntary","/ˈvɒləntri/","adj. 自愿的","voluntary work"),
    ("volunteer","/ˌvɒlənˈtɪər/","v./n. 志愿","volunteer to help"),
    ("wage","/weɪdʒ/","n. 工资 v. 发动","minimum wage"),
    ("wander","/ˈwɒndər/","v. 漫步","wander around"),
    ("wealthy","/ˈwelθi/","adj. 富有的","wealthy family"),
    ("weapon","/ˈwepən/","n. 武器","nuclear weapon"),
    ("whereas","/ˌweərˈæz/","conj. 然而","whereas previously"),
    ("withdraw","/wɪðˈdrɔː/","v. 撤回","withdraw from"),
    ("withstand","/wɪðˈstænd/","v. 承受","withstand pressure"),
    ("yield","/jiːld/","v. 产生，屈服","yield results"),
]
print(f"Bank: {len(CET4_BANK)} words")

# ===== 4. 逐天计算词汇 =====
def day_key(offset):
    d = START_DATE + datetime.timedelta(days=offset)
    return '%d-%02d-%02d' % (d.year, d.month, d.day)

# Day 0: 固定前 80
pool = list(all_entries)  # copy of original entries (strings like '{w:"abandon",...}')
learned_names = set()
daily_entries = []  # will hold [day0_entries, day1_entries, ...]

day0 = pool[:80]
for e in day0: learned_names.add(wname(e))
daily_entries.append(day0)

# Day 1: exclude day0, seedRandom("2026-05-22"), take 100
avail = [e for e in pool if wname(e) not in learned_names]
rng = seededRandom('2026-05-22')
for i in range(len(avail)-1, 0, -1):
    j = int(rng() * (i+1)); avail[i], avail[j] = avail[j], avail[i]
day1 = avail[:100]
for e in day1: learned_names.add(wname(e))
daily_entries.append(day1)

# Day 2: same logic
avail = [e for e in pool if wname(e) not in learned_names]
rng = seededRandom('2026-05-23')
for i in range(len(avail)-1, 0, -1):
    j = int(rng() * (i+1)); avail[i], avail[j] = avail[j], avail[i]
day2 = avail[:100]
for e in day2: learned_names.add(wname(e))
daily_entries.append(day2)

# Days 3+: 随机洗牌银行 → 补词到300 → 再洗池 → 取100
# 不用 bank_idx 顺序取，而是每天用 seedsRandom 洗牌银行，从全银行随机补词
def bank_to_entry(t):
    return '{w:"%s",p:"%s",m:"%s",c:"%s"}' % t

bank_as_entries = [bank_to_entry(t) for t in CET4_BANK]

for day_idx in range(3, todayIndex + 1):
    # 当前池：原词中未学的 + 银行词中未学的
    current_orig = [e.strip() for e in pool if wname(e) not in learned_names]
    current_bank = [e for t, e in zip(CET4_BANK, bank_as_entries) if t[0] not in learned_names]
    
    # 洗牌银行部分（用当天 seed，保证每天银行取词顺序不同）
    day_rng = seededRandom(day_key(day_idx))
    for i in range(len(current_bank)-1, 0, -1):
        j = int(day_rng() * (i+1))
        current_bank[i], current_bank[j] = current_bank[j], current_bank[i]
    
    # 合并池
    current_pool_strs = current_orig + current_bank
    
    # 检查池大小（应该 >= 300，因为银行有870词，减去已学的最多500，还剩370+）
    if len(current_pool_strs) < 300:
        print(f"WARNING: Day {day_idx} pool only {len(current_pool_strs)} words (< 300)!")
    
    # 洗牌整个池，取 100
    for i in range(len(current_pool_strs)-1, 0, -1):
        j = int(day_rng() * (i+1))
        current_pool_strs[i], current_pool_strs[j] = current_pool_strs[j], current_pool_strs[i]
    
    day_entries = current_pool_strs[:100]
    for e in day_entries:
        learned_names.add(wname(e))
    daily_entries.append(day_entries)
    print(f"Day {day_idx}: pool={len(current_pool_strs)} → 100 words ✓")

print(f"Total days computed: {len(daily_entries)}")
print(f"Total learned: {len(learned_names)}")

# ===== 5. 构建 DAILY_WORDS + 新 WORD_POOL =====
daily_js = 'const DAILY_WORDS = [\n'
for i, day_entries in enumerate(daily_entries):
    arr = '[' + ','.join(e.strip() if isinstance(e, str) else e for e in day_entries) + ']'
    daily_js += '  ' + arr
    if i < len(daily_entries) - 1:
        daily_js += ',\n'
    else:
        daily_js += '\n'
daily_js += '];\n'

html = html.replace('<script>', '<script>\n' + daily_js)
print("DAILY_WORDS injected")

# ===== 6. 替换 WORD_POOL 为新池（仅剩未学词）=====
remaining_orig = [e.strip() for e in pool if wname(e) not in learned_names]
remaining_bank = [bank_to_entry(t) for t in CET4_BANK if t[0] not in learned_names]
new_pool_entries = remaining_orig + remaining_bank

old_pool = m.group(0)
new_pool_decl = 'const WORD_POOL = [\n' + ',\n'.join('  ' + e for e in new_pool_entries) + '\n];'
html = html.replace(old_pool, new_pool_decl)
print(f"WORD_POOL replaced: {len(new_pool_entries)} fresh words remaining")

# ===== 7. 替换 getDailyVocab =====
s = html.find('function getDailyVocab')
d = 0; fs = False
for i in range(s, len(html)):
    if html[i] == '{': d += 1; fs = True
    elif html[i] == '}': d -= 1
    if fs and d == 0: e = i + 1; break

new_func = '''function getDailyVocab(d) {
  var idx = dayIndex(d);
  return DAILY_WORDS[idx];
}'''
html = html.replace(html[s:e], new_func)
print("getDailyVocab → returns DAILY_WORDS[idx]")

# ===== 8. 验证 =====
s2 = html.find('<script>'); e2 = html.rfind('</script>')
js = html[s2:e2]
ob = js.count('{'); cb = js.count('}')
print(f"JS braces: {ob}/{cb} balanced={ob==cb}")
print(f"Size: {len(html)} bytes")

with open(PATH, 'w', encoding='utf-8') as f:
    f.write(html)
print("Done!")
