"""
smart_expand_vocab.py — 智能增量词汇扩充
每日检查：所需 = 80 + 100 × dayIndex
缺多少补多少，从 CET-4 高频词库取，不重复
"""
import re, datetime

PATH = r'C:\Users\24470\WorkBuddy\2026-05-21-16-18-52\cet4-study\index.html'

with open(PATH, 'r', encoding='utf-8') as f:
    html = f.read()

# ============================================================
# 1. 计算所需词汇量
# ============================================================
START_DATE = datetime.date(2026, 5, 21)
now = datetime.datetime.now()
if now.hour < 9:
    effective = (now - datetime.timedelta(days=1)).date()
else:
    effective = now.date()
dayIndex = (effective - START_DATE).days
needed_total = 80 + 100 * max(dayIndex, 0)

print(f"Today: {effective} (dayIndex={dayIndex})")
print(f"Needed vocab: {needed_total}")

# ============================================================
# 2. 统计当前词库
# ============================================================
pool_match = re.search(r'const WORD_POOL\s*=\s*\[(.*?)\];', html, re.DOTALL)
if not pool_match:
    print("ERROR: WORD_POOL not found!")
    import sys; sys.exit(1)

pool_body = pool_match.group(1)
current_words = re.findall(r'w:"([^"]+)"', pool_body)
current_count = len(current_words)
existing_set = set(current_words)
print(f"Current pool: {current_count} words")

deficit = needed_total - current_count
if deficit <= 0:
    print(f"No expansion needed (pool {current_count} ≥ needed {needed_total})")
    import sys; sys.exit(0)
print(f"Deficit: {deficit} — adding {deficit} new words")

# ============================================================
# 3. CET-4 常考高频词汇库 (~1800词，按字母序，确保日复一日增量稳定)
# ============================================================
CET4_BANK = [
    {w:"abnormal",p:"/æbˈnɔːml/",m:"adj. 反常的",c:"abnormal behavior"},
    {w:"aboard",p:"/əˈbɔːd/",m:"adv./prep. 在船上，在车上",c:"go aboard"},
    {w:"abolish",p:"/əˈbɒlɪʃ/",m:"v. 废除，取消",c:"abolish slavery"},
    {w:"abortion",p:"/əˈbɔːʃn/",m:"n. 流产，堕胎",c:"illegal abortion"},
    {w:"abroad",p:"/əˈbrɔːd/",m:"adv. 到国外",c:"study abroad"},
    {w:"absence",p:"/ˈæbsəns/",m:"n. 缺席，不在",c:"in the absence of"},
    {w:"absolute",p:"/ˈæbsəluːt/",m:"adj. 绝对的，完全的",c:"absolute power"},
    {w:"absorb",p:"/əbˈzɔːb/",m:"v. 吸收，吸引",c:"be absorbed in"},
    {w:"abstract",p:"/ˈæbstrækt/",m:"adj. 抽象的 n. 摘要",c:"abstract concept"},
    {w:"absurd",p:"/əbˈsɜːd/",m:"adj. 荒谬的",c:"absurd idea"},
    {w:"abundant",p:"/əˈbʌndənt/",m:"adj. 丰富的",c:"abundant resources"},
    {w:"academic",p:"/ˌækəˈdemɪk/",m:"adj. 学术的",c:"academic research"},
    {w:"accelerate",p:"/əkˈseləreɪt/",m:"v. 加速",c:"accelerate growth"},
    {w:"access",p:"/ˈækses/",m:"n. 通道 v. 进入",c:"have access to"},
    {w:"accommodate",p:"/əˈkɒmədeɪt/",m:"v. 容纳，适应",c:"accommodate needs"},
    {w:"accompany",p:"/əˈkʌmpəni/",m:"v. 陪伴，伴随",c:"accompany by"},
    {w:"accomplish",p:"/əˈkɒmplɪʃ/",m:"v. 完成，实现",c:"accomplish goals"},
    {w:"account",p:"/əˈkaʊnt/",m:"n. 账户 v. 解释",c:"take into account"},
    {w:"accumulate",p:"/əˈkjuːmjəleɪt/",m:"v. 积累",c:"accumulate wealth"},
    {w:"accurate",p:"/ˈækjərət/",m:"adj. 精确的",c:"accurate data"},
    {w:"accuse",p:"/əˈkjuːz/",m:"v. 指控，指责",c:"accuse of"},
    {w:"achieve",p:"/əˈtʃiːv/",m:"v. 达到，实现",c:"achieve success"},
    {w:"achievement",p:"/əˈtʃiːvmənt/",m:"n. 成就，成绩",c:"academic achievement"},
    {w:"acknowledge",p:"/əkˈnɒlɪdʒ/",m:"v. 承认，确认",c:"acknowledge receipt"},
    {w:"acquaintance",p:"/əˈkweɪntəns/",m:"n. 熟人",c:"make acquaintance"},
    {w:"acquire",p:"/əˈkwaɪər/",m:"v. 获得，习得",c:"acquire skills"},
    {w:"adapt",p:"/əˈdæpt/",m:"v. 适应，改编",c:"adapt to"},
    {w:"adequate",p:"/ˈædɪkwət/",m:"adj. 足够的",c:"adequate supply"},
    {w:"adjust",p:"/əˈdʒʌst/",m:"v. 调整，适应",c:"adjust to"},
    {w:"administration",p:"/ədˌmɪnɪˈstreɪʃn/",m:"n. 管理，行政",c:"public administration"},
    {w:"admire",p:"/ədˈmaɪər/",m:"v. 钦佩",c:"admire for"},
    {w:"admission",p:"/ədˈmɪʃn/",m:"n. 准许进入，承认",c:"admission ticket"},
    {w:"adopt",p:"/əˈdɒpt/",m:"v. 采用，收养",c:"adopt a policy"},
    {w:"advanced",p:"/ədˈvɑːnst/",m:"adj. 先进的",c:"advanced technology"},
    {w:"advantage",p:"/ədˈvɑːntɪdʒ/",m:"n. 优势",c:"take advantage of"},
    {w:"advertise",p:"/ˈædvətaɪz/",m:"v. 做广告",c:"advertise for"},
    {w:"advocate",p:"/ˈædvəkeɪt/",m:"v. 倡导 n. 倡导者",c:"advocate for"},
    {w:"affair",p:"/əˈfeər/",m:"n. 事务，事件",c:"foreign affairs"},
    {w:"affect",p:"/əˈfekt/",m:"v. 影响，感动",c:"adversely affect"},
    {w:"afford",p:"/əˈfɔːd/",m:"v. 负担得起",c:"can't afford"},
    {w:"agency",p:"/ˈeɪdʒənsi/",m:"n. 代理机构",c:"travel agency"},
    {w:"aggressive",p:"/əˈɡresɪv/",m:"adj. 好斗的，进取的",c:"aggressive behavior"},
    {w:"agree",p:"/əˈɡriː/",m:"v. 同意",c:"agree with"},
    {w:"aid",p:"/eɪd/",m:"n./v. 帮助",c:"first aid"},
    {w:"aim",p:"/eɪm/",m:"n. 目标 v. 瞄准",c:"aim at"},
    {w:"alarm",p:"/əˈlɑːm/",m:"n. 警报，闹钟",c:"fire alarm"},
    {w:"alcohol",p:"/ˈælkəhɒl/",m:"n. 酒精",c:"alcohol abuse"},
    {w:"alert",p:"/əˈlɜːt/",m:"adj. 警觉的 v. 警告",c:"stay alert"},
    {w:"allocate",p:"/ˈæləkeɪt/",m:"v. 分配",c:"allocate resources"},
    {w:"allowance",p:"/əˈlaʊəns/",m:"n. 津贴",c:"make allowance for"},
    {w:"alongside",p:"/əˌlɒŋˈsaɪd/",m:"prep. 在…旁边",c:"work alongside"},
    {w:"alter",p:"/ˈɔːltər/",m:"v. 改变",c:"alter the course"},
    {w:"alternative",p:"/ɔːlˈtɜːnətɪv/",m:"adj. 替代的 n. 替代品",c:"alternative approach"},
    {w:"amaze",p:"/əˈmeɪz/",m:"v. 使惊奇",c:"be amazed at"},
    {w:"ambition",p:"/æmˈbɪʃn/",m:"n. 雄心",c:"achieve ambition"},
    {w:"amount",p:"/əˈmaʊnt/",m:"n. 数量",c:"a large amount of"},
    {w:"amuse",p:"/əˈmjuːz/",m:"v. 逗乐",c:"amuse oneself"},
    {w:"analysis",p:"/əˈnæləsɪs/",m:"n. 分析",c:"data analysis"},
    {w:"analyze",p:"/ˈænəlaɪz/",m:"v. 分析",c:"analyze data"},
    {w:"ancestor",p:"/ˈænsestər/",m:"n. 祖先",c:"common ancestor"},
    {w:"anchor",p:"/ˈæŋkər/",m:"n. 锚 v. 固定",c:"news anchor"},
    {w:"ancient",p:"/ˈeɪnʃənt/",m:"adj. 古代的",c:"ancient times"},
    {w:"angle",p:"/ˈæŋɡl/",m:"n. 角度",c:"from another angle"},
    {w:"anniversary",p:"/ˌænɪˈvɜːsəri/",m:"n. 周年纪念日",c:"wedding anniversary"},
    {w:"announce",p:"/əˈnaʊns/",m:"v. 宣布",c:"announce plans"},
    {w:"annual",p:"/ˈænjuəl/",m:"adj. 年度的",c:"annual report"},
    {w:"anticipate",p:"/ænˈtɪsɪpeɪt/",m:"v. 预期",c:"anticipate problems"},
    {w:"anxiety",p:"/æŋˈzaɪəti/",m:"n. 焦虑",c:"anxiety disorder"},
    {w:"apart",p:"/əˈpɑːt/",m:"adv. 分开",c:"apart from"},
    {w:"apology",p:"/əˈpɒlədʒi/",m:"n. 道歉",c:"make an apology"},
    {w:"apparent",p:"/əˈpærənt/",m:"adj. 显然的",c:"apparent reason"},
    {w:"appeal",p:"/əˈpiːl/",m:"v./n. 呼吁，吸引",c:"appeal to"},
    {w:"appetite",p:"/ˈæpɪtaɪt/",m:"n. 胃口",c:"lose appetite"},
    {w:"appliance",p:"/əˈplaɪəns/",m:"n. 电器",c:"household appliance"},
    {w:"applicant",p:"/ˈæplɪkənt/",m:"n. 申请人",c:"job applicant"},
    {w:"apply",p:"/əˈplaɪ/",m:"v. 申请，应用",c:"apply for"},
    {w:"appoint",p:"/əˈpɔɪnt/",m:"v. 任命",c:"appoint a leader"},
    {w:"appointment",p:"/əˈpɔɪntmənt/",m:"n. 约会，任命",c:"make an appointment"},
    {w:"appreciate",p:"/əˈpriːʃieɪt/",m:"v. 欣赏，感激",c:"appreciate help"},
    {w:"approach",p:"/əˈprəʊtʃ/",m:"v./n. 接近，方法",c:"new approach"},
    {w:"appropriate",p:"/əˈprəʊpriət/",m:"adj. 适当的",c:"appropriate behavior"},
    {w:"approve",p:"/əˈpruːv/",m:"v. 批准，赞成",c:"approve of"},
    {w:"architecture",p:"/ˈɑːkɪtektʃər/",m:"n. 建筑学",c:"modern architecture"},
    {w:"argue",p:"/ˈɑːɡjuː/",m:"v. 争论",c:"argue against"},
    {w:"argument",p:"/ˈɑːɡjumənt/",m:"n. 争论，论据",c:"strong argument"},
    {w:"arise",p:"/əˈraɪz/",m:"v. 出现，产生",c:"problems arise"},
    {w:"arrange",p:"/əˈreɪndʒ/",m:"v. 安排",c:"arrange for"},
    {w:"arrest",p:"/əˈrest/",m:"v./n. 逮捕",c:"under arrest"},
    {w:"articulate",p:"/ɑːˈtɪkjuleɪt/",m:"v. 清楚表达",c:"articulate ideas"},
    {w:"artificial",p:"/ˌɑːtɪˈfɪʃl/",m:"adj. 人工的",c:"artificial intelligence"},
    {w:"aspect",p:"/ˈæspekt/",m:"n. 方面",c:"every aspect"},
    {w:"assemble",p:"/əˈsembl/",m:"v. 集合，组装",c:"assemble parts"},
    {w:"assert",p:"/əˈsɜːt/",m:"v. 断言，维护",c:"assert authority"},
    {w:"assess",p:"/əˈses/",m:"v. 评估",c:"assess the situation"},
    {w:"asset",p:"/ˈæset/",m:"n. 资产，优点",c:"valuable asset"},
    {w:"assign",p:"/əˈsaɪn/",m:"v. 分配，指派",c:"assign tasks"},
    {w:"assist",p:"/əˈsɪst/",m:"v. 帮助",c:"assist in"},
    {w:"associate",p:"/əˈsəʊʃieɪt/",m:"v. 联系",c:"associate with"},
    {w:"assume",p:"/əˈsjuːm/",m:"v. 假设，承担",c:"assume responsibility"},
    {w:"assumption",p:"/əˈsʌmpʃn/",m:"n. 假设",c:"make an assumption"},
    {w:"assure",p:"/əˈʃʊər/",m:"v. 使确信，保证",c:"assure safety"},
    {w:"atmosphere",p:"/ˈætməsfɪər/",m:"n. 大气，氛围",c:"friendly atmosphere"},
    {w:"attach",p:"/əˈtætʃ/",m:"v. 附上",c:"attach importance to"},
    {w:"attain",p:"/əˈteɪn/",m:"v. 达到",c:"attain goals"},
    {w:"attempt",p:"/əˈtempt/",m:"n./v. 尝试",c:"attempt to"},
    {w:"attend",p:"/əˈtend/",m:"v. 参加",c:"attend a meeting"},
    {w:"attention",p:"/əˈtenʃn/",m:"n. 注意",c:"pay attention to"},
    {w:"attitude",p:"/ˈætɪtjuːd/",m:"n. 态度",c:"positive attitude"},
    {w:"attract",p:"/əˈtrækt/",m:"v. 吸引",c:"attract attention"},
    {w:"attractive",p:"/əˈtræktɪv/",m:"adj. 有吸引力的",c:"attractive offer"},
    {w:"attribute",p:"/əˈtrɪbjuːt/",m:"v. 归因于 n. 属性",c:"attribute to"},
    {w:"audience",p:"/ˈɔːdiəns/",m:"n. 观众",c:"target audience"},
    {w:"authority",p:"/ɔːˈθɒrəti/",m:"n. 权威，当局",c:"local authority"},
    {w:"automatic",p:"/ˌɔːtəˈmætɪk/",m:"adj. 自动的",c:"automatic system"},
    {w:"available",p:"/əˈveɪləbl/",m:"adj. 可用的",c:"available resources"},
    {w:"avenue",p:"/ˈævənjuː/",m:"n. 大街，途径",c:"explore avenues"},
    {w:"average",p:"/ˈævərɪdʒ/",m:"adj. 平均的 n. 平均数",c:"on average"},
    {w:"avoid",p:"/əˈvɔɪd/",m:"v. 避免",c:"avoid doing"},
    {w:"award",p:"/əˈwɔːd/",m:"n. 奖品 v. 授予",c:"win an award"},
    {w:"aware",p:"/əˈweər/",m:"adj. 意识到的",c:"be aware of"},
    {w:"awful",p:"/ˈɔːfl/",m:"adj. 糟糕的",c:"awful weather"},
    {w:"awkward",p:"/ˈɔːkwəd/",m:"adj. 尴尬的",c:"awkward situation"},
    {w:"backup",p:"/ˈbækʌp/",m:"n. 备份 v. 支持",c:"data backup"},
    {w:"backward",p:"/ˈbækwəd/",m:"adj. 落后的 adv. 向后",c:"backward area"},
    {w:"balance",p:"/ˈbæləns/",m:"n. 平衡 v. 平衡",c:"keep balance"},
    {w:"ban",p:"/bæn/",m:"v./n. 禁止",c:"ban on"},
    {w:"bankrupt",p:"/ˈbæŋkrʌpt/",m:"adj. 破产的",c:"go bankrupt"},
    {w:"barely",p:"/ˈbeəli/",m:"adv. 几乎不",c:"barely enough"},
    {w:"bargain",p:"/ˈbɑːɡɪn/",m:"n. 便宜货 v. 讨价还价",c:"bargain price"},
    {w:"barrier",p:"/ˈbæriər/",m:"n. 障碍",c:"language barrier"},
    {w:"battle",p:"/ˈbætl/",m:"n./v. 战斗",c:"battle against"},
    {w:"bear",p:"/beər/",m:"v. 承受 n. 熊",c:"bear in mind"},
    {w:"behalf",p:"/bɪˈhɑːf/",m:"n. 利益，代表",c:"on behalf of"},
    {w:"behave",p:"/bɪˈheɪv/",m:"v. 表现",c:"behave well"},
    {w:"being",p:"/ˈbiːɪŋ/",m:"n. 生物，存在",c:"human being"},
    {w:"belief",p:"/bɪˈliːf/",m:"n. 信念",c:"beyond belief"},
    {w:"beloved",p:"/bɪˈlʌvd/",m:"adj. 心爱的",c:"beloved wife"},
    {w:"beneath",p:"/bɪˈniːθ/",m:"prep. 在…下方",c:"beneath the surface"},
    {w:"beneficial",p:"/ˌbenɪˈfɪʃl/",m:"adj. 有益的",c:"beneficial to health"},
    {w:"benefit",p:"/ˈbenɪfɪt/",m:"n. 利益 v. 受益",c:"benefit from"},
    {w:"betray",p:"/bɪˈtreɪ/",m:"v. 背叛，出卖",c:"betray trust"},
    {w:"billion",p:"/ˈbɪljən/",m:"n. 十亿",c:"billions of"},
    {w:"bind",p:"/baɪnd/",m:"v. 捆绑，约束",c:"bind together"},
    {w:"biology",p:"/baɪˈɒlədʒi/",m:"n. 生物学",c:"molecular biology"},
    {w:"bitter",p:"/ˈbɪtər/",m:"adj. 苦的",c:"bitter experience"},
    {w:"blade",p:"/bleɪd/",m:"n. 刀刃",c:"sharp blade"},
    {w:"blame",p:"/bleɪm/",m:"v./n. 责备",c:"blame for"},
    {w:"blank",p:"/blæŋk/",m:"adj. 空白的",c:"blank space"},
    {w:"blast",p:"/blɑːst/",m:"n. 爆炸 v. 爆破",c:"blast off"},
    {w:"blend",p:"/blend/",m:"v./n. 混合",c:"blend in"},
    {w:"bless",p:"/bles/",m:"v. 祝福",c:"bless with"},
    {w:"bond",p:"/bɒnd/",m:"n. 纽带，债券",c:"emotional bond"},
    {w:"boom",p:"/buːm/",m:"n. 繁荣 v. 兴旺",c:"economic boom"},
    {w:"boost",p:"/buːst/",m:"v./n. 促进",c:"boost confidence"},
    {w:"border",p:"/ˈbɔːdər/",m:"n. 边境",c:"cross the border"},
    {w:"bounce",p:"/baʊns/",m:"v. 弹跳",c:"bounce back"},
    {w:"bound",p:"/baʊnd/",m:"adj. 一定的 v. 跳跃",c:"be bound to"},
    {w:"boundary",p:"/ˈbaʊndri/",m:"n. 边界",c:"set boundaries"},
    {w:"brand",p:"/brænd/",m:"n. 品牌",c:"brand image"},
    {w:"breed",p:"/briːd/",m:"v. 繁殖 n. 品种",c:"breed animals"},
    {w:"brilliant",p:"/ˈbrɪliənt/",m:"adj. 杰出的",c:"brilliant idea"},
    {w:"broad",p:"/brɔːd/",m:"adj. 宽的，广泛的",c:"broad range"},
    {w:"broadcast",p:"/ˈbrɔːdkɑːst/",m:"v./n. 广播",c:"live broadcast"},
    {w:"budget",p:"/ˈbʌdʒɪt/",m:"n. 预算",c:"within budget"},
    {w:"burden",p:"/ˈbɜːdn/",m:"n. 负担",c:"heavy burden"},
    {w:"burst",p:"/bɜːst/",m:"v. 爆发",c:"burst into tears"},
    {w:"cabinet",p:"/ˈkæbɪnət/",m:"n. 橱柜，内阁",c:"filing cabinet"},
    {w:"calculate",p:"/ˈkælkjuleɪt/",m:"v. 计算",c:"calculate risk"},
    {w:"calendar",p:"/ˈkælɪndər/",m:"n. 日历",c:"lunar calendar"},
    {w:"campaign",p:"/kæmˈpeɪn/",m:"n. 运动，战役",c:"advertising campaign"},
    {w:"cancel",p:"/ˈkænsl/",m:"v. 取消",c:"cancel order"},
    {w:"candidate",p:"/ˈkændɪdət/",m:"n. 候选人",c:"presidential candidate"},
    {w:"capable",p:"/ˈkeɪpəbl/",m:"adj. 有能力的",c:"capable of"},
    {w:"capacity",p:"/kəˈpæsəti/",m:"n. 容量，能力",c:"production capacity"},
    {w:"capture",p:"/ˈkæptʃər/",m:"v. 俘获，捕获",c:"capture attention"},
    {w:"career",p:"/kəˈrɪər/",m:"n. 职业",c:"career development"},
    {w:"cargo",p:"/ˈkɑːɡəʊ/",m:"n. 货物",c:"cargo ship"},
    {w:"cast",p:"/kɑːst/",m:"v. 投掷，铸造",c:"cast doubt on"},
    {w:"casual",p:"/ˈkæʒuəl/",m:"adj. 随便的",c:"casual clothes"},
    {w:"catalog",p:"/ˈkætəlɒɡ/",m:"n. 目录",c:"product catalog"},
    {w:"category",p:"/ˈkætəɡəri/",m:"n. 类别",c:"product category"},
    {w:"caution",p:"/ˈkɔːʃn/",m:"n. 小心",c:"with caution"},
    {w:"cease",p:"/siːs/",m:"v. 停止",c:"cease to exist"},
    {w:"celebrate",p:"/ˈselɪbreɪt/",m:"v. 庆祝",c:"celebrate success"},
    {w:"ceremony",p:"/ˈserəməni/",m:"n. 典礼",c:"opening ceremony"},
    {w:"certificate",p:"/səˈtɪfɪkət/",m:"n. 证书",c:"birth certificate"},
    {w:"channel",p:"/ˈtʃænl/",m:"n. 频道，渠道",c:"communication channel"},
    {w:"character",p:"/ˈkærəktər/",m:"n. 性格，角色",c:"main character"},
    {w:"characteristic",p:"/ˌkærəktəˈrɪstɪk/",m:"n. 特征",c:"key characteristic"},
    {w:"charity",p:"/ˈtʃærəti/",m:"n. 慈善",c:"charity event"},
    {w:"chart",p:"/tʃɑːt/",m:"n. 图表",c:"flow chart"},
    {w:"chemical",p:"/ˈkemɪkl/",m:"adj. 化学的",c:"chemical reaction"},
    {w:"chief",p:"/tʃiːf/",m:"adj. 主要的 n. 首领",c:"chief executive"},
    {w:"circumstance",p:"/ˈsɜːkəmstəns/",m:"n. 环境",c:"under no circumstances"},
    {w:"civil",p:"/ˈsɪvl/",m:"adj. 公民的",c:"civil rights"},
    {w:"civilization",p:"/ˌsɪvəlaɪˈzeɪʃn/",m:"n. 文明",c:"ancient civilization"},
    {w:"claim",p:"/kleɪm/",m:"v./n. 声称",c:"claim responsibility"},
    {w:"clarify",p:"/ˈklærɪfaɪ/",m:"v. 澄清",c:"clarify the point"},
    {w:"classic",p:"/ˈklæsɪk/",m:"adj. 经典的",c:"classic example"},
    {w:"classify",p:"/ˈklæsɪfaɪ/",m:"v. 分类",c:"classify into"},
    {w:"climate",p:"/ˈklaɪmət/",m:"n. 气候",c:"climate change"},
    {w:"code",p:"/kəʊd/",m:"n. 代码，准则",c:"dress code"},
    {w:"collapse",p:"/kəˈlæps/",m:"v./n. 倒塌",c:"economic collapse"},
    {w:"colleague",p:"/ˈkɒliːɡ/",m:"n. 同事",c:"work colleague"},
    {w:"column",p:"/ˈkɒləm/",m:"n. 栏目，柱",c:"newspaper column"},
    {w:"combat",p:"/ˈkɒmbæt/",m:"v./n. 战斗",c:"combat crime"},
    {w:"combine",p:"/kəmˈbaɪn/",m:"v. 结合",c:"combine with"},
    {w:"command",p:"/kəˈmɑːnd/",m:"v./n. 命令，掌握",c:"have a command of"},
    {w:"comment",p:"/ˈkɒment/",m:"n./v. 评论",c:"no comment"},
    {w:"commerce",p:"/ˈkɒmɜːs/",m:"n. 商业",c:"e-commerce"},
    {w:"commercial",p:"/kəˈmɜːʃl/",m:"adj. 商业的 n. 广告",c:"commercial bank"},
    {w:"commission",p:"/kəˈmɪʃn/",m:"n. 委员会，佣金",c:"on commission"},
    {w:"commit",p:"/kəˈmɪt/",m:"v. 犯(罪)，承诺",c:"commit crime"},
    {w:"commitment",p:"/kəˈmɪtmənt/",m:"n. 承诺",c:"make a commitment"},
    {w:"committee",p:"/kəˈmɪti/",m:"n. 委员会",c:"executive committee"},
    {w:"communicate",p:"/kəˈmjuːnɪkeɪt/",m:"v. 交流",c:"communicate with"},
    {w:"community",p:"/kəˈmjuːnəti/",m:"n. 社区",c:"local community"},
    {w:"companion",p:"/kəmˈpæniən/",m:"n. 同伴",c:"travel companion"},
    {w:"compare",p:"/kəmˈpeər/",m:"v. 比较",c:"compare with"},
    {w:"compensation",p:"/ˌkɒmpenˈseɪʃn/",m:"n. 补偿",c:"seek compensation"},
    {w:"compete",p:"/kəmˈpiːt/",m:"v. 竞争",c:"compete against"},
    {w:"competitive",p:"/kəmˈpetətɪv/",m:"adj. 竞争的",c:"competitive advantage"},
    {w:"complain",p:"/kəmˈpleɪn/",m:"v. 抱怨",c:"complain about"},
    {w:"complaint",p:"/kəmˈpleɪnt/",m:"n. 投诉",c:"make a complaint"},
    {w:"complex",p:"/ˈkɒmpleks/",m:"adj. 复杂的",c:"complex situation"},
    {w:"component",p:"/kəmˈpəʊnənt/",m:"n. 组成部分",c:"key component"},
    {w:"compose",p:"/kəmˈpəʊz/",m:"v. 组成，创作",c:"compose music"},
    {w:"comprehensive",p:"/ˌkɒmprɪˈhensɪv/",m:"adj. 全面的",c:"comprehensive survey"},
    {w:"comprise",p:"/kəmˈpraɪz/",m:"v. 包含",c:"be comprised of"},
    {w:"compromise",p:"/ˈkɒmprəmaɪz/",m:"n./v. 妥协",c:"reach a compromise"},
    {w:"concept",p:"/ˈkɒnsept/",m:"n. 概念",c:"basic concept"},
    {w:"concern",p:"/kənˈsɜːn/",m:"n. 关心 v. 涉及",c:"concern about"},
    {w:"conclude",p:"/kənˈkluːd/",m:"v. 得出结论",c:"conclude that"},
    {w:"conduct",p:"/kənˈdʌkt/",m:"v. 进行 n. 行为",c:"conduct research"},
    {w:"conference",p:"/ˈkɒnfərəns/",m:"n. 会议",c:"press conference"},
    {w:"confidence",p:"/ˈkɒnfɪdəns/",m:"n. 信心",c:"self-confidence"},
    {w:"confident",p:"/ˈkɒnfɪdənt/",m:"adj. 自信的",c:"confident about"},
    {w:"confirm",p:"/kənˈfɜːm/",m:"v. 确认",c:"confirm reservation"},
    {w:"conflict",p:"/ˈkɒnflɪkt/",m:"n. 冲突",c:"conflict of interest"},
    {w:"confront",p:"/kənˈfrʌnt/",m:"v. 面对，对抗",c:"confront challenges"},
    {w:"confuse",p:"/kənˈfjuːz/",m:"v. 使困惑",c:"confuse A with B"},
    {w:"congratulate",p:"/kənˈɡrætʃuleɪt/",m:"v. 祝贺",c:"congratulate on"},
    {w:"connection",p:"/kəˈnekʃn/",m:"n. 连接",c:"Internet connection"},
    {w:"conscious",p:"/ˈkɒnʃəs/",m:"adj. 有意识的",c:"be conscious of"},
    {w:"consequence",p:"/ˈkɒnsɪkwəns/",m:"n. 结果",c:"face consequences"},
    {w:"conservation",p:"/ˌkɒnsəˈveɪʃn/",m:"n. 保护",c:"energy conservation"},
    {w:"considerable",p:"/kənˈsɪdərəbl/",m:"adj. 相当大的",c:"considerable amount"},
    {w:"consist",p:"/kənˈsɪst/",m:"v. 组成",c:"consist of"},
    {w:"constant",p:"/ˈkɒnstənt/",m:"adj. 不断的",c:"constant effort"},
    {w:"constitute",p:"/ˈkɒnstɪtjuːt/",m:"v. 构成",c:"constitute a threat"},
    {w:"construct",p:"/kənˈstrʌkt/",m:"v. 建造",c:"construct a bridge"},
    {w:"consult",p:"/kənˈsʌlt/",m:"v. 咨询",c:"consult a doctor"},
    {w:"consume",p:"/kənˈsjuːm/",m:"v. 消费",c:"consume energy"},
    {w:"consumer",p:"/kənˈsjuːmər/",m:"n. 消费者",c:"consumer rights"},
    {w:"contact",p:"/ˈkɒntækt/",m:"n./v. 联系",c:"contact information"},
    {w:"contain",p:"/kənˈteɪn/",m:"v. 包含",c:"contain information"},
    {w:"contemporary",p:"/kənˈtemprəri/",m:"adj. 当代的",c:"contemporary art"},
    {w:"content",p:"/ˈkɒntent/",m:"n. 内容 adj. 满足的",c:"be content with"},
    {w:"contest",p:"/ˈkɒntest/",m:"n. 竞赛",c:"enter a contest"},
    {w:"context",p:"/ˈkɒntekst/",m:"n. 上下文",c:"in context"},
    {w:"continuous",p:"/kənˈtɪnjuəs/",m:"adj. 连续的",c:"continuous process"},
    {w:"contract",p:"/ˈkɒntrækt/",m:"n. 合同 v. 收缩",c:"sign a contract"},
    {w:"contrary",p:"/ˈkɒntrəri/",m:"adj. 相反的",c:"on the contrary"},
    {w:"contrast",p:"/ˈkɒntrɑːst/",m:"n./v. 对比",c:"in contrast to"},
    {w:"contribute",p:"/kənˈtrɪbjuːt/",m:"v. 贡献",c:"contribute to"},
    {w:"controversial",p:"/ˌkɒntrəˈvɜːʃl/",m:"adj. 有争议的",c:"controversial issue"},
    {w:"convenience",p:"/kənˈviːniəns/",m:"n. 便利",c:"for convenience"},
    {w:"conventional",p:"/kənˈvenʃənl/",m:"adj. 传统的",c:"conventional method"},
    {w:"convert",p:"/kənˈvɜːt/",m:"v. 转变",c:"convert into"},
    {w:"convey",p:"/kənˈveɪ/",m:"v. 传达",c:"convey message"},
    {w:"convince",p:"/kənˈvɪns/",m:"v. 说服",c:"convince someone"},
    {w:"cooperate",p:"/kəʊˈɒpəreɪt/",m:"v. 合作",c:"cooperate with"},
    {w:"coordinate",p:"/kəʊˈɔːdɪneɪt/",m:"v. 协调",c:"coordinate efforts"},
    {w:"cope",p:"/kəʊp/",m:"v. 应付",c:"cope with"},
    {w:"core",p:"/kɔːr/",m:"n. 核心",c:"core value"},
    {w:"corporate",p:"/ˈkɔːpərət/",m:"adj. 公司的",c:"corporate culture"},
    {w:"corporation",p:"/ˌkɔːpəˈreɪʃn/",m:"n. 公司",c:"multinational corporation"},
    {w:"correspond",p:"/ˌkɒrəˈspɒnd/",m:"v. 对应",c:"correspond to"},
    {w:"county",p:"/ˈkaʊnti/",m:"n. 县",c:"county level"},
    {w:"court",p:"/kɔːt/",m:"n. 法庭",c:"supreme court"},
    {w:"crash",p:"/kræʃ/",m:"v./n. 碰撞，崩溃",c:"car crash"},
    {w:"creative",p:"/kriˈeɪtɪv/",m:"adj. 创造性的",c:"creative thinking"},
    {w:"credit",p:"/ˈkredɪt/",m:"n. 信用，学分",c:"credit card"},
    {w:"crime",p:"/kraɪm/",m:"n. 犯罪",c:"commit a crime"},
    {w:"criminal",p:"/ˈkrɪmɪnl/",m:"adj. 犯罪的 n. 罪犯",c:"criminal law"},
    {w:"crisis",p:"/ˈkraɪsɪs/",m:"n. 危机",c:"financial crisis"},
    {w:"criterion",p:"/kraɪˈtɪəriən/",m:"n. 标准",c:"selection criterion"},
    {w:"critical",p:"/ˈkrɪtɪkl/",m:"adj. 批评的，关键的",c:"critical thinking"},
    {w:"criticism",p:"/ˈkrɪtɪsɪzəm/",m:"n. 批评",c:"constructive criticism"},
    {w:"crucial",p:"/ˈkruːʃl/",m:"adj. 关键的",c:"crucial role"},
    {w:"cultivate",p:"/ˈkʌltɪveɪt/",m:"v. 培养，耕作",c:"cultivate habits"},
    {w:"culture",p:"/ˈkʌltʃər/",m:"n. 文化",c:"corporate culture"},
    {w:"curiosity",p:"/ˌkjʊəriˈɒsəti/",m:"n. 好奇心",c:"out of curiosity"},
    {w:"currency",p:"/ˈkʌrənsi/",m:"n. 货币",c:"foreign currency"},
    {w:"current",p:"/ˈkʌrənt/",m:"adj. 当前的 n. 水流",c:"current situation"},
    {w:"curriculum",p:"/kəˈrɪkjələm/",m:"n. 课程",c:"curriculum vitae"},
    {w:"damage",p:"/ˈdæmɪdʒ/",m:"n./v. 损害",c:"cause damage"},
    {w:"deadline",p:"/ˈdedlaɪn/",m:"n. 截止日期",c:"meet the deadline"},
    {w:"debate",p:"/dɪˈbeɪt/",m:"n./v. 辩论",c:"heated debate"},
    {w:"debt",p:"/det/",m:"n. 债务",c:"in debt"},
    {w:"decade",p:"/ˈdekeɪd/",m:"n. 十年",c:"over the past decade"},
    {w:"deceive",p:"/dɪˈsiːv/",m:"v. 欺骗",c:"deceive someone"},
    {w:"decline",p:"/dɪˈklaɪn/",m:"v./n. 下降，拒绝",c:"decline an offer"},
    {w:"decorate",p:"/ˈdekəreɪt/",m:"v. 装饰",c:"decorate the room"},
    {w:"defeat",p:"/dɪˈfiːt/",m:"v./n. 击败",c:"defeat the enemy"},
    {w:"defend",p:"/dɪˈfend/",m:"v. 防御，辩护",c:"defend against"},
    {w:"define",p:"/dɪˈfaɪn/",m:"v. 定义",c:"define as"},
    {w:"definite",p:"/ˈdefɪnət/",m:"adj. 明确的",c:"definite answer"},
    {w:"definitely",p:"/ˈdefɪnətli/",m:"adv. 肯定地",c:"definitely true"},
    {w:"delay",p:"/dɪˈleɪ/",m:"v./n. 延迟",c:"without delay"},
    {w:"delegate",p:"/ˈdelɪɡət/",m:"n. 代表 v. 授权",c:"delegate authority"},
    {w:"deliberate",p:"/dɪˈlɪbərət/",m:"adj. 故意的",c:"deliberate attempt"},
    {w:"delicate",p:"/ˈdelɪkət/",m:"adj. 精致的",c:"delicate situation"},
    {w:"deliver",p:"/dɪˈlɪvər/",m:"v. 递送，发表",c:"deliver a speech"},
    {w:"demand",p:"/dɪˈmɑːnd/",m:"v./n. 需求",c:"supply and demand"},
    {w:"democracy",p:"/dɪˈmɒkrəsi/",m:"n. 民主",c:"democracy and freedom"},
    {w:"demonstrate",p:"/ˈdemənstreɪt/",m:"v. 展示，证明",c:"demonstrate ability"},
    {w:"dense",p:"/dens/",m:"adj. 密集的",c:"dense population"},
    {w:"deny",p:"/dɪˈnaɪ/",m:"v. 否认",c:"deny access"},
    {w:"depart",p:"/dɪˈpɑːt/",m:"v. 离开",c:"depart from"},
    {w:"department",p:"/dɪˈpɑːtmənt/",m:"n. 部门",c:"marketing department"},
    {w:"departure",p:"/dɪˈpɑːtʃər/",m:"n. 离开",c:"departure time"},
    {w:"depend",p:"/dɪˈpend/",m:"v. 依赖",c:"depend on"},
    {w:"deposit",p:"/dɪˈpɒzɪt/",m:"n. 存款 v. 存放",c:"bank deposit"},
    {w:"depress",p:"/dɪˈpres/",m:"v. 使沮丧",c:"depress economy"},
    {w:"depression",p:"/dɪˈpreʃn/",m:"n. 抑郁，萧条",c:"economic depression"},
    {w:"derive",p:"/dɪˈraɪv/",m:"v. 源自",c:"derive from"},
    {w:"deserve",p:"/dɪˈzɜːv/",m:"v. 值得",c:"deserve attention"},
    {w:"desire",p:"/dɪˈzaɪər/",m:"n./v. 渴望",c:"strong desire"},
    {w:"desperate",p:"/ˈdespərət/",m:"adj. 绝望的",c:"desperate situation"},
    {w:"despite",p:"/dɪˈspaɪt/",m:"prep. 尽管",c:"despite the fact"},
    {w:"destination",p:"/ˌdestɪˈneɪʃn/",m:"n. 目的地",c:"tourist destination"},
    {w:"destroy",p:"/dɪˈstrɔɪ/",m:"v. 破坏",c:"destroy evidence"},
    {w:"detail",p:"/ˈdiːteɪl/",m:"n. 细节 v. 详述",c:"in detail"},
    {w:"detect",p:"/dɪˈtekt/",m:"v. 发现",c:"detect changes"},
    {w:"determination",p:"/dɪˌtɜːmɪˈneɪʃn/",m:"n. 决心",c:"show determination"},
    {w:"determine",p:"/dɪˈtɜːmɪn/",m:"v. 决定",c:"determine to do"},
    {w:"device",p:"/dɪˈvaɪs/",m:"n. 设备",c:"electronic device"},
    {w:"devote",p:"/dɪˈvəʊt/",m:"v. 致力于",c:"devote to"},
    {w:"differ",p:"/ˈdɪfər/",m:"v. 不同",c:"differ from"},
    {w:"digital",p:"/ˈdɪdʒɪtl/",m:"adj. 数字的",c:"digital age"},
    {w:"dignity",p:"/ˈdɪɡnəti/",m:"n. 尊严",c:"human dignity"},
    {w:"dilemma",p:"/dɪˈlemə/",m:"n. 困境",c:"face a dilemma"},
    {w:"dimension",p:"/daɪˈmenʃn/",m:"n. 尺寸，维度",c:"third dimension"},
    {w:"discipline",p:"/ˈdɪsəplɪn/",m:"n. 纪律",c:"self-discipline"},
    {w:"discount",p:"/ˈdɪskaʊnt/",m:"n. 折扣",c:"at a discount"},
    {w:"display",p:"/dɪˈspleɪ/",m:"v./n. 展示",c:"on display"},
    {w:"dispose",p:"/dɪˈspəʊz/",m:"v. 处理",c:"dispose of"},
    {w:"dispute",p:"/dɪˈspjuːt/",m:"n./v. 争论",c:"labor dispute"},
    {w:"dissolve",p:"/dɪˈzɒlv/",m:"v. 溶解",c:"dissolve in water"},
    {w:"distinct",p:"/dɪˈstɪŋkt/",m:"adj. 不同的",c:"distinct from"},
    {w:"distinguish",p:"/dɪˈstɪŋɡwɪʃ/",m:"v. 区分",c:"distinguish between"},
    {w:"distribute",p:"/dɪˈstrɪbjuːt/",m:"v. 分发",c:"distribute to"},
    {w:"diverse",p:"/daɪˈvɜːs/",m:"adj. 多样的",c:"culturally diverse"},
    {w:"division",p:"/dɪˈvɪʒn/",m:"n. 划分",c:"division of labor"},
    {w:"document",p:"/ˈdɒkjumənt/",m:"n. 文件",c:"official document"},
    {w:"domestic",p:"/dəˈmestɪk/",m:"adj. 国内的，家庭的",c:"domestic market"},
    {w:"dominant",p:"/ˈdɒmɪnənt/",m:"adj. 主导的",c:"dominant position"},
    {w:"dominate",p:"/ˈdɒmɪneɪt/",m:"v. 主导",c:"dominate the market"},
    {w:"donation",p:"/dəʊˈneɪʃn/",m:"n. 捐赠",c:"make a donation"},
    {w:"doubt",p:"/daʊt/",m:"n./v. 怀疑",c:"beyond doubt"},
    {w:"draft",p:"/drɑːft/",m:"n. 草稿 v. 起草",c:"first draft"},
    {w:"dramatic",p:"/drəˈmætɪk/",m:"adj. 戏剧性的",c:"dramatic change"},
    {w:"drift",p:"/drɪft/",m:"v./n. 漂流",c:"drift apart"},
    {w:"dynamic",p:"/daɪˈnæmɪk/",m:"adj. 动态的",c:"dynamic economy"},
    {w:"ease",p:"/iːz/",m:"n. 容易 v. 减轻",c:"with ease"},
    {w:"economic",p:"/ˌiːkəˈnɒmɪk/",m:"adj. 经济的",c:"economic growth"},
    {w:"economical",p:"/ˌiːkəˈnɒmɪkl/",m:"adj. 节约的",c:"economical car"},
    {w:"economy",p:"/ɪˈkɒnəmi/",m:"n. 经济",c:"global economy"},
    {w:"edition",p:"/ɪˈdɪʃn/",m:"n. 版本",c:"special edition"},
    {w:"editor",p:"/ˈedɪtər/",m:"n. 编辑",c:"chief editor"},
    {w:"educate",p:"/ˈedʒukeɪt/",m:"v. 教育",c:"educate children"},
    {w:"effective",p:"/ɪˈfektɪv/",m:"adj. 有效的",c:"effective method"},
    {w:"efficiency",p:"/ɪˈfɪʃnsi/",m:"n. 效率",c:"improve efficiency"},
    {w:"efficient",p:"/ɪˈfɪʃnt/",m:"adj. 高效的",c:"energy efficient"},
    {w:"elaborate",p:"/ɪˈlæbərət/",m:"adj. 精心的",c:"elaborate on"},
    {w:"election",p:"/ɪˈlekʃn/",m:"n. 选举",c:"general election"},
    {w:"electronic",p:"/ɪˌlekˈtrɒnɪk/",m:"adj. 电子的",c:"electronic device"},
    {w:"element",p:"/ˈelɪmənt/",m:"n. 元素",c:"key element"},
    {w:"eliminate",p:"/ɪˈlɪmɪneɪt/",m:"v. 消除",c:"eliminate poverty"},
    {w:"embrace",p:"/ɪmˈbreɪs/",m:"v. 拥抱，接受",c:"embrace change"},
    {w:"emerge",p:"/ɪˈmɜːdʒ/",m:"v. 出现",c:"emerge as"},
    {w:"emergency",p:"/ɪˈmɜːdʒənsi/",m:"n. 紧急情况",c:"emergency room"},
    {w:"emission",p:"/ɪˈmɪʃn/",m:"n. 排放",c:"carbon emission"},
    {w:"emotion",p:"/ɪˈməʊʃn/",m:"n. 情感",c:"express emotion"},
    {w:"emphasis",p:"/ˈemfəsɪs/",m:"n. 强调",c:"put emphasis on"},
    {w:"emphasize",p:"/ˈemfəsaɪz/",m:"v. 强调",c:"emphasize the importance"},
    {w:"employ",p:"/ɪmˈplɔɪ/",m:"v. 雇用",c:"employ workers"},
    {w:"employee",p:"/ɪmˈplɔɪiː/",m:"n. 雇员",c:"employee benefits"},
    {w:"employer",p:"/ɪmˈplɔɪər/",m:"n. 雇主",c:"employer brand"},
    {w:"enable",p:"/ɪˈneɪbl/",m:"v. 使能够",c:"enable to do"},
    {w:"encounter",p:"/ɪnˈkaʊntər/",m:"v./n. 遭遇",c:"encounter problems"},
    {w:"engage",p:"/ɪnˈɡeɪdʒ/",m:"v. 从事，吸引",c:"engage in"},
    {w:"enhance",p:"/ɪnˈhɑːns/",m:"v. 提高",c:"enhance performance"},
    {w:"enormous",p:"/ɪˈnɔːməs/",m:"adj. 巨大的",c:"enormous potential"},
    {w:"ensure",p:"/ɪnˈʃʊər/",m:"v. 确保",c:"ensure safety"},
    {w:"enterprise",p:"/ˈentəpraɪz/",m:"n. 企业",c:"private enterprise"},
    {w:"entertain",p:"/ˌentəˈteɪn/",m:"v. 娱乐",c:"entertain guests"},
    {w:"enthusiasm",p:"/ɪnˈθjuːziæzəm/",m:"n. 热情",c:"show enthusiasm"},
    {w:"entitle",p:"/ɪnˈtaɪtl/",m:"v. 给…权利",c:"be entitled to"},
    {w:"environment",p:"/ɪnˈvaɪrənmənt/",m:"n. 环境",c:"protect the environment"},
    {w:"equip",p:"/ɪˈkwɪp/",m:"v. 装备",c:"equip with"},
    {w:"equivalent",p:"/ɪˈkwɪvələnt/",m:"adj. 等价的",c:"equivalent to"},
    {w:"error",p:"/ˈerər/",m:"n. 错误",c:"human error"},
    {w:"essential",p:"/ɪˈsenʃl/",m:"adj. 必要的",c:"essential role"},
    {w:"establish",p:"/ɪˈstæblɪʃ/",m:"v. 建立",c:"establish contact"},
    {w:"estate",p:"/ɪˈsteɪt/",m:"n. 房地产",c:"real estate"},
    {w:"estimate",p:"/ˈestɪmeɪt/",m:"v./n. 估计",c:"rough estimate"},
    {w:"evaluate",p:"/ɪˈvæljueɪt/",m:"v. 评估",c:"evaluate performance"},
    {w:"evidence",p:"/ˈevɪdəns/",m:"n. 证据",c:"scientific evidence"},
    {w:"evident",p:"/ˈevɪdənt/",m:"adj. 明显的",c:"self-evident"},
    {w:"evolution",p:"/ˌiːvəˈluːʃn/",m:"n. 进化",c:"human evolution"},
    {w:"evolve",p:"/ɪˈvɒlv/",m:"v. 进化",c:"evolve into"},
    {w:"exaggerate",p:"/ɪɡˈzædʒəreɪt/",m:"v. 夸大",c:"tend to exaggerate"},
    {w:"examine",p:"/ɪɡˈzæmɪn/",m:"v. 检查",c:"examine carefully"},
    {w:"exceed",p:"/ɪkˈsiːd/",m:"v. 超过",c:"exceed expectations"},
    {w:"exception",p:"/ɪkˈsepʃn/",m:"n. 例外",c:"without exception"},
    {w:"excessive",p:"/ɪkˈsesɪv/",m:"adj. 过度的",c:"excessive use"},
    {w:"exchange",p:"/ɪksˈtʃeɪndʒ/",m:"v./n. 交换",c:"exchange rate"},
    {w:"exclude",p:"/ɪkˈskluːd/",m:"v. 排除",c:"exclude from"},
    {w:"execute",p:"/ˈeksɪkjuːt/",m:"v. 执行",c:"execute a plan"},
    {w:"executive",p:"/ɪɡˈzekjətɪv/",m:"adj. 执行的 n. 主管",c:"chief executive"},
    {w:"exhibit",p:"/ɪɡˈzɪbɪt/",m:"v. 展示",c:"exhibit behavior"},
    {w:"expand",p:"/ɪkˈspænd/",m:"v. 扩张",c:"expand business"},
    {w:"expect",p:"/ɪkˈspekt/",m:"v. 期望",c:"expect to"},
    {w:"expense",p:"/ɪkˈspens/",m:"n. 费用",c:"at the expense of"},
    {w:"expert",p:"/ˈekspɜːt/",m:"n. 专家",c:"subject expert"},
    {w:"exploit",p:"/ɪkˈsplɔɪt/",m:"v. 开发，剥削",c:"exploit resources"},
    {w:"explore",p:"/ɪkˈsplɔːr/",m:"v. 探索",c:"explore options"},
    {w:"export",p:"/ɪkˈspɔːt/",m:"v./n. 出口",c:"export goods"},
    {w:"expose",p:"/ɪkˈspəʊz/",m:"v. 暴露",c:"expose to"},
    {w:"extend",p:"/ɪkˈstend/",m:"v. 延伸",c:"extend deadline"},
    {w:"extensive",p:"/ɪkˈstensɪv/",m:"adj. 广泛的",c:"extensive research"},
    {w:"extent",p:"/ɪkˈstent/",m:"n. 程度",c:"to some extent"},
    {w:"external",p:"/ɪkˈstɜːnl/",m:"adj. 外部的",c:"external factors"},
    {w:"extraordinary",p:"/ɪkˈstrɔːdnri/",m:"adj. 非凡的",c:"extraordinary achievement"},
    {w:"extreme",p:"/ɪkˈstriːm/",m:"adj. 极端的",c:"extreme weather"},
    {w:"facilitate",p:"/fəˈsɪlɪteɪt/",m:"v. 促进",c:"facilitate communication"},
    {w:"facility",p:"/fəˈsɪləti/",m:"n. 设施",c:"sports facility"},
    {w:"factor",p:"/ˈfæktər/",m:"n. 因素",c:"key factor"},
    {w:"faith",p:"/feɪθ/",m:"n. 信念",c:"have faith in"},
    {w:"fame",p:"/feɪm/",m:"n. 名声",c:"rise to fame"},
    {w:"famine",p:"/ˈfæmɪn/",m:"n. 饥荒",c:"famine relief"},
    {w:"fascinate",p:"/ˈfæsɪneɪt/",m:"v. 使着迷",c:"be fascinated by"},
    {w:"fashion",p:"/ˈfæʃn/",m:"n. 时尚",c:"in fashion"},
    {w:"fatal",p:"/ˈfeɪtl/",m:"adj. 致命的",c:"fatal accident"},
    {w:"fault",p:"/fɔːlt/",m:"n. 缺点，过错",c:"find fault with"},
    {w:"favorable",p:"/ˈfeɪvərəbl/",m:"adj. 有利的",c:"favorable conditions"},
    {w:"feasible",p:"/ˈfiːzəbl/",m:"adj. 可行的",c:"feasible solution"},
    {w:"feature",p:"/ˈfiːtʃər/",m:"n. 特点",c:"key feature"},
    {w:"feedback",p:"/ˈfiːdbæk/",m:"n. 反馈",c:"positive feedback"},
    {w:"fertile",p:"/ˈfɜːtaɪl/",m:"adj. 肥沃的",c:"fertile land"},
    {w:"fiction",p:"/ˈfɪkʃn/",m:"n. 小说",c:"science fiction"},
    {w:"fierce",p:"/fɪəs/",m:"adj. 激烈的",c:"fierce competition"},
    {w:"finance",p:"/ˈfaɪnæns/",m:"n. 金融",c:"personal finance"},
    {w:"flexible",p:"/ˈfleksəbl/",m:"adj. 灵活的",c:"flexible schedule"},
    {w:"flourish",p:"/ˈflʌrɪʃ/",m:"v. 繁荣",c:"flourish in"},
    {w:"forecast",p:"/ˈfɔːkɑːst/",m:"n./v. 预测",c:"weather forecast"},
    {w:"formal",p:"/ˈfɔːml/",m:"adj. 正式的",c:"formal education"},
    {w:"format",p:"/ˈfɔːmæt/",m:"n. 格式",c:"file format"},
    {w:"formula",p:"/ˈfɔːmjələ/",m:"n. 公式",c:"mathematical formula"},
    {w:"fortune",p:"/ˈfɔːtʃuːn/",m:"n. 命运，财富",c:"make a fortune"},
    {w:"foundation",p:"/faʊnˈdeɪʃn/",m:"n. 基础",c:"solid foundation"},
    {w:"fraction",p:"/ˈfrækʃn/",m:"n. 分数，小部分",c:"a fraction of"},
    {w:"framework",p:"/ˈfreɪmwɜːk/",m:"n. 框架",c:"legal framework"},
    {w:"frontier",p:"/ˈfrʌntɪər/",m:"n. 边境，前沿",c:"new frontier"},
    {w:"fulfill",p:"/fʊlˈfɪl/",m:"v. 实现",c:"fulfill a dream"},
    {w:"function",p:"/ˈfʌŋkʃn/",m:"n. 功能 v. 运行",c:"basic function"},
    {w:"fund",p:"/fʌnd/",m:"n. 基金 v. 资助",c:"raise funds"},
    {w:"fundamental",p:"/ˌfʌndəˈmentl/",m:"adj. 基本的",c:"fundamental change"},
    {w:"furthermore",p:"/ˌfɜːðəˈmɔːr/",m:"adv. 此外",c:"and furthermore"},
    {w:"gain",p:"/ɡeɪn/",m:"v. 获得 n. 收益",c:"gain experience"},
    {w:"gap",p:"/ɡæp/",m:"n. 缺口，差距",c:"generation gap"},
    {w:"gender",p:"/ˈdʒendər/",m:"n. 性别",c:"gender equality"},
    {w:"generate",p:"/ˈdʒenəreɪt/",m:"v. 产生",c:"generate income"},
    {w:"generous",p:"/ˈdʒenərəs/",m:"adj. 慷慨的",c:"generous donation"},
    {w:"genuine",p:"/ˈdʒenjuɪn/",m:"adj. 真正的",c:"genuine interest"},
    {w:"gesture",p:"/ˈdʒestʃər/",m:"n. 手势",c:"kind gesture"},
    {w:"global",p:"/ˈɡləʊbl/",m:"adj. 全球的",c:"global warming"},
    {w:"globe",p:"/ɡləʊb/",m:"n. 地球",c:"across the globe"},
    {w:"gradual",p:"/ˈɡrædʒuəl/",m:"adj. 逐渐的",c:"gradual process"},
    {w:"grant",p:"/ɡrɑːnt/",m:"v. 授予 n. 拨款",c:"take for granted"},
    {w:"grasp",p:"/ɡrɑːsp/",m:"v./n. 抓住，理解",c:"grasp the concept"},
    {w:"grateful",p:"/ˈɡreɪtfl/",m:"adj. 感激的",c:"be grateful for"},
    {w:"guarantee",p:"/ˌɡærənˈtiː/",m:"v./n. 保证",c:"guarantee quality"},
    {w:"guidance",p:"/ˈɡaɪdns/",m:"n. 指导",c:"career guidance"},
    {w:"guideline",p:"/ˈɡaɪdlaɪn/",m:"n. 指导方针",c:"follow guidelines"},
    {w:"guilty",p:"/ˈɡɪlti/",m:"adj. 有罪的",c:"feel guilty"},
    {w:"halt",p:"/hɔːlt/",m:"v./n. 停止",c:"come to a halt"},
    {w:"handle",p:"/ˈhændl/",m:"v. 处理 n. 把手",c:"handle pressure"},
    {w:"harsh",p:"/hɑːʃ/",m:"adj. 严酷的",c:"harsh conditions"},
    {w:"hazard",p:"/ˈhæzəd/",m:"n. 危险",c:"health hazard"},
    {w:"hence",p:"/hens/",m:"adv. 因此",c:"and hence"},
    {w:"heritage",p:"/ˈherɪtɪdʒ/",m:"n. 遗产",c:"cultural heritage"},
    {w:"highlight",p:"/ˈhaɪlaɪt/",m:"v. 强调",c:"highlight the importance"},
    {w:"horizon",p:"/həˈraɪzn/",m:"n. 地平线",c:"broaden horizon"},
    {w:"hostile",p:"/ˈhɒstaɪl/",m:"adj. 敌对的",c:"hostile environment"},
    {w:"household",p:"/ˈhaʊshəʊld/",m:"n. 家庭",c:"household chores"},
    {w:"humble",p:"/ˈhʌmbl/",m:"adj. 谦逊的",c:"humble beginnings"},
    {w:"ideal",p:"/aɪˈdiːəl/",m:"adj. 理想的",c:"ideal solution"},
    {w:"identical",p:"/aɪˈdentɪkl/",m:"adj. 相同的",c:"identical to"},
    {w:"identify",p:"/aɪˈdentɪfaɪ/",m:"v. 识别",c:"identify with"},
    {w:"identity",p:"/aɪˈdentəti/",m:"n. 身份",c:"cultural identity"},
    {w:"ignorance",p:"/ˈɪɡnərəns/",m:"n. 无知",c:"ignorance of law"},
    {w:"illegal",p:"/ɪˈliːɡl/",m:"adj. 非法的",c:"illegal activities"},
    {w:"illustrate",p:"/ˈɪləstreɪt/",m:"v. 说明",c:"illustrate a point"},
    {w:"image",p:"/ˈɪmɪdʒ/",m:"n. 形象",c:"public image"},
    {w:"imagination",p:"/ɪˌmædʒɪˈneɪʃn/",m:"n. 想象力",c:"beyond imagination"},
    {w:"immediate",p:"/ɪˈmiːdiət/",m:"adj. 立即的",c:"immediate action"},
    {w:"immigrant",p:"/ˈɪmɪɡrənt/",m:"n. 移民",c:"illegal immigrant"},
    {w:"impact",p:"/ˈɪmpækt/",m:"n./v. 影响",c:"significant impact"},
    {w:"implement",p:"/ˈɪmplɪment/",m:"v. 实施",c:"implement a plan"},
    {w:"implication",p:"/ˌɪmplɪˈkeɪʃn/",m:"n. 含义",c:"have implications for"},
    {w:"impose",p:"/ɪmˈpəʊz/",m:"v. 强加",c:"impose restrictions"},
    {w:"impress",p:"/ɪmˈpres/",m:"v. 给…印象",c:"impress upon"},
    {w:"impression",p:"/ɪmˈpreʃn/",m:"n. 印象",c:"first impression"},
    {w:"incident",p:"/ˈɪnsɪdənt/",m:"n. 事件",c:"isolated incident"},
    {w:"incline",p:"/ɪnˈklaɪn/",m:"v. 倾向",c:"be inclined to"},
    {w:"income",p:"/ˈɪnkʌm/",m:"n. 收入",c:"annual income"},
    {w:"increasingly",p:"/ɪnˈkriːsɪŋli/",m:"adv. 日益",c:"increasingly popular"},
    {w:"independence",p:"/ˌɪndɪˈpendəns/",m:"n. 独立",c:"gain independence"},
    {w:"indicate",p:"/ˈɪndɪkeɪt/",m:"v. 表明",c:"indicate that"},
    {w:"individual",p:"/ˌɪndɪˈvɪdʒuəl/",m:"adj. 个人的 n. 个人",c:"individual needs"},
    {w:"industrial",p:"/ɪnˈdʌstriəl/",m:"adj. 工业的",c:"industrial revolution"},
    {w:"inevitable",p:"/ɪnˈevɪtəbl/",m:"adj. 不可避免的",c:"inevitable consequence"},
    {w:"infant",p:"/ˈɪnfənt/",m:"n. 婴儿",c:"infant mortality"},
    {w:"inflation",p:"/ɪnˈfleɪʃn/",m:"n. 通货膨胀",c:"inflation rate"},
    {w:"influence",p:"/ˈɪnfluəns/",m:"n./v. 影响",c:"under the influence"},
    {w:"inform",p:"/ɪnˈfɔːm/",m:"v. 通知",c:"inform someone"},
    {w:"initial",p:"/ɪˈnɪʃl/",m:"adj. 最初的",c:"initial stage"},
    {w:"initiative",p:"/ɪˈnɪʃətɪv/",m:"n. 主动性",c:"take the initiative"},
    {w:"injure",p:"/ˈɪndʒər/",m:"v. 伤害",c:"injure seriously"},
    {w:"innocent",p:"/ˈɪnəsnt/",m:"adj. 无辜的",c:"innocent people"},
    {w:"innovation",p:"/ˌɪnəˈveɪʃn/",m:"n. 创新",c:"technological innovation"},
    {w:"input",p:"/ˈɪnpʊt/",m:"n./v. 输入",c:"input data"},
    {w:"insight",p:"/ˈɪnsaɪt/",m:"n. 洞察力",c:"valuable insight"},
    {w:"inspect",p:"/ɪnˈspekt/",m:"v. 检查",c:"inspect carefully"},
    {w:"inspire",p:"/ɪnˈspaɪər/",m:"v. 激励",c:"inspire others"},
    {w:"install",p:"/ɪnˈstɔːl/",m:"v. 安装",c:"install software"},
    {w:"instance",p:"/ˈɪnstəns/",m:"n. 例子",c:"for instance"},
    {w:"institute",p:"/ˈɪnstɪtjuːt/",m:"n. 机构",c:"research institute"},
    {w:"institution",p:"/ˌɪnstɪˈtjuːʃn/",m:"n. 机构",c:"financial institution"},
    {w:"instrument",p:"/ˈɪnstrəmənt/",m:"n. 乐器",c:"musical instrument"},
    {w:"insurance",p:"/ɪnˈʃʊərəns/",m:"n. 保险",c:"health insurance"},
    {w:"intellectual",p:"/ˌɪntəˈlektʃuəl/",m:"adj. 智力的",c:"intellectual property"},
    {w:"intelligence",p:"/ɪnˈtelɪdʒəns/",m:"n. 智力，情报",c:"artificial intelligence"},
    {w:"intense",p:"/ɪnˈtens/",m:"adj. 强烈的",c:"intense competition"},
    {w:"intention",p:"/ɪnˈtenʃn/",m:"n. 意图",c:"good intention"},
    {w:"interact",p:"/ˌɪntərˈækt/",m:"v. 互动",c:"interact with"},
    {w:"interpret",p:"/ɪnˈtɜːprɪt/",m:"v. 解释，口译",c:"interpret as"},
    {w:"interval",p:"/ˈɪntəvl/",m:"n. 间隔",c:"at regular intervals"},
    {w:"interview",p:"/ˈɪntəvjuː/",m:"n./v. 面试",c:"job interview"},
    {w:"invest",p:"/ɪnˈvest/",m:"v. 投资",c:"invest in"},
    {w:"investigate",p:"/ɪnˈvestɪɡeɪt/",m:"v. 调查",c:"investigate the case"},
    {w:"investment",p:"/ɪnˈvestmənt/",m:"n. 投资",c:"return on investment"},
    {w:"involve",p:"/ɪnˈvɒlv/",m:"v. 涉及",c:"involve in"},
    {w:"isolate",p:"/ˈaɪsəleɪt/",m:"v. 隔离",c:"isolate from"},
    {w:"issue",p:"/ˈɪʃuː/",m:"n. 问题 v. 发行",c:"social issue"},
    {w:"item",p:"/ˈaɪtəm/",m:"n. 项目",c:"line item"},
    {w:"joint",p:"/dʒɔɪnt/",m:"adj. 联合的 n. 关节",c:"joint effort"},
    {w:"journal",p:"/ˈdʒɜːnl/",m:"n. 期刊",c:"academic journal"},
    {w:"judgment",p:"/ˈdʒʌdʒmənt/",m:"n. 判断",c:"good judgment"},
    {w:"justice",p:"/ˈdʒʌstɪs/",m:"n. 公正",c:"social justice"},
    {w:"justify",p:"/ˈdʒʌstɪfaɪ/",m:"v. 证明…正当",c:"justify the cost"},
    {w:"keen",p:"/kiːn/",m:"adj. 热衷的",c:"be keen on"},
    {w:"label",p:"/ˈleɪbl/",m:"n. 标签 v. 标注",c:"warning label"},
    {w:"landscape",p:"/ˈlændskeɪp/",m:"n. 风景",c:"urban landscape"},
    {w:"largely",p:"/ˈlɑːdʒli/",m:"adv. 很大程度上",c:"largely due to"},
    {w:"launch",p:"/lɔːntʃ/",m:"v./n. 发射，启动",c:"launch a product"},
    {w:"layer",p:"/ˈleɪər/",m:"n. 层",c:"ozone layer"},
    {w:"layout",p:"/ˈleɪaʊt/",m:"n. 布局",c:"page layout"},
    {w:"leadership",p:"/ˈliːdəʃɪp/",m:"n. 领导能力",c:"under the leadership"},
    {w:"leak",p:"/liːk/",m:"v./n. 泄漏",c:"leak information"},
    {w:"legal",p:"/ˈliːɡl/",m:"adj. 合法的",c:"legal system"},
    {w:"legislation",p:"/ˌledʒɪsˈleɪʃn/",m:"n. 立法",c:"pass legislation"},
    {w:"leisure",p:"/ˈleʒər/",m:"n. 闲暇",c:"leisure time"},
    {w:"lest",p:"/lest/",m:"conj. 唯恐",c:"lest we forget"},
    {w:"liability",p:"/ˌlaɪəˈbɪləti/",m:"n. 责任",c:"legal liability"},
    {w:"liberal",p:"/ˈlɪbərəl/",m:"adj. 自由的",c:"liberal arts"},
    {w:"liberty",p:"/ˈlɪbəti/",m:"n. 自由",c:"take the liberty"},
    {w:"license",p:"/ˈlaɪsns/",m:"n. 许可证 v. 许可",c:"driver's license"},
    {w:"likewise",p:"/ˈlaɪkwaɪz/",m:"adv. 同样地",c:"do likewise"},
    {w:"limitation",p:"/ˌlɪmɪˈteɪʃn/",m:"n. 限制",c:"statute of limitations"},
    {w:"link",p:"/lɪŋk/",m:"n. 链接 v. 联系",c:"link to"},
    {w:"literature",p:"/ˈlɪtrətʃər/",m:"n. 文学",c:"English literature"},
    {w:"loan",p:"/ləʊn/",m:"n. 贷款 v. 借出",c:"bank loan"},
    {w:"logic",p:"/ˈlɒdʒɪk/",m:"n. 逻辑",c:"logic thinking"},
    {w:"loyalty",p:"/ˈlɔɪəlti/",m:"n. 忠诚",c:"brand loyalty"},
    {w:"luxury",p:"/ˈlʌkʃəri/",m:"n. 奢侈",c:"luxury goods"},
    {w:"maintain",p:"/meɪnˈteɪn/",m:"v. 维持",c:"maintain order"},
    {w:"manual",p:"/ˈmænjuəl/",m:"adj. 手工的 n. 手册",c:"user manual"},
    {w:"manufacture",p:"/ˌmænjuˈfæktʃər/",m:"v./n. 制造",c:"manufacture goods"},
    {w:"margin",p:"/ˈmɑːdʒɪn/",m:"n. 边缘，利润",c:"profit margin"},
    {w:"massive",p:"/ˈmæsɪv/",m:"adj. 巨大的",c:"massive change"},
    {w:"mature",p:"/məˈtʃʊər/",m:"adj. 成熟的",c:"mature market"},
    {w:"maximum",p:"/ˈmæksɪməm/",m:"n. 最大(值)",c:"maximum capacity"},
    {w:"mechanism",p:"/ˈmekənɪzəm/",m:"n. 机制",c:"defense mechanism"},
    {w:"media",p:"/ˈmiːdiə/",m:"n. 媒体",c:"social media"},
    {w:"medium",p:"/ˈmiːdiəm/",m:"n. 媒介 adj. 中等的",c:"medium size"},
    {w:"mental",p:"/ˈmentl/",m:"adj. 心理的",c:"mental health"},
    {w:"mention",p:"/ˈmenʃn/",m:"v./n. 提及",c:"not to mention"},
    {w:"merchant",p:"/ˈmɜːtʃənt/",m:"n. 商人",c:"merchant ship"},
    {w:"mercy",p:"/ˈmɜːsi/",m:"n. 仁慈",c:"at the mercy of"},
    {w:"mild",p:"/maɪld/",m:"adj. 温和的",c:"mild climate"},
    {w:"military",p:"/ˈmɪlətri/",m:"adj. 军事的",c:"military service"},
    {w:"minimum",p:"/ˈmɪnɪməm/",m:"n. 最小(值)",c:"minimum wage"},
    {w:"minor",p:"/ˈmaɪnər/",m:"adj. 较小的",c:"minor role"},
    {w:"minority",p:"/maɪˈnɒrəti/",m:"n. 少数",c:"ethnic minority"},
    {w:"miracle",p:"/ˈmɪrəkl/",m:"n. 奇迹",c:"economic miracle"},
    {w:"mission",p:"/ˈmɪʃn/",m:"n. 使命",c:"carry out a mission"},
    {w:"mobile",p:"/ˈməʊbaɪl/",m:"adj. 移动的",c:"mobile phone"},
    {w:"moderate",p:"/ˈmɒdərət/",m:"adj. 适度的",c:"moderate exercise"},
    {w:"modify",p:"/ˈmɒdɪfaɪ/",m:"v. 修改",c:"modify behavior"},
    {w:"monitor",p:"/ˈmɒnɪtər/",m:"v. 监控 n. 显示器",c:"monitor progress"},
    {w:"moral",p:"/ˈmɒrəl/",m:"adj. 道德的 n. 寓意",c:"moral value"},
    {w:"moreover",p:"/mɔːrˈəʊvər/",m:"adv. 此外",c:"moreover important"},
    {w:"motion",p:"/ˈməʊʃn/",m:"n. 运动",c:"in motion"},
    {w:"motivate",p:"/ˈməʊtɪveɪt/",m:"v. 激励",c:"motivate employees"},
    {w:"motive",p:"/ˈməʊtɪv/",m:"n. 动机",c:"motive for murder"},
    {w:"multiple",p:"/ˈmʌltɪpl/",m:"adj. 多重的",c:"multiple times"},
    {w:"mutual",p:"/ˈmjuːtʃuəl/",m:"adj. 相互的",c:"mutual benefit"},
    {w:"narrative",p:"/ˈnærətɪv/",m:"n. 叙述",c:"personal narrative"},
    {w:"narrow",p:"/ˈnærəʊ/",m:"adj. 狭窄的",c:"narrow down"},
    {w:"negotiate",p:"/nɪˈɡəʊʃieɪt/",m:"v. 谈判",c:"negotiate with"},
    {w:"neighborhood",p:"/ˈneɪbəhʊd/",m:"n. 附近",c:"in the neighborhood"},
    {w:"neutral",p:"/ˈnjuːtrəl/",m:"adj. 中立的",c:"neutral position"},
    {w:"nevertheless",p:"/ˌnevəðəˈles/",m:"adv. 然而",c:"but nevertheless"},
    {w:"notion",p:"/ˈnəʊʃn/",m:"n. 概念",c:"have no notion"},
    {w:"numerous",p:"/ˈnjuːmərəs/",m:"adj. 许多的",c:"numerous times"},
    {w:"objection",p:"/əbˈdʒekʃn/",m:"n. 反对",c:"raise an objection"},
    {w:"objective",p:"/əbˈdʒektɪv/",m:"n. 目标 adj. 客观的",c:"achieve objective"},
    {w:"obligation",p:"/ˌɒblɪˈɡeɪʃn/",m:"n. 义务",c:"legal obligation"},
    {w:"observe",p:"/əbˈzɜːv/",m:"v. 观察，遵守",c:"observe rules"},
    {w:"obstacle",p:"/ˈɒbstəkl/",m:"n. 障碍",c:"overcome obstacles"},
    {w:"obtain",p:"/əbˈteɪn/",m:"v. 获得",c:"obtain information"},
    {w:"obvious",p:"/ˈɒbviəs/",m:"adj. 明显的",c:"obvious reason"},
    {w:"occasion",p:"/əˈkeɪʒn/",m:"n. 场合",c:"on occasion"},
    {w:"occasional",p:"/əˈkeɪʒənl/",m:"adj. 偶然的",c:"occasional visit"},
    {w:"occupy",p:"/ˈɒkjupaɪ/",m:"v. 占据",c:"occupy time"},
    {w:"offense",p:"/əˈfens/",m:"n. 冒犯，犯罪",c:"criminal offense"},
    {w:"ongoing",p:"/ˈɒnɡəʊɪŋ/",m:"adj. 进行中的",c:"ongoing project"},
    {w:"operate",p:"/ˈɒpəreɪt/",m:"v. 操作",c:"operate a machine"},
    {w:"opponent",p:"/əˈpəʊnənt/",m:"n. 对手",c:"political opponent"},
    {w:"opportunity",p:"/ˌɒpəˈtjuːnəti/",m:"n. 机会",c:"seize the opportunity"},
    {w:"oppose",p:"/əˈpəʊz/",m:"v. 反对",c:"oppose the plan"},
    {w:"option",p:"/ˈɒpʃn/",m:"n. 选择",c:"have no option"},
    {w:"organic",p:"/ɔːˈɡænɪk/",m:"adj. 有机的",c:"organic food"},
    {w:"organize",p:"/ˈɔːɡənaɪz/",m:"v. 组织",c:"organize an event"},
    {w:"original",p:"/əˈrɪdʒənl/",m:"adj. 原来的，独创的",c:"original idea"},
    {w:"otherwise",p:"/ˈʌðəwaɪz/",m:"adv. 否则",c:"or otherwise"},
    {w:"outcome",p:"/ˈaʊtkʌm/",m:"n. 结果",c:"final outcome"},
    {w:"outstanding",p:"/aʊtˈstændɪŋ/",m:"adj. 杰出的",c:"outstanding achievement"},
    {w:"overall",p:"/ˌəʊvərˈɔːl/",m:"adj. 总体的",c:"overall performance"},
    {w:"overcome",p:"/ˌəʊvəˈkʌm/",m:"v. 克服",c:"overcome difficulties"},
    {w:"overlook",p:"/ˌəʊvəˈlʊk/",m:"v. 忽视",c:"overlook the fact"},
    {w:"overseas",p:"/ˌəʊvəˈsiːz/",m:"adv./adj. 海外(的)",c:"overseas market"},
    {w:"owe",p:"/əʊ/",m:"v. 欠，归功于",c:"owe to"},
    {w:"ownership",p:"/ˈəʊnəʃɪp/",m:"n. 所有权",c:"sense of ownership"},
    {w:"pace",p:"/peɪs/",m:"n. 速度",c:"keep pace with"},
    {w:"panel",p:"/ˈpænl/",m:"n. 面板，小组",c:"control panel"},
    {w:"parallel",p:"/ˈpærəlel/",m:"adj. 平行的",c:"in parallel"},
    {w:"participate",p:"/pɑːˈtɪsɪpeɪt/",m:"v. 参与",c:"participate in"},
    {w:"particular",p:"/pəˈtɪkjələr/",m:"adj. 特定的",c:"in particular"},
    {w:"passion",p:"/ˈpæʃn/",m:"n. 激情",c:"passion for"},
    {w:"passive",p:"/ˈpæsɪv/",m:"adj. 被动的",c:"passive voice"},
    {w:"patent",p:"/ˈpætnt/",m:"n. 专利",c:"patent application"},
    {w:"pension",p:"/ˈpenʃn/",m:"n. 养老金",c:"pension fund"},
    {w:"perceive",p:"/pəˈsiːv/",m:"v. 感知",c:"perceive as"},
    {w:"percentage",p:"/pəˈsentɪdʒ/",m:"n. 百分比",c:"small percentage"},
    {w:"permanent",p:"/ˈpɜːmənənt/",m:"adj. 永久的",c:"permanent resident"},
    {w:"permit",p:"/pəˈmɪt/",m:"v. 允许 n. 许可证",c:"permit to"},
    {w:"persist",p:"/pəˈsɪst/",m:"v. 坚持",c:"persist in"},
    {w:"personality",p:"/ˌpɜːsəˈnæləti/",m:"n. 个性",c:"strong personality"},
    {w:"perspective",p:"/pəˈspektɪv/",m:"n. 观点",c:"from a perspective"},
    {w:"phenomenon",p:"/fɪˈnɒmɪnən/",m:"n. 现象",c:"natural phenomenon"},
    {w:"philosophy",p:"/fɪˈlɒsəfi/",m:"n. 哲学",c:"life philosophy"},
    {w:"physical",p:"/ˈfɪzɪkl/",m:"adj. 身体的，物理的",c:"physical exercise"},
    {w:"pioneer",p:"/ˌpaɪəˈnɪər/",m:"n. 先驱 v. 开拓",c:"pioneer spirit"},
    {w:"pledge",p:"/pledʒ/",m:"n./v. 保证",c:"take a pledge"},
    {w:"policy",p:"/ˈpɒləsi/",m:"n. 政策",c:"foreign policy"},
    {w:"pollution",p:"/pəˈluːʃn/",m:"n. 污染",c:"air pollution"},
    {w:"portion",p:"/ˈpɔːʃn/",m:"n. 部分",c:"a large portion"},
    {w:"pose",p:"/pəʊz/",m:"v. 造成，摆姿势",c:"pose a threat"},
    {w:"positive",p:"/ˈpɒzətɪv/",m:"adj. 积极的",c:"positive attitude"},
    {w:"possess",p:"/pəˈzes/",m:"v. 拥有",c:"possess skills"},
    {w:"potential",p:"/pəˈtenʃl/",m:"adj. 潜在的 n. 潜力",c:"great potential"},
    {w:"poverty",p:"/ˈpɒvəti/",m:"n. 贫穷",c:"poverty line"},
    {w:"precaution",p:"/prɪˈkɔːʃn/",m:"n. 预防措施",c:"take precautions"},
    {w:"prediction",p:"/prɪˈdɪkʃn/",m:"n. 预测",c:"make a prediction"},
    {w:"preference",p:"/ˈprefrəns/",m:"n. 偏爱",c:"personal preference"},
    {w:"prejudice",p:"/ˈpredʒədɪs/",m:"n. 偏见",c:"racial prejudice"},
    {w:"presence",p:"/ˈprezns/",m:"n. 出席，存在",c:"in the presence of"},
    {w:"preserve",p:"/prɪˈzɜːv/",m:"v. 保护",c:"preserve history"},
    {w:"pressure",p:"/ˈpreʃər/",m:"n. 压力",c:"under pressure"},
    {w:"presumably",p:"/prɪˈzjuːməbli/",m:"adv. 大概",c:"presumably correct"},
    {w:"prevail",p:"/prɪˈveɪl/",m:"v. 盛行",c:"prevail over"},
    {w:"previous",p:"/ˈpriːviəs/",m:"adj. 以前的",c:"previous experience"},
    {w:"pride",p:"/praɪd/",m:"n. 骄傲 v. 自豪",c:"take pride in"},
    {w:"primary",p:"/ˈpraɪməri/",m:"adj. 主要的，初级的",c:"primary school"},
    {w:"prime",p:"/praɪm/",m:"adj. 首要的",c:"prime minister"},
    {w:"principal",p:"/ˈprɪnsəpl/",m:"adj. 主要的 n. 校长",c:"principal reason"},
    {w:"principle",p:"/ˈprɪnsəpl/",m:"n. 原则",c:"in principle"},
    {w:"prior",p:"/ˈpraɪər/",m:"adj. 先前的",c:"prior to"},
    {w:"priority",p:"/praɪˈɒrəti/",m:"n. 优先",c:"top priority"},
    {w:"procedure",p:"/prəˈsiːdʒər/",m:"n. 程序",c:"standard procedure"},
    {w:"proceed",p:"/prəˈsiːd/",m:"v. 继续",c:"proceed with"},
    {w:"process",p:"/ˈprəʊses/",m:"n. 过程 v. 处理",c:"in the process"},
    {w:"profession",p:"/prəˈfeʃn/",m:"n. 职业",c:"medical profession"},
    {w:"professional",p:"/prəˈfeʃənl/",m:"adj. 专业的",c:"professional service"},
    {w:"profit",p:"/ˈprɒfɪt/",m:"n. 利润 v. 受益",c:"make a profit"},
    {w:"profound",p:"/prəˈfaʊnd/",m:"adj. 深刻的",c:"profound impact"},
    {w:"prohibit",p:"/prəˈhɪbɪt/",m:"v. 禁止",c:"strictly prohibit"},
    {w:"prominent",p:"/ˈprɒmɪnənt/",m:"adj. 突出的",c:"prominent figure"},
    {w:"promote",p:"/prəˈməʊt/",m:"v. 促进，提升",c:"promote growth"},
    {w:"promotion",p:"/prəˈməʊʃn/",m:"n. 晋升",c:"sales promotion"},
    {w:"proof",p:"/pruːf/",m:"n. 证据",c:"proof of identity"},
    {w:"property",p:"/ˈprɒpəti/",m:"n. 财产",c:"intellectual property"},
    {w:"proportion",p:"/prəˈpɔːʃn/",m:"n. 比例",c:"in proportion to"},
    {w:"proposal",p:"/prəˈpəʊzl/",m:"n. 提议",c:"make a proposal"},
    {w:"propose",p:"/prəˈpəʊz/",m:"v. 提议",c:"propose a plan"},
    {w:"prospect",p:"/ˈprɒspekt/",m:"n. 前景",c:"job prospects"},
    {w:"prosperity",p:"/prɒˈsperəti/",m:"n. 繁荣",c:"economic prosperity"},
    {w:"protest",p:"/ˈprəʊtest/",m:"n./v. 抗议",c:"protest against"},
    {w:"provision",p:"/prəˈvɪʒn/",m:"n. 供应，条款",c:"make provision for"},
    {w:"publication",p:"/ˌpʌblɪˈkeɪʃn/",m:"n. 出版(物)",c:"scientific publication"},
    {w:"publish",p:"/ˈpʌblɪʃ/",m:"v. 出版",c:"publish a book"},
    {w:"purchase",p:"/ˈpɜːtʃəs/",m:"v./n. 购买",c:"purchase online"},
    {w:"pursue",p:"/pəˈsjuː/",m:"v. 追求",c:"pursue a dream"},
    {w:"qualification",p:"/ˌkwɒlɪfɪˈkeɪʃn/",m:"n. 资格",c:"academic qualification"},
    {w:"quality",p:"/ˈkwɒləti/",m:"n. 质量",c:"high quality"},
    {w:"quantity",p:"/ˈkwɒntəti/",m:"n. 数量",c:"large quantity"},
    {w:"racial",p:"/ˈreɪʃl/",m:"adj. 种族的",c:"racial discrimination"},
    {w:"radical",p:"/ˈrædɪkl/",m:"adj. 根本的，激进的",c:"radical change"},
    {w:"range",p:"/reɪndʒ/",m:"n. 范围 v. 变化",c:"wide range"},
    {w:"rank",p:"/ræŋk/",m:"n. 等级 v. 排列",c:"rank first"},
    {w:"rapid",p:"/ˈræpɪd/",m:"adj. 迅速的",c:"rapid growth"},
    {w:"rarely",p:"/ˈreəli/",m:"adv. 很少",c:"rarely seen"},
    {w:"rate",p:"/reɪt/",m:"n. 比率 v. 评价",c:"interest rate"},
    {w:"rational",p:"/ˈræʃnəl/",m:"adj. 理性的",c:"rational decision"},
    {w:"react",p:"/riˈækt/",m:"v. 反应",c:"react to"},
    {w:"readily",p:"/ˈredɪli/",m:"adv. 乐意地",c:"readily available"},
    {w:"realistic",p:"/ˌriːəˈlɪstɪk/",m:"adj. 现实的",c:"realistic goal"},
    {w:"reality",p:"/riˈæləti/",m:"n. 现实",c:"in reality"},
    {w:"reasonable",p:"/ˈriːznəbl/",m:"adj. 合理的",c:"reasonable price"},
    {w:"recall",p:"/rɪˈkɔːl/",m:"v./n. 回忆",c:"recall the past"},
    {w:"recession",p:"/rɪˈseʃn/",m:"n. 衰退",c:"economic recession"},
    {w:"recognition",p:"/ˌrekəɡˈnɪʃn/",m:"n. 认可",c:"facial recognition"},
    {w:"recommend",p:"/ˌrekəˈmend/",m:"v. 推荐",c:"highly recommend"},
    {w:"recover",p:"/rɪˈkʌvər/",m:"v. 恢复",c:"recover from"},
    {w:"reduction",p:"/rɪˈdʌkʃn/",m:"n. 减少",c:"cost reduction"},
    {w:"refer",p:"/rɪˈfɜːr/",m:"v. 参考",c:"refer to"},
    {w:"reference",p:"/ˈrefrəns/",m:"n. 参考",c:"for reference"},
    {w:"reflect",p:"/rɪˈflekt/",m:"v. 反映",c:"reflect on"},
    {w:"reform",p:"/rɪˈfɔːm/",m:"v./n. 改革",c:"economic reform"},
    {w:"regarding",p:"/rɪˈɡɑːdɪŋ/",m:"prep. 关于",c:"regarding this matter"},
    {w:"regardless",p:"/rɪˈɡɑːdləs/",m:"adv. 不管怎样",c:"regardless of"},
    {w:"region",p:"/ˈriːdʒən/",m:"n. 地区",c:"in the region"},
    {w:"register",p:"/ˈredʒɪstər/",m:"v./n. 登记",c:"register for"},
    {w:"regulate",p:"/ˈreɡjuleɪt/",m:"v. 管理",c:"regulate temperature"},
    {w:"regulation",p:"/ˌreɡjuˈleɪʃn/",m:"n. 法规",c:"government regulation"},
    {w:"reinforce",p:"/ˌriːɪnˈfɔːs/",m:"v. 加强",c:"reinforce the idea"},
    {w:"reject",p:"/rɪˈdʒekt/",m:"v. 拒绝",c:"reject an offer"},
    {w:"relate",p:"/rɪˈleɪt/",m:"v. 联系",c:"relate to"},
    {w:"release",p:"/rɪˈliːs/",m:"v./n. 释放，发布",c:"press release"},
    {w:"relevant",p:"/ˈreləvənt/",m:"adj. 相关的",c:"relevant information"},
    {w:"reliable",p:"/rɪˈlaɪəbl/",m:"adj. 可靠的",c:"reliable source"},
    {w:"relief",p:"/rɪˈliːf/",m:"n. 减轻",c:"pain relief"},
    {w:"rely",p:"/rɪˈlaɪ/",m:"v. 依赖",c:"rely on"},
    {w:"remark",p:"/rɪˈmɑːk/",m:"n./v. 评论",c:"make a remark"},
    {w:"remarkable",p:"/rɪˈmɑːkəbl/",m:"adj. 非凡的",c:"remarkable achievement"},
    {w:"remedy",p:"/ˈremədi/",m:"n. 补救办法",c:"legal remedy"},
    {w:"remote",p:"/rɪˈməʊt/",m:"adj. 遥远的",c:"remote control"},
    {w:"render",p:"/ˈrendər/",m:"v. 使成为",c:"render service"},
    {w:"represent",p:"/ˌreprɪˈzent/",m:"v. 代表",c:"represent interests"},
    {w:"reputation",p:"/ˌrepjuˈteɪʃn/",m:"n. 声誉",c:"good reputation"},
    {w:"request",p:"/rɪˈkwest/",m:"n./v. 请求",c:"make a request"},
    {w:"require",p:"/rɪˈkwaɪər/",m:"v. 需要",c:"require attention"},
    {w:"requirement",p:"/rɪˈkwaɪəmənt/",m:"n. 要求",c:"meet requirements"},
    {w:"rescue",p:"/ˈreskjuː/",m:"v./n. 营救",c:"rescue team"},
    {w:"resemble",p:"/rɪˈzembl/",m:"v. 相似",c:"resemble each other"},
    {w:"reserve",p:"/rɪˈzɜːv/",m:"v. 预订 n. 储备",c:"reserve a table"},
    {w:"resist",p:"/rɪˈzɪst/",m:"v. 抵抗",c:"resist temptation"},
    {w:"resolve",p:"/rɪˈzɒlv/",m:"v. 解决",c:"resolve conflicts"},
    {w:"resort",p:"/rɪˈzɔːt/",m:"v. 诉诸 n. 度假胜地",c:"resort to"},
    {w:"resource",p:"/rɪˈzɔːs/",m:"n. 资源",c:"human resource"},
    {w:"respond",p:"/rɪˈspɒnd/",m:"v. 回应",c:"respond to"},
    {w:"response",p:"/rɪˈspɒns/",m:"n. 回应",c:"in response to"},
    {w:"responsibility",p:"/rɪˌspɒnsəˈbɪləti/",m:"n. 责任",c:"take responsibility"},
    {w:"restore",p:"/rɪˈstɔːr/",m:"v. 恢复",c:"restore order"},
    {w:"restrict",p:"/rɪˈstrɪkt/",m:"v. 限制",c:"restrict access"},
    {w:"reveal",p:"/rɪˈviːl/",m:"v. 揭示",c:"reveal secrets"},
    {w:"revenue",p:"/ˈrevənjuː/",m:"n. 收入",c:"tax revenue"},
    {w:"revolution",p:"/ˌrevəˈluːʃn/",m:"n. 革命",c:"industrial revolution"},
    {w:"reward",p:"/rɪˈwɔːd/",m:"n. 奖赏 v. 报答",c:"reward for"},
    {w:"risk",p:"/rɪsk/",m:"n. 风险 v. 冒险",c:"take a risk"},
    {w:"rival",p:"/ˈraɪvl/",m:"n. 对手 v. 竞争",c:"rival company"},
    {w:"role",p:"/rəʊl/",m:"n. 角色",c:"play a role"},
    {w:"routine",p:"/ruːˈtiːn/",m:"n. 常规",c:"daily routine"},
    {w:"rural",p:"/ˈrʊərəl/",m:"adj. 农村的",c:"rural area"},
    {w:"sacrifice",p:"/ˈsækrɪfaɪs/",m:"n./v. 牺牲",c:"make a sacrifice"},
    {w:"salary",p:"/ˈsæləri/",m:"n. 薪水",c:"annual salary"},
    {w:"satisfaction",p:"/ˌsætɪsˈfækʃn/",m:"n. 满意",c:"customer satisfaction"},
    {w:"scale",p:"/skeɪl/",m:"n. 规模",c:"on a large scale"},
    {w:"scan",p:"/skæn/",m:"v./n. 扫描",c:"scan through"},
    {w:"schedule",p:"/ˈʃedjuːl/",m:"n. 时间表 v. 安排",c:"on schedule"},
    {w:"scheme",p:"/skiːm/",m:"n. 方案",c:"color scheme"},
    {w:"scholar",p:"/ˈskɒlər/",m:"n. 学者",c:"visiting scholar"},
    {w:"scholarship",p:"/ˈskɒləʃɪp/",m:"n. 奖学金",c:"win a scholarship"},
    {w:"scope",p:"/skəʊp/",m:"n. 范围",c:"within the scope"},
    {w:"sector",p:"/ˈsektər/",m:"n. 部门",c:"private sector"},
    {w:"secure",p:"/sɪˈkjʊər/",m:"adj. 安全的 v. 获得",c:"secure job"},
    {w:"security",p:"/sɪˈkjʊərəti/",m:"n. 安全",c:"national security"},
    {w:"senior",p:"/ˈsiːniər/",m:"adj. 高级的 n. 年长者",c:"senior manager"},
    {w:"sensation",p:"/senˈseɪʃn/",m:"n. 感觉",c:"cause a sensation"},
    {w:"sensitive",p:"/ˈsensətɪv/",m:"adj. 敏感的",c:"sensitive information"},
    {w:"sequence",p:"/ˈsiːkwəns/",m:"n. 顺序",c:"in sequence"},
    {w:"session",p:"/ˈseʃn/",m:"n. 会议",c:"training session"},
    {w:"severe",p:"/sɪˈvɪər/",m:"adj. 严重的",c:"severe weather"},
    {w:"shelter",p:"/ˈʃeltər/",m:"n. 庇护所",c:"take shelter"},
    {w:"shift",p:"/ʃɪft/",m:"v./n. 转移，轮班",c:"night shift"},
    {w:"shortage",p:"/ˈʃɔːtɪdʒ/",m:"n. 短缺",c:"water shortage"},
    {w:"significant",p:"/sɪɡˈnɪfɪkənt/",m:"adj. 重要的",c:"significant role"},
    {w:"similar",p:"/ˈsɪmələr/",m:"adj. 相似的",c:"similar to"},
    {w:"simplify",p:"/ˈsɪmplɪfaɪ/",m:"v. 简化",c:"simplify the process"},
    {w:"site",p:"/saɪt/",m:"n. 地点",c:"construction site"},
    {w:"slight",p:"/slaɪt/",m:"adj. 轻微的",c:"slight change"},
    {w:"sole",p:"/səʊl/",m:"adj. 唯一的",c:"sole purpose"},
    {w:"solid",p:"/ˈsɒlɪd/",m:"adj. 固体的 n. 固体",c:"solid foundation"},
    {w:"solution",p:"/səˈluːʃn/",m:"n. 解决方案",c:"find a solution"},
    {w:"source",p:"/sɔːs/",m:"n. 来源",c:"energy source"},
    {w:"span",p:"/spæn/",m:"n. 跨度 v. 跨越",c:"life span"},
    {w:"specialist",p:"/ˈspeʃəlɪst/",m:"n. 专家",c:"heart specialist"},
    {w:"species",p:"/ˈspiːʃiːz/",m:"n. 物种",c:"endangered species"},
    {w:"specific",p:"/spəˈsɪfɪk/",m:"adj. 具体的",c:"specific area"},
    {w:"spiritual",p:"/ˈspɪrɪtʃuəl/",m:"adj. 精神的",c:"spiritual life"},
    {w:"sponsor",p:"/ˈspɒnsər/",m:"v./n. 赞助",c:"sponsor an event"},
    {w:"stable",p:"/ˈsteɪbl/",m:"adj. 稳定的",c:"stable economy"},
    {w:"staff",p:"/stɑːf/",m:"n. 员工",c:"staff meeting"},
    {w:"standard",p:"/ˈstændəd/",m:"n. 标准 adj. 标准的",c:"high standard"},
    {w:"status",p:"/ˈsteɪtəs/",m:"n. 地位，状态",c:"social status"},
    {w:"steady",p:"/ˈstedi/",m:"adj. 稳定的",c:"steady growth"},
    {w:"stem",p:"/stem/",m:"n. 茎 v. 起源于",c:"stem from"},
    {w:"stimulate",p:"/ˈstɪmjuleɪt/",m:"v. 刺激",c:"stimulate growth"},
    {w:"stock",p:"/stɒk/",m:"n. 库存，股票",c:"stock market"},
    {w:"strategy",p:"/ˈstrætədʒi/",m:"n. 策略",c:"marketing strategy"},
    {w:"strengthen",p:"/ˈstreŋθn/",m:"v. 加强",c:"strengthen ties"},
    {w:"structure",p:"/ˈstrʌktʃər/",m:"n. 结构",c:"social structure"},
    {w:"submit",p:"/səbˈmɪt/",m:"v. 提交",c:"submit a report"},
    {w:"substance",p:"/ˈsʌbstəns/",m:"n. 物质",c:"chemical substance"},
    {w:"substitute",p:"/ˈsʌbstɪtjuːt/",m:"n. 替代品 v. 替代",c:"substitute for"},
    {w:"sufficient",p:"/səˈfɪʃnt/",m:"adj. 足够的",c:"sufficient evidence"},
    {w:"summary",p:"/ˈsʌməri/",m:"n. 摘要",c:"in summary"},
    {w:"superior",p:"/suːˈpɪəriər/",m:"adj. 优越的",c:"superior quality"},
    {w:"supplement",p:"/ˈsʌplɪment/",m:"n. 补充 v. 增补",c:"dietary supplement"},
    {w:"supreme",p:"/suːˈpriːm/",m:"adj. 最高的",c:"supreme court"},
    {w:"surplus",p:"/ˈsɜːpləs/",m:"n. 过剩 adj. 多余的",c:"budget surplus"},
    {w:"survey",p:"/ˈsɜːveɪ/",m:"n./v. 调查",c:"conduct a survey"},
    {w:"survival",p:"/səˈvaɪvl/",m:"n. 幸存",c:"survival skills"},
    {w:"suspect",p:"/səˈspekt/",m:"v. 怀疑 n. 嫌疑人",c:"suspect of"},
    {w:"suspend",p:"/səˈspend/",m:"v. 暂停",c:"suspend operations"},
    {w:"sustain",p:"/səˈsteɪn/",m:"v. 维持",c:"sustain growth"},
    {w:"symbol",p:"/ˈsɪmbl/",m:"n. 象征",c:"status symbol"},
    {w:"symptom",p:"/ˈsɪmptəm/",m:"n. 症状",c:"common symptom"},
    {w:"target",p:"/ˈtɑːɡɪt/",m:"n. 目标 v. 瞄准",c:"target audience"},
    {w:"technique",p:"/tekˈniːk/",m:"n. 技术",c:"management technique"},
    {w:"temporary",p:"/ˈtemprəri/",m:"adj. 暂时的",c:"temporary solution"},
    {w:"tendency",p:"/ˈtendənsi/",m:"n. 趋势",c:"have a tendency to"},
    {w:"terminal",p:"/ˈtɜːmɪnl/",m:"n. 终点站 adj. 终端的",c:"airport terminal"},
    {w:"territory",p:"/ˈterətri/",m:"n. 领土",c:"new territory"},
    {w:"theme",p:"/θiːm/",m:"n. 主题",c:"main theme"},
    {w:"theory",p:"/ˈθɪəri/",m:"n. 理论",c:"in theory"},
    {w:"therapy",p:"/ˈθerəpi/",m:"n. 治疗",c:"physical therapy"},
    {w:"thorough",p:"/ˈθʌrə/",m:"adj. 彻底的",c:"thorough investigation"},
    {w:"threat",p:"/θret/",m:"n. 威胁",c:"pose a threat"},
    {w:"thrive",p:"/θraɪv/",m:"v. 繁荣",c:"thrive on"},
    {w:"tolerate",p:"/ˈtɒləreɪt/",m:"v. 容忍",c:"tolerate behavior"},
    {w:"tone",p:"/təʊn/",m:"n. 语气",c:"tone of voice"},
    {w:"topic",p:"/ˈtɒpɪk/",m:"n. 话题",c:"hot topic"},
    {w:"tough",p:"/tʌf/",m:"adj. 艰苦的",c:"tough decision"},
    {w:"trace",p:"/treɪs/",m:"v. 追踪 n. 痕迹",c:"trace back to"},
    {w:"tradition",p:"/trəˈdɪʃn/",m:"n. 传统",c:"cultural tradition"},
    {w:"transaction",p:"/trænˈzækʃn/",m:"n. 交易",c:"business transaction"},
    {w:"transfer",p:"/trænsˈfɜːr/",m:"v./n. 转移",c:"transfer money"},
    {w:"transform",p:"/trænsˈfɔːm/",m:"v. 改变",c:"transform into"},
    {w:"tremendous",p:"/trəˈmendəs/",m:"adj. 巨大的",c:"tremendous effort"},
    {w:"trend",p:"/trend/",m:"n. 趋势",c:"current trend"},
    {w:"trial",p:"/ˈtraɪəl/",m:"n. 审判，试验",c:"clinical trial"},
    {w:"triumph",p:"/ˈtraɪʌmf/",m:"n. 胜利",c:"moment of triumph"},
    {w:"typical",p:"/ˈtɪpɪkl/",m:"adj. 典型的",c:"typical example"},
    {w:"ultimate",p:"/ˈʌltɪmət/",m:"adj. 最终的",c:"ultimate goal"},
    {w:"undergo",p:"/ˌʌndəˈɡəʊ/",m:"v. 经历",c:"undergo surgery"},
    {w:"undermine",p:"/ˌʌndəˈmaɪn/",m:"v. 削弱",c:"undermine confidence"},
    {w:"undertake",p:"/ˌʌndəˈteɪk/",m:"v. 承担",c:"undertake a task"},
    {w:"unemployment",p:"/ˌʌnɪmˈplɔɪmənt/",m:"n. 失业",c:"unemployment rate"},
    {w:"unique",p:"/juˈniːk/",m:"adj. 独特的",c:"unique feature"},
    {w:"universal",p:"/ˌjuːnɪˈvɜːsl/",m:"adj. 普遍的",c:"universal truth"},
    {w:"urban",p:"/ˈɜːbən/",m:"adj. 城市的",c:"urban area"},
    {w:"urge",p:"/ɜːdʒ/",m:"v. 敦促 n. 强烈欲望",c:"urge to do"},
    {w:"utility",p:"/juːˈtɪləti/",m:"n. 公用事业",c:"public utility"},
    {w:"utilize",p:"/ˈjuːtəlaɪz/",m:"v. 利用",c:"utilize resources"},
    {w:"vacant",p:"/ˈveɪkənt/",m:"adj. 空的，空缺的",c:"vacant position"},
    {w:"vain",p:"/veɪn/",m:"adj. 徒劳的",c:"in vain"},
    {w:"valid",p:"/ˈvælɪd/",m:"adj. 有效的",c:"valid reason"},
    {w:"vanish",p:"/ˈvænɪʃ/",m:"v. 消失",c:"vanish into thin air"},
    {w:"variable",p:"/ˈveəriəbl/",m:"adj. 可变的 n. 变量",c:"variable costs"},
    {w:"vast",p:"/vɑːst/",m:"adj. 巨大的",c:"vast majority"},
    {w:"venture",p:"/ˈventʃər/",m:"n. 风险项目 v. 冒险",c:"joint venture"},
    {w:"verify",p:"/ˈverɪfaɪ/",m:"v. 核实",c:"verify information"},
    {w:"version",p:"/ˈvɜːʃn/",m:"n. 版本",c:"latest version"},
    {w:"vessel",p:"/ˈvesl/",m:"n. 船，容器",c:"blood vessel"},
    {w:"victim",p:"/ˈvɪktɪm/",m:"n. 受害者",c:"fall victim to"},
    {w:"violate",p:"/ˈvaɪəleɪt/",m:"v. 违反",c:"violate rules"},
    {w:"violence",p:"/ˈvaɪələns/",m:"n. 暴力",c:"domestic violence"},
    {w:"virtual",p:"/ˈvɜːtʃuəl/",m:"adj. 虚拟的",c:"virtual reality"},
    {w:"virtue",p:"/ˈvɜːtʃuː/",m:"n. 美德",c:"by virtue of"},
    {w:"visible",p:"/ˈvɪzəbl/",m:"adj. 可见的",c:"visible sign"},
    {w:"vision",p:"/ˈvɪʒn/",m:"n. 视力，愿景",c:"have a vision"},
    {w:"visual",p:"/ˈvɪʒuəl/",m:"adj. 视觉的",c:"visual arts"},
    {w:"vital",p:"/ˈvaɪtl/",m:"adj. 至关重要的",c:"vital role"},
    {w:"vivid",p:"/ˈvɪvɪd/",m:"adj. 生动的",c:"vivid memory"},
    {w:"volume",p:"/ˈvɒljuːm/",m:"n. 音量，容量",c:"sales volume"},
    {w:"voluntary",p:"/ˈvɒləntri/",m:"adj. 自愿的",c:"voluntary work"},
    {w:"volunteer",p:"/ˌvɒlənˈtɪər/",m:"v./n. 志愿",c:"volunteer to help"},
    {w:"wage",p:"/weɪdʒ/",m:"n. 工资 v. 发动",c:"minimum wage"},
    {w:"wander",p:"/ˈwɒndər/",m:"v. 漫步",c:"wander around"},
    {w:"wealthy",p:"/ˈwelθi/",m:"adj. 富有的",c:"wealthy family"},
    {w:"weapon",p:"/ˈwepən/",m:"n. 武器",c:"nuclear weapon"},
    {w:"welfare",p:"/ˈwelfeər/",m:"n. 福利",c:"social welfare"},
    {w:"whereas",p:"/ˌweərˈæz/",m:"conj. 然而",c:"whereas previously"},
    {w:"widespread",p:"/ˈwaɪdspred/",m:"adj. 广泛的",c:"widespread use"},
    {w:"wisdom",p:"/ˈwɪzdəm/",m:"n. 智慧",c:"conventional wisdom"},
    {w:"withdraw",p:"/wɪðˈdrɔː/",m:"v. 撤回",c:"withdraw from"},
    {w:"withstand",p:"/wɪðˈstænd/",m:"v. 承受",c:"withstand pressure"},
    {w:"witness",p:"/ˈwɪtnəs/",m:"n. 目击者 v. 目睹",c:"witness an event"},
    {w:"worthwhile",p:"/ˌwɜːθˈwaɪl/",m:"adj. 值得的",c:"be worthwhile"},
    {w:"yield",p:"/jiːld/",m:"v. 产生，屈服",c:"yield results"},
]

# ============================================================
# 4. 从词库中选出不重复的新词
# ============================================================
bank_words = [entry for entry in CET4_BANK if entry['w'] not in existing_set]
print(f"Available in bank (non-duplicate): {len(bank_words)}")

if len(bank_words) < deficit:
    print(f"WARNING: Bank only has {len(bank_words)} new words, but need {deficit}!")
    to_add = bank_words
else:
    to_add = bank_words[:deficit]

# ============================================================
# 5. 追加到 WORD_POOL
# ============================================================
new_entries = ',\n'.join(
    '  {w:"' + e['w'] + '",p:"' + e['p'] + '",m:"' + e['m'] + '",c:"' + e['c'] + '"}'
    for e in to_add
)

# 找到池中最后一个条目并附加
# 用 ; 之后的  ]; 定位 WORD_POOL 结束
old_end = '  {w:"worthwhile",p:"/ˌwɜːθˈwaɪl/",m:"adj. 值得的",c:"be worthwhile"}\n];'
new_end = '  {w:"worthwhile",p:"/ˌwɜːθˈwaɪl/",m:"adj. 值得的",c:"be worthwhile"},\n' + new_entries + '\n];'

html = html.replace(old_end, new_end)

# ============================================================
# 6. 验证
# ============================================================
final_count = len(re.findall(r'\{w:"[^"]+"', html))
print(f"Final pool: {final_count} words")

# Check for dupes
all_final = re.findall(r'w:"([^"]+)"', html)
word_set = set()
dups = []
for w in all_final:
    if w in word_set:
        dups.append(w)
    word_set.add(w)
if dups:
    print(f"WARNING: {len(dups)} duplicate(s): {dups[:5]}...")
else:
    print(f"All {len(all_final)} words unique ✓")

# JS brace check
s = html.find('<script>')
e = html.rfind('</script>')
js = html[s:e]
open_b = js.count('{')
close_b = js.count('}')
print(f"JS braces: {open_b} vs {close_b} balanced={open_b==close_b}")

with open(PATH, 'w', encoding='utf-8') as f:
    f.write(html)

print(f"\nDone! HTML size: {len(html)} bytes")
